class_name Soldier
extends CharacterBody3D
## One soldier. At a distance it follows terrain with inexpensive steering;
## close to the player its capsule becomes solid and movement uses physics.
## Beyond LOD_DISTANCE from the camera it swaps its skinned model for a sprite.

signal died(soldier: Soldier)

const LOD_DISTANCE := 45.0
const WALK := 3.6
const RUN := 5.8
const ATTACK_RANGE := 1.7
const ENGAGE_RANGE := 9.0
const PLAYER_SOLID_RANGE := 16.0
const WORLD_LAYER := 1
const SOLDIER_LAYER := 4

var team := 0
var squad: Squad
var max_health := 40
var health := 40
var damage := 8
var slot_target := Vector3.ZERO
var combat_target: Node3D = null
var dead := false

var _look := ""
var _file := ""
var _keep: Array[String] = []
var _model: Node3D
var _anim: AnimationPlayer
var _animator: CharacterAnimator
var _impulse := Vector3.ZERO
var _guard := 0.0
## Chance to catch a hit on the shield.
var block_chance := 0.3
var _sprite: MeshInstance3D
var _actor_shape: CollisionShape3D
var _attack_cooldown := 0.0
var _busy := 0.0
var _retarget := 0.0
var _velocity := Vector3.ZERO
var _step_distance := 0.0


static func create(team_id: int, look: String, file: String, keep: Array[String]) -> Soldier:
	var s := Soldier.new()
	s.team = team_id
	s._look = look
	s._file = file
	s._keep = keep
	return s


func _ready() -> void:
	# Distant troops remain cheap; only nearby troops participate in physics.
	collision_layer = SOLDIER_LAYER
	collision_mask = WORLD_LAYER
	_actor_shape = CollisionShape3D.new()
	var capsule := CapsuleShape3D.new()
	capsule.radius = 0.34
	capsule.height = 1.65
	_actor_shape.shape = capsule
	_actor_shape.position.y = 0.825
	_actor_shape.disabled = true
	add_child(_actor_shape)
	add_to_group("team%d" % team)
	add_to_group("combatant")
	_model = Assets.character(_file, 1.75, _keep)
	add_child(_model)
	_anim = Assets.animation_player(_model)
	_animator = CharacterAnimator.new(_model, RUN, WALK)
	_sprite = MeshInstance3D.new()
	_sprite.mesh = ImpostorBaker.quad()
	_sprite.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	var baker: ImpostorBaker = get_tree().get_first_node_in_group("impostor_baker")
	if baker and baker.materials.has(_look):
		_sprite.material_override = baker.materials[_look]
	_sprite.visible = false
	add_child(_sprite)
	_retarget = randf() * 0.4


func _physics_process(delta: float) -> void:
	if dead:
		return
	_attack_cooldown -= delta
	_busy -= delta
	_guard -= delta
	_retarget -= delta
	_update_lod()
	_update_player_collision()
	if _retarget <= 0.0:
		_retarget = 0.4
		_pick_target()

	var goal := slot_target
	var engaging: bool = combat_target != null and is_instance_valid(combat_target) and not combat_target.get("dead")
	if engaging:
		goal = combat_target.global_position
	var to_goal := goal - global_position
	to_goal.y = 0.0
	var dist := to_goal.length()
	var desired := Vector3.ZERO
	if engaging and dist <= ATTACK_RANGE:
		_face(to_goal)
		if _attack_cooldown <= 0.0 and _busy <= 0.0:
			_attack()
	elif dist > 0.4:
		var speed := RUN if dist > 6.0 or engaging else WALK
		desired = to_goal / dist * minf(speed, dist * 3.0)
	desired += _separation() * 2.5
	_velocity = _velocity.lerp(desired, 8.0 * delta)
	if _busy > 0.0:
		_velocity *= 0.4
	var step_velocity := _velocity + _impulse
	var p := global_position + step_velocity * delta
	_impulse = _impulse.move_toward(Vector3.ZERO, 25.0 * delta)
	p.y = WorldGen.height(p.x, p.z)
	var player := get_tree().get_first_node_in_group("player") as Node3D
	var physics_close := player != null and player.global_position.distance_squared_to(global_position) < PLAYER_SOLID_RANGE * PLAYER_SOLID_RANGE
	if physics_close:
		global_position.y = p.y
		velocity = step_velocity
		move_and_slide()
		# Ground height is generated by WorldGen; retain its exact surface after
		# resolving horizontal contacts with buildings and the player.
		global_position.y = WorldGen.height(global_position.x, global_position.z)
		_velocity.x = velocity.x
		_velocity.z = velocity.z
	else:
		global_position = p

	var planar := Vector2(_velocity.x, _velocity.z).length()
	if _busy <= 0.0:
		if planar > 0.5:
			_face(_velocity)
		elif not engaging:
			_face(squad.facing if squad else Vector3.FORWARD)
	if _model.visible:
		_animator.update(delta, planar)
		_animator.set_blocking(_guard > 0.0)
		if planar > 0.5:
			_step_distance += planar * delta
			var gait := clampf((planar - WALK) / (RUN - WALK), 0.0, 1.0)
			var authored_stride := lerpf(WALK / 1.5, RUN / (2.0 * 24.0 / 22.0), gait)
			var gait_speed := lerpf(WALK, RUN, gait)
			var stride := authored_stride * planar / gait_speed
			if _step_distance >= stride:
				_step_distance = fmod(_step_distance, stride)
				var listener_near := Audio.listener == null or Audio.listener.global_position.distance_to(global_position) < 35.0
				if listener_near:
					Audio.sfx("step_" + WorldGen.footstep_surface(global_position.x, global_position.z), global_position, -13.0)
		else:
			_step_distance = 0.0


func _pick_target() -> void:
	var order := squad.order if squad else Squad.Order.HOLD
	var reach := INF if order == Squad.Order.CHARGE else ENGAGE_RANGE
	var best: Node3D = null
	var best_d := reach
	for enemy in get_tree().get_nodes_in_group("team%d" % (1 - team)):
		if enemy.get("dead"):
			continue
		var d := global_position.distance_to((enemy as Node3D).global_position)
		if d < best_d:
			best_d = d
			best = enemy
	combat_target = best


func _separation() -> Vector3:
	var push := Vector3.ZERO
	if squad == null:
		return push
	for other in squad.soldiers:
		if other == self:
			continue
		var d := global_position - other.global_position
		d.y = 0.0
		var len := d.length()
		if len < 1.2 and len > 0.001:
			push += d / len * (1.2 - len)
	return push


func _update_player_collision() -> void:
	var player := get_tree().get_first_node_in_group("player") as Node3D
	_actor_shape.set_deferred("disabled", player == null or player.global_position.distance_squared_to(global_position) > PLAYER_SOLID_RANGE * PLAYER_SOLID_RANGE)


func _attack() -> void:
	_attack_cooldown = randf_range(1.1, 1.5)
	_busy = 0.5
	_animator.play_upper(["1H_Melee_Attack_Chop", "1H_Melee_Attack_Slice_Diagonal", "1H_Melee_Attack_Slice_Horizontal"][randi() % 3], 1.4)
	var victim := combat_target
	get_tree().create_timer(0.3).timeout.connect(func() -> void:
		if not dead and is_instance_valid(victim) and not victim.get("dead") \
				and global_position.distance_to(victim.global_position) < ATTACK_RANGE + 0.5:
			victim.take_damage(damage, self)
			Audio.sfx("clash" if randf() < 0.5 else "hit", global_position, -6.0))


func take_damage(amount: int, from: Node = null, knockback := Vector3.ZERO) -> void:
	if dead:
		return
	var from_front := true
	if from is Node3D:
		var to := (from as Node3D).global_position - global_position
		from_front = global_transform.basis.z.dot(Vector3(to.x, 0, to.z).normalized()) > 0.3
	if from_front and randf() < block_chance and _busy <= 0.0:
		_guard = 0.6
		_impulse = knockback * 0.4
		_animator.play_upper("Block_Hit", 1.5)
		return
	health -= amount
	_impulse = knockback
	if health <= 0:
		_die()
	else:
		_busy = 0.35
		if knockback.length() > 4.0:
			_animator.play_full("Hit_B", 1.3)
		else:
			_animator.play_upper("Hit_A", 1.5)


func _die() -> void:
	dead = true
	remove_from_group("team%d" % team)
	remove_from_group("combatant")
	_animator.play_terminal("Death_A" if randf() < 0.5 else "Death_B")
	died.emit(self)
	var tween := create_tween()
	tween.tween_interval(5.0)
	tween.tween_property(self, "scale", Vector3(1, 0.01, 1), 0.6)
	tween.tween_callback(queue_free)


func _face(dir: Vector3) -> void:
	if Vector2(dir.x, dir.z).length() > 0.01:
		rotation.y = lerp_angle(rotation.y, atan2(dir.x, dir.z), 0.25)




func _update_lod() -> void:
	var cam := get_viewport().get_camera_3d()
	if cam == null:
		return
	var far := cam.global_position.distance_to(global_position) > LOD_DISTANCE
	if far == _sprite.visible:
		return
	_sprite.visible = far
	_model.visible = not far
	_animator.set_active(not far)
