"""Food and drink: raw produce, meat and fish, cooked dishes, baking, preserved food, drinks, regional dishes."""
from core import add, craft

F = "food"
HEARTH = ["hearth", "campfire"]


def food(i, name, price, nutr, fam, tint, desc, level=1, rarity=0, spoil=None, stack=20, weight=0.3, heal=None, buff=None,
         region=None, kind="food", raw=None, cooked=None, preserved=None, drink=None, **kw):
    ex = dict(kw)
    kind = ex.pop("type", kind)
    if buff:
        ex["buff_name"], ex["buff_stat"], ex["buff_value"], ex["buff_hours"] = buff
    if spoil:
        ex["spoil_hours"] = spoil
        ex["spoils_into"] = "spoiled_food"
    return add(i, name, "food", F, price=price, stack=stack, weight=weight, rarity=rarity, level=level, desc=desc, tint=tint,
               glyph="fam:" + fam, nutrition=nutr, heal=heal, region=region, type=kind, raw=raw, cooked=cooked, preserved=preserved,
               drink=drink, **ex)


def cook(out, level, inputs, count=1, stations=HEARTH, skill="cooking", xp=None, time=None, rid=None):
    return craft(out, skill, stations, level, inputs, count=count, xp=xp, time=time, rid=rid)


def build():
    add("spoiled_food", "Spoiled Food", "food", F, price=0, stack=30, weight=0.3, rarity=0, level=1,
        desc="Green, slick and smelling of the midden. Eating it makes you ill; hogs don't mind.", tint="#7a8a4a", glyph="fam:meat", nutrition=2, type="junk", spoiled=True)

    # ---- raw produce ---------------------------------------------------------------------------
    R = lambda i, n, p, nu, fam, tint, desc, sp=240, lv=1, **kw: food(i, n, p, nu, fam, tint, desc, level=lv, spoil=sp, type="produce", **kw)
    R("carrot", "Carrot", 2, 10, "veg", "#f08a2c", "Sweet orange root.")
    R("onion", "Onion", 2, 6, "veg", "#e8d0a0", "Pungent. Half of cooking begins with one.", 400)
    R("leek", "Leek", 2, 8, "veg", "#b8d890", "Mild and green-white.", 200)
    R("garlic_bulb", "Garlic", 2, 4, "veg", "#f4efe0", "Keeps wolves and company away.", 500)
    R("peas", "Pea Pods", 2, 9, "veg", "#8ac860", "Sweet green peas in the pod.", 120)
    R("broad_beans", "Broad Beans", 2, 11, "veg", "#9cbc70", "Filling field beans.", 200)
    R("beetroot", "Beetroot", 2, 10, "veg", "#8a2a4a", "Stains everything it touches.", 300)
    R("radish", "Radish", 1, 6, "veg", "#e04a6a", "Peppery little root.", 150)
    R("parsnip", "Parsnip", 2, 11, "veg", "#eed8a8", "Sweet after the first frost.", 300)
    R("pumpkin", "Pumpkin", 4, 22, "fruit", "#f08a2c", "Heavy gourd. Makes a great deal of soup.", 400, 3)
    R("pear", "Pear", 2, 11, "fruit", "#c8d86a", "Soft and sweet.", 120)
    R("plum", "Plum", 2, 9, "fruit", "#6a3a7a", "Dark and juicy.", 100)
    R("cherries", "Cherries", 3, 8, "fruit", "#c42a3a", "A handful of red cherries.", 80)
    R("grapes", "Grapes", 3, 9, "fruit", "#7a4a9a", "Sweet grapes from the south slopes.", 100, 3)
    R("hazelnuts", "Hazelnuts", 2, 12, "grain", "#b88a5a", "A pocketful of nuts.", 900)
    R("walnuts", "Walnuts", 3, 14, "grain", "#a07848", "Rich, oily nuts.", 900, 4)
    R("blackberries", "Blackberries", 2, 6, "fruit", "#3a2848", "Hedge berries, stain-fingered sweet.", 70)
    R("elderberries", "Elderberries", 2, 5, "fruit", "#3a2a58", "Tart berries; cook before eating.", 80, 2)
    R("honey_jar", "Jar of Honey", 7, 16, "honey", "#f0b830", "Dark wildflower honey.", None, 2, stack=10)
    R("milk", "Pail of Milk", 2, 10, "drink", "#f8f4ec", "Fresh and still warm.", 36, stack=10, drink=True)
    R("cream", "Cream", 4, 14, "drink", "#faf3e0", "Thick yellow cream.", 48, 3, stack=10)
    R("butter", "Butter", 5, 16, "cheese", "#f8e070", "Churned and salted.", 240, 3, stack=10)
    R("lard", "Lard", 3, 12, "cheese", "#f4f0e0", "Rendered pork fat.", 400, 2)
    R("goat_cheese", "Goat Cheese", 6, 24, "cheese", "#f4f0e4", "Tangy and crumbly.", 300, 3)
    R("aged_cheese", "Aged Mountain Cheese", 14, 34, "cheese", "#e8c468", "Hard, sharp, made to last a winter.", 900, 8, rarity=1)
    R("oats", "Oats", 2, 10, "grain", "#e0d4a0", "For porridge and horses.", None)
    R("rye", "Rye", 2, 9, "grain", "#b8a880", "Dark hardy grain for dark bread.", None)
    R("rice", "Rice", 3, 12, "grain", "#f4f0e0", "Imported from the south and east.", None, 10, stack=40)
    R("pepper", "Black Pepper", 14, 0, "powder", "#3a3a3a", "Hot peppercorns from the far south.", None, 14, rarity=1, stack=40)
    R("cinnamon", "Cinnamon", 16, 0, "powder", "#b06a34", "Sweet bark. The rich buy it by the stick.", None, 16, rarity=1, stack=40)
    R("saffron", "Saffron", 40, 0, "powder", "#e8842a", "Worth more than its weight in silver.", None, 24, rarity=2, stack=40)
    R("ginger", "Ginger Root", 10, 2, "veg", "#d8b068", "Fiery, warming root.", 500, 12, stack=40)
    R("cloves", "Cloves", 18, 0, "powder", "#6a3a24", "Dried spice buds.", None, 16, rarity=1, stack=40)
    R("tea_green", "Green Tea Leaves", 6, 0, "herb", "#88b860", "Shenlu tea, lightly steamed.", None, 10, stack=40)
    R("tea_black", "Black Tea Leaves", 6, 0, "herb", "#5a3a28", "Dark, malty tea.", None, 10, stack=40)
    R("cooking_salt_pork", "Salted Pork", 6, 26, "meat", "#d8a090", "Packed in brine. Keeps for seasons.", 1500, 3, preserved=True)

    # ---- raw meat & fish ---------------------------------------------------------------------------
    M = lambda i, n, p, nu, fam, tint, desc, sp=48, lv=1, **kw: food(i, n, p, nu, fam, tint, desc, level=lv, spoil=sp, type="raw_meat", raw=True, **kw)
    M("mutton", "Mutton", 5, 22, "meat", "#d08a84", "A joint of mutton.", 48)
    M("beef", "Beef", 6, 26, "meat", "#c2606a", "A cut of beef.", 48, 3)
    M("chicken", "Chicken", 4, 16, "meat", "#f0c8b0", "Plucked and dressed.", 36)
    M("goose", "Goose", 6, 24, "meat", "#f0d0b8", "A plump goose.", 40, 4)
    M("duck", "Duck", 5, 20, "meat", "#eac8a8", "Dressed wildfowl.", 40, 3)
    M("bear_meat", "Bear Meat", 8, 30, "meat", "#a84a4a", "Dark, rich and gamy. Cook it well.", 40, 12, rarity=1)
    M("troll_meat", "Troll Flesh", 12, 34, "meat", "#6f8a66", "It twitches when you aren't looking. Must be cooked thoroughly.", 30, 28, rarity=2, stack=10)
    M("wyvern_meat", "Wyvern Meat", 40, 50, "meat", "#d86a4a", "Lean, dense and faintly sweet.", 40, 44, rarity=3, stack=10)
    M("eel", "River Eel", 4, 14, "fish", "#5a6a5a", "Slippery and rich.", 30, 4)
    M("carp", "Carp", 3, 14, "fish", "#b8a060", "Muddy but filling.", 30)
    M("salmon", "Salmon", 6, 22, "fish", "#f08a6a", "Silver and pink, from the upper Ashrun.", 30, 8)
    M("crayfish", "Crayfish", 4, 10, "fish", "#c8483a", "From the Ashrun's gravel beds.", 24, 3)
    M("frog_legs", "Frog Legs", 3, 8, "meat", "#b8c890", "The marsh people swear by them.", 24, 2)
    M("raw_sausage", "Sausage Links", 5, 18, "meat", "#d87a6a", "Pork, herbs and salt in a casing.", 60, 3)

    # ---- basic recipes: milling, dairy ----------------------------------------------------------------
    cook("flour", 1, [("wheat", 3)], count=2, stations=["hearth", "oven"], skill="baking", xp=4, rid="flour_from_wheat")
    cook("butter", 2, [("milk", 2)], stations=HEARTH, xp=6)
    cook("cream", 2, [("milk", 2)], xp=4, stations=HEARTH)
    cook("cheese", 3, [("milk", 2), ("salt", 1)], xp=8, rid="cheese_from_milk")
    cook("goat_cheese", 3, [("milk", 3), ("thyme", 1)], count=2, xp=10)
    cook("lard", 2, [("pork", 1)], xp=4)
    cook("aged_cheese", 6, [("cheese", 2), ("salt", 1)], xp=16, time=3.0)
    cook("raw_sausage", 3, [("pork", 2), ("salt", 1), ("sage", 1)], count=3, xp=10)

    # ---- cooked dishes ------------------------------------------------------------------------------------
    D = lambda i, n, p, nu, fam, tint, desc, lv, buff=None, heal=None, sp=96, rarity=0, **kw: food(
        i, n, p, nu, fam, tint, desc, level=lv, rarity=rarity, spoil=sp, heal=heal, buff=buff, stack=kw.pop("stack", 5), cooked=True, type="dish", **kw)
    D("porridge", "Bowl of Porridge", None, 26, "soup", "#e8dcc0", "Oats, water and salt. Sticks to the ribs.", 1, sp=72)
    D("honey_porridge", "Honeyed Porridge", None, 34, "soup", "#f0d890", "Sweet, warming and honest.", 2, ("Morning warmth", "stamina_regen", 0.15, 3), sp=72)
    D("cabbage_soup", "Cabbage Soup", None, 28, "soup", "#b8d890", "Thin, hot and cheap.", 1, sp=72)
    D("onion_soup", "Onion Soup", None, 32, "soup", "#e8c878", "Slow-cooked and sweet. Toasted crust on top.", 3, ("Hearty broth", "max_health", 8, 3), sp=72)
    D("pea_soup", "Pea Soup", None, 34, "soup", "#9cc870", "Thick as porridge.", 2, sp=72)
    D("pottage", "Vegetable Pottage", None, 36, "soup", "#b0a060", "Whatever the garden gave, boiled down.", 2, sp=72)
    D("fish_stew", "Fish Stew", None, 42, "soup", "#e0b888", "Chunks of river fish in a peppery broth.", 4, ("Riverwise", "stamina_regen", 0.25, 3), heal=6)
    D("mutton_stew", "Mutton Stew", None, 50, "soup", "#b87a4a", "Dark and rich, with barley.", 4, ("Stout belly", "max_health", 14, 4), heal=8)
    D("beef_stew", "Beef Stew", None, 54, "soup", "#a8603a", "Slow-simmered and deeply savoury.", 5, ("Stout belly", "max_health", 18, 4), heal=10)
    D("hunters_pot", "Hunter's Pot", None, 58, "soup", "#9a6a3a", "Venison, mushrooms and juniper berries.", 6, ("Sure-footed", "speed", 0.05, 4), heal=8)
    D("turnip_mash", "Buttered Turnip Mash", None, 28, "soup", "#f0e8c8", "Boiled, pounded and buttered.", 2, sp=72)
    D("glazed_carrots", "Honey-Glazed Carrots", None, 26, "veg", "#f09a3c", "Sweet side dish.", 3, sp=96)
    D("boiled_eggs", "Boiled Eggs", None, 18, "egg", "#f4ecd8", "Three eggs and a pinch of salt.", 1, sp=120)
    D("omelette", "Herb Omelette", None, 30, "egg", "#f0d860", "Eggs, butter and thyme.", 3, ("Bright start", "stamina_regen", 0.2, 3))
    D("fried_fish", "Fried Fish", None, 30, "fish", "#d8a868", "Crisp and hot from the pan.", 2, sp=72)
    D("eel_skewer", "Roasted Eel Skewer", None, 28, "fish", "#7a5a3a", "Charred eel on a stick.", 4, ("Quick on the feet", "speed", 0.04, 3), sp=72)
    D("salmon_fillet", "Baked Salmon", None, 44, "fish", "#f09a78", "Rich pink fillet with thyme.", 8, ("Riverwise", "stamina_regen", 0.35, 4), heal=10)
    D("crayfish_boil", "Crayfish Boil", None, 26, "fish", "#d8583a", "Messy and delicious.", 3, sp=48)
    D("roast_chicken", "Roast Chicken", None, 46, "meat", "#d8a060", "Golden skin, juicy thigh.", 3, ("Good cheer", "stamina_regen", 0.2, 3), heal=6)
    D("roast_duck", "Roast Duck", None, 50, "meat", "#c8884a", "Crisp skin over dark meat.", 5, ("Good cheer", "stamina_regen", 0.3, 3), heal=8)
    D("roast_goose", "Roast Goose", None, 68, "meat", "#b87838", "Festival fare, stuffed with apples.", 8, ("Feast day", "max_health", 26, 5), heal=14, rarity=1)
    D("roast_pork", "Roast Pork", None, 52, "meat", "#c8804a", "Crackling and apple sauce.", 4, ("Hearty", "damage", 1, 4), heal=8)
    D("roast_boar", "Roast Boar", None, 62, "meat", "#a8603a", "Wild boar with juniper.", 7, ("Hearty", "damage", 2, 4), heal=10)
    D("bear_steak", "Bear Steak", None, 66, "meat", "#8a4a32", "Thick, dark and gamy; strength in every bite.", 13, ("Bear's strength", "damage", 3, 4), heal=14, rarity=1)
    D("troll_steak", "Troll Steak", None, 70, "meat", "#6f8a66", "Charred black outside. Wounds close faster for hours.", 29, ("Troll's vigour", "max_health", 40, 5), heal=28, rarity=2)
    D("wyvern_steak", "Wyvern Steak", None, 92, "meat", "#d86a4a", "Seared pink. A dragon-kin's meal; you feel light and fierce.", 45, ("Wyrm's fire", "damage", 6, 6), heal=40, rarity=3)
    D("grilled_venison", "Grilled Venison Steak", None, 48, "meat", "#9a5a3a", "Simple, bloody-rare and perfect.", 4, ("Hearty", "damage", 1, 3), heal=6)
    D("sausages", "Fried Sausages", None, 40, "meat", "#c8704a", "Spitting in the pan.", 4, sp=72)
    D("bacon", "Crisp Bacon", None, 30, "meat", "#b85a3a", "Smoky strips.", 3, sp=72)
    D("frog_legs_fried", "Fried Frog Legs", None, 18, "meat", "#d8b068", "Tastes like chicken, they say.", 3, sp=48)
    D("wolf_jerky_stew", "Wolf-Meat Stew", None, 36, "soup", "#8a5a3a", "Not delicious, but it fills the stomach.", 2, sp=72)
    D("stuffed_pumpkin", "Stuffed Pumpkin", None, 60, "veg", "#d87a2c", "Baked with sausage and chestnuts.", 6, ("Harvest strength", "max_health", 22, 5), heal=10, rarity=1)
    D("farmers_platter", "Farmer's Platter", None, 58, "pie", "#e0c070", "Cheese, bread, onions, cold meat.", 4, ("Well fed", "stamina_regen", 0.2, 4), sp=96)
    D("cheese_platter", "Cheese Platter", None, 38, "cheese", "#f0d488", "Three cheeses, pickled onions.", 4, sp=120)

    cook("porridge", 1, [("oats", 2), ("salt", 1)], xp=4)
    cook("honey_porridge", 2, [("oats", 2), ("honey_jar", 1)], xp=8)
    cook("cabbage_soup", 1, [("cabbage", 2), ("onion", 1)], xp=6)
    cook("onion_soup", 3, [("onion", 3), ("butter", 1), ("bread", 1)], xp=12)
    cook("pea_soup", 2, [("peas", 3), ("onion", 1)], xp=8)
    cook("pottage", 2, [("carrot", 1), ("turnip", 1), ("leek", 1), ("broad_beans", 1)], xp=8)
    cook("fish_stew", 4, [("perch|trout|pike|carp", 2), ("leek", 1), ("thyme", 1)], xp=16)
    cook("mutton_stew", 4, [("mutton", 2), ("carrot", 1), ("barley", 1)], xp=18)
    cook("beef_stew", 5, [("beef", 2), ("carrot", 1), ("onion", 1), ("thyme", 1)], xp=22)
    cook("hunters_pot", 6, [("venison", 2), ("mushroom", 2), ("onion", 1), ("sage", 1)], xp=26)
    cook("turnip_mash", 2, [("turnip", 2), ("butter", 1)], xp=8)
    cook("glazed_carrots", 3, [("carrot", 3), ("honey_jar", 1), ("butter", 1)], xp=10)
    cook("boiled_eggs", 1, [("egg", 3)], xp=3)
    cook("omelette", 3, [("egg", 3), ("butter", 1), ("thyme", 1)], xp=11)
    cook("fried_fish", 2, [("perch|trout|pike|carp", 1), ("lard", 1)], xp=8)
    cook("eel_skewer", 4, [("eel", 1), ("salt", 1)], xp=12)
    cook("salmon_fillet", 8, [("salmon", 1), ("butter", 1), ("thyme", 1)], xp=30)
    cook("crayfish_boil", 3, [("crayfish", 3), ("salt", 1), ("parsley", 1)], xp=10)
    cook("roast_chicken", 3, [("chicken", 1), ("thyme", 1), ("firewood", 1)], xp=14)
    cook("roast_duck", 5, [("duck", 1), ("apple", 1), ("firewood", 1)], xp=22)
    cook("roast_goose", 8, [("goose", 1), ("apple", 2), ("sage", 1), ("firewood", 1)], xp=36, time=3.0)
    cook("roast_pork", 4, [("pork", 2), ("apple", 1), ("firewood", 1)], xp=18)
    cook("roast_boar", 7, [("pork", 3), ("boar_tusk", 1), ("sage", 1), ("firewood", 1)], xp=30) if False else cook("roast_boar", 7, [("pork", 3), ("sage", 1), ("firewood", 1)], xp=30)
    cook("bear_steak", 9, [("bear_meat", 2), ("salt", 1), ("firewood", 1)], xp=40)
    cook("troll_steak", 10, [("troll_meat", 2), ("garlic_bulb", 2), ("salt", 1), ("firewood", 2)], xp=70, time=4.0)
    cook("wyvern_steak", 10, [("wyvern_meat", 1), ("pepper", 1), ("butter", 1), ("firewood", 2)], xp=90, time=4.0)
    cook("grilled_venison", 4, [("venison", 2), ("salt", 1)], xp=16)
    cook("sausages", 4, [("raw_sausage", 2), ("lard", 1)], xp=12)
    cook("bacon", 3, [("pork", 1), ("salt", 1)], count=2, xp=10)
    cook("frog_legs_fried", 3, [("frog_legs", 3), ("lard", 1)], xp=8)
    cook("wolf_jerky_stew", 2, [("wolf_meat", 2), ("onion", 1)], xp=8)
    cook("stuffed_pumpkin", 6, [("pumpkin", 1), ("raw_sausage", 1), ("walnuts", 1), ("onion", 1)], xp=28)
    cook("farmers_platter", 4, [("cheese", 1), ("bread", 1), ("onion", 1), ("bacon", 1)], xp=16, stations=HEARTH)
    cook("cheese_platter", 4, [("cheese", 1), ("goat_cheese", 1), ("aged_cheese", 1), ("onion", 1)], xp=14)

    # ---- preserved --------------------------------------------------------------------------------------------
    Pv = lambda i, n, p, nu, fam, tint, desc, lv, sp=1500, buff=None, **kw: food(i, n, p, nu, fam, tint, desc, level=lv, spoil=sp, buff=buff, stack=kw.pop("stack", 20), preserved=True, type="preserved", **kw)
    Pv("jerky", "Dried Jerky", None, 28, "meat", "#8a5a3a", "Salted, smoked and dried. Travels anywhere.", 3, 2000, weight=0.15)
    Pv("smoked_fish", "Smoked Fish", None, 26, "fish", "#b88a4a", "Hung over the hearth until firm.", 3, 1200, weight=0.2)
    Pv("smoked_ham", "Smoked Ham", None, 48, "meat", "#c86a54", "A whole ham, dark with smoke.", 5, 2400, stack=5, weight=0.6)
    Pv("salted_fish", "Salted Fish", None, 22, "fish", "#d0d0c0", "Brined and dried. Quite terrible, quite lasting.", 2, 2000)
    Pv("pickled_cabbage", "Pickled Cabbage", None, 18, "veg", "#c0d890", "Sour crunch from the barrel.", 2, 2000)
    Pv("pickled_onions", "Pickled Onions", None, 14, "veg", "#eed8c0", "A jar of sharp little onions.", 2, 2000)
    Pv("dried_fruit", "Dried Fruit", None, 24, "fruit", "#a8683a", "Chewy raisins, plums and apple rings.", 3, 2400, buff=("Sweet tooth", "stamina_regen", 0.1, 2))
    Pv("hardtack", "Hardtack", None, 20, "bread", "#c8b48a", "Bone-dry biscuit. Soak it or break a tooth.", 1, 4000)
    Pv("trail_rations", "Trail Rations", None, 44, "sack_food", "#b09060", "Jerky, hardtack, nuts and dried fruit in a wrapped cloth.", 4, 2400, buff=("Travel-fit", "speed", 0.03, 4), stack=10)
    Pv("honeycomb_bar", "Honey & Nut Bar", None, 30, "honey", "#e8b84a", "Honey, oats and hazelnuts, pressed.", 4, 3000, buff=("Quick energy", "stamina_regen", 0.3, 2))

    cook("jerky", 3, [("venison|mutton|beef|wolf_meat", 2), ("salt", 1)], count=2, xp=10, time=2.4)
    cook("smoked_fish", 3, [("perch|trout|pike|carp|eel|salmon", 2), ("salt", 1), ("firewood", 1)], count=2, xp=10)
    cook("smoked_ham", 5, [("pork", 3), ("salt", 2), ("firewood", 2)], xp=22, time=3.0)
    cook("salted_fish", 2, [("perch|trout|pike|carp", 2), ("salt", 2)], count=2, xp=6)
    cook("pickled_cabbage", 2, [("cabbage", 2), ("salt", 1), ("pottery_jug", 1)], count=2, xp=8)
    cook("pickled_onions", 2, [("onion", 3), ("salt", 1), ("pottery_jug", 1)], count=2, xp=8)
    cook("dried_fruit", 3, [("apple|pear|plum|grapes", 4)], count=2, xp=8)
    cook("hardtack", 1, [("flour", 2), ("salt", 1)], count=4, stations=["hearth", "oven"], skill="baking", xp=5)
    cook("trail_rations", 4, [("jerky", 1), ("hardtack", 1), ("hazelnuts", 1), ("dried_fruit", 1)], xp=14)
    cook("honeycomb_bar", 4, [("oats", 2), ("honey_jar", 1), ("hazelnuts", 1)], count=2, xp=12)

    # ---- baking -------------------------------------------------------------------------------------------------
    OV = ["hearth", "oven"]
    B = lambda i, n, p, nu, fam, tint, desc, lv, buff=None, heal=None, sp=120, rarity=0, **kw: food(
        i, n, p, nu, fam, tint, desc, level=lv, rarity=rarity, spoil=sp, heal=heal, buff=buff, stack=kw.pop("stack", 8), cooked=True, type="baked", **kw)
    B("rye_loaf", "Rye Loaf", None, 30, "bread", "#7a5a3a", "Dense, dark, sour and lasting.", 2, sp=200)
    B("nut_bread", "Nut Bread", None, 38, "bread", "#a07848", "Walnuts folded through the dough.", 4, ("Steady hands", "stamina_regen", 0.12, 3), sp=200)
    B("honey_loaf", "Honey Loaf", None, 36, "bread", "#d8a858", "Sweet, soft and golden.", 3, sp=160)
    B("bread_rolls", "Bread Rolls", None, 22, "bread", "#d8a868", "A basket of small soft rolls.", 1, sp=96)
    B("flatbread", "Flatbread", None, 20, "bread", "#e0c080", "Quick, unleavened, hot from the stone.", 1, sp=96)
    B("oatcakes", "Oatcakes", None, 18, "pie", "#d4b880", "Dry little cakes that travel well.", 1, sp=300)
    B("cheese_bread", "Cheese Bread", None, 40, "bread", "#e8c878", "Melted cheese baked into the crust.", 4, sp=120)
    B("meat_pie", "Meat Pie", None, 52, "pie", "#b8783a", "Gravy-rich mutton and onion under a flaky lid.", 4, ("Hearty", "damage", 1, 4), heal=6, sp=96)
    B("mushroom_pie", "Mushroom Pie", None, 44, "pie", "#9a7a4a", "Wood mushrooms, thyme and cream.", 4, ("Warmed through", "max_health", 14, 4), heal=8, sp=96)
    B("eel_pie", "Eel Pie", None, 40, "pie", "#9a7a4a", "A river-town classic.", 5, sp=96)
    B("apple_pie", "Apple Pie", None, 46, "pie", "#d8a050", "Spiced apples in butter pastry.", 4, ("Sugar rush", "speed", 0.05, 3), sp=96)
    B("pear_tart", "Pear Tart", None, 44, "pie", "#d8c070", "Glazed pears on almond cream.", 5, ("Sugar rush", "speed", 0.05, 3), sp=96)
    B("fruit_tart", "Fruit Tart", None, 42, "pie", "#c8587a", "Berries and plums under a sugared crust.", 5, sp=72)
    B("pumpkin_pie", "Pumpkin Pie", None, 50, "pie", "#e09030", "Autumn's own pie, with cinnamon.", 6, ("Harvest strength", "max_health", 16, 4), sp=96)
    B("pasty", "Miner's Pasty", None, 46, "pie", "#c8884a", "Meat and turnip in a crimped crust. Holds for a shift underground.", 3, ("Underground steady", "stamina_regen", 0.18, 4), sp=120)
    B("sweet_bun", "Sweet Bun", None, 24, "pie", "#d8a060", "Sticky sugar glaze.", 2, sp=72)
    B("gingerbread", "Gingerbread", None, 32, "pie", "#9a5a2a", "Festival spice cake.", 6, sp=300)
    B("shortbread", "Shortbread", None, 28, "pie", "#e8cc90", "Butter, flour, sugar, and nothing else.", 4, sp=400)
    B("honey_cake", "Honey Cake", None, 42, "pie", "#e0a840", "Layered with cream.", 6, ("Festival spirits", "stamina_regen", 0.25, 3), sp=120)
    B("royal_cake", "Kingsreach Spice Cake", None, 64, "pie", "#d8883a", "Saffron and candied fruit. Fit for a banquet.", 14, ("Banquet glow", "max_health", 30, 5), heal=12, rarity=2, sp=200)
    B("dumplings", "Stuffed Dumplings", None, 36, "pie", "#f0e0c0", "Steamed pockets of meat and cabbage.", 5, sp=96)

    cook("rye_loaf", 2, [("rye", 2), ("salt", 1)], xp=8, stations=OV, skill="baking")
    cook("nut_bread", 4, [("flour", 2), ("walnuts", 1), ("butter", 1)], xp=14, stations=OV, skill="baking")
    cook("honey_loaf", 3, [("flour", 2), ("honey_jar", 1)], xp=10, stations=OV, skill="baking")
    cook("bread_rolls", 1, [("flour", 2)], count=4, xp=6, stations=OV, skill="baking")
    cook("flatbread", 1, [("flour", 1), ("salt", 1)], count=2, xp=4, stations=OV, skill="baking")
    cook("oatcakes", 1, [("oats", 2), ("butter", 1)], count=4, xp=5, stations=OV, skill="baking")
    cook("cheese_bread", 4, [("bread", 1), ("cheese", 1)], xp=12, stations=OV, skill="baking")
    cook("meat_pie", 4, [("flour", 1), ("mutton|beef|pork", 1), ("onion", 1), ("butter", 1)], xp=18, stations=OV, skill="baking")
    cook("mushroom_pie", 4, [("flour", 1), ("mushroom", 3), ("cream", 1), ("thyme", 1)], xp=18, stations=OV, skill="baking")
    cook("eel_pie", 5, [("flour", 1), ("eel", 2), ("parsley", 1)], xp=20, stations=OV, skill="baking")
    cook("apple_pie", 4, [("flour", 1), ("apple", 3), ("butter", 1)], xp=16, stations=OV, skill="baking")
    cook("pear_tart", 5, [("flour", 1), ("pear", 3), ("butter", 1), ("honey_jar", 1)], xp=18, stations=OV, skill="baking")
    cook("fruit_tart", 5, [("flour", 1), ("plum|cherries|blackberries", 3), ("butter", 1)], xp=18, stations=OV, skill="baking")
    cook("pumpkin_pie", 6, [("flour", 1), ("pumpkin", 1), ("cinnamon", 1), ("butter", 1)], xp=24, stations=OV, skill="baking")
    cook("pasty", 3, [("flour", 1), ("mutton|beef|pork", 1), ("turnip", 1), ("butter", 1)], xp=14, stations=OV, skill="baking")
    cook("sweet_bun", 2, [("flour", 1), ("honey_jar", 1)], count=3, xp=8, stations=OV, skill="baking")
    cook("gingerbread", 6, [("flour", 2), ("ginger", 1), ("honey_jar", 1), ("cloves", 1)], count=3, xp=20, stations=OV, skill="baking")
    cook("shortbread", 4, [("flour", 2), ("butter", 2)], count=4, xp=12, stations=OV, skill="baking")
    cook("honey_cake", 6, [("flour", 2), ("honey_jar", 2), ("egg", 2), ("cream", 1)], xp=24, stations=OV, skill="baking")
    cook("royal_cake", 9, [("flour", 3), ("honey_jar", 2), ("egg", 3), ("saffron", 1), ("dried_fruit", 1)], xp=50, stations=OV, skill="baking", time=4.0)
    cook("dumplings", 5, [("flour", 1), ("pork|mutton", 1), ("cabbage", 1), ("ginger", 1)], count=2, xp=16, stations=HEARTH, skill="cooking")

    # ---- drinks ------------------------------------------------------------------------------------------------------
    BV = ["hearth", "brew_vat"]
    Dr = lambda i, n, p, nu, fam, tint, desc, lv, buff=None, heal=None, sp=None, rarity=0, **kw: food(
        i, n, p, nu, fam, tint, desc, level=lv, rarity=rarity, spoil=sp, heal=heal, buff=buff, stack=kw.pop("stack", 10), drink=True, type="drink", **kw)
    Dr("small_beer", "Small Beer", None, 6, "drink", "#d8a848", "Weak, safe to drink, sold by the jug.", 1, sp=400)
    Dr("strong_ale", "Strong Ale", None, 8, "drink", "#a86a28", "Dark and heady. Courage in a mug.", 3, ("Dutch courage", "damage", 2, 2), sp=600)
    Dr("stout", "Black Stout", None, 10, "drink", "#3a2a1a", "Roasted barley, thick as broth.", 5, ("Iron stomach", "max_health", 12, 3), sp=600)
    Dr("mead", "Honey Mead", None, 8, "drink", "#e8b840", "Sweet, strong and warming.", 4, ("Warm glow", "stamina_regen", 0.2, 3), sp=None)
    Dr("cider", "Apple Cider", None, 6, "drink", "#d8a84a", "Crisp and a little fizzy.", 2, sp=500)
    Dr("perry", "Pear Perry", None, 6, "drink", "#dcd07a", "Light and floral.", 3, sp=500)
    Dr("red_wine", "Red Wine", None, 8, "drink", "#7a1a2a", "Dry and deep.", 5, ("Smooth", "magic", 3, 3), sp=None, rarity=1)
    Dr("white_wine", "White Wine", None, 8, "drink", "#e8d888", "Clean and cold.", 5, ("Smooth", "stamina_regen", 0.15, 3), sp=None, rarity=1)
    Dr("berry_wine", "Blackberry Wine", None, 7, "drink", "#4a1a4a", "Sweet hedge-wine.", 3, sp=None)
    Dr("elder_cordial", "Elderflower Cordial", None, 6, "drink", "#f4f0c8", "Floral and cool, from the Veylwood style.", 3, ("Bright", "speed", 0.03, 2), sp=400, region="veylwood")
    Dr("apple_juice", "Apple Juice", None, 8, "drink", "#e0c060", "Pressed this morning.", 1, sp=48)
    Dr("goat_milk_warm", "Warm Spiced Milk", None, 12, "drink", "#f4e8c8", "Milk with honey and cinnamon.", 4, ("Sound sleep", "stamina_regen", 0.12, 3), sp=24)
    Dr("clean_water", "Flask of Clean Water", 1, 2, "drink", "#a8d8f0", "Cold from the well. Nothing better when thirsty.", 1, stack=10)
    Dr("firewater", "Firewater", None, 4, "drink", "#e8e0c8", "Distilled spirit. A warm fist to the chest.", 6, ("Liquid courage", "damage", 3, 1), sp=None, rarity=1)
    Dr("green_tea", "Green Tea", None, 4, "drink", "#9ac878", "Clear and grassy. Shenlu monks drink it before meditation.", 4, ("Clear mind", "qi_regen", 0.15, 3), region="shenlu")
    Dr("black_tea", "Black Tea", None, 4, "drink", "#7a4a2a", "Strong and malty.", 4, ("Alert", "stamina_regen", 0.2, 3))
    Dr("mint_tea", "Frostmint Tea", None, 4, "drink", "#a8ecd8", "Cool and sharp.", 5, ("Cool head", "magic", 4, 3))
    Dr("ginseng_tea", "Ginseng Tea", None, 14, "drink", "#d8b860", "Bitter, golden and deeply restorative.", 14, ("Root strength", "qi_regen", 0.4, 4), heal=10, rarity=1)
    Dr("rice_wine", "Rice Wine", None, 8, "drink", "#f0ecd8", "Milky and sweet, from Shenlu.", 8, ("Quiet calm", "qi_regen", 0.2, 3), region="shenlu", rarity=1)
    Dr("sake", "Seirune Sake", None, 8, "drink", "#f4f4ec", "Clear and clean.", 10, ("Steady blade", "damage", 2, 3), region="seirune", rarity=1)
    Dr("kumis", "Fermented Mare's Milk", None, 6, "drink", "#f0ece0", "Sour, fizzy and strangely wholesome. Ongur riders drink it by the skin.", 6, ("Saddle-hardy", "stamina_regen", 0.25, 3), region="ongur", rarity=1)
    Dr("dwarven_stout", "Hollowdeep Stout", None, 10, "drink", "#2a1a10", "Thick enough to stand a spoon in.", 12, ("Stone-hearted", "armour", 3, 3), region="hollowdeep", rarity=1)
    Dr("sun_wine", "Solmarch Sun Wine", None, 14, "drink", "#f0b848", "Golden, sweet and heady.", 20, ("Sun's blessing", "max_health", 25, 4), region="solmarch", rarity=2)

    cook("small_beer", 1, [("barley", 2), ("hops", 1), ("clean_water", 1)], count=3, stations=BV, skill="brewing", xp=6)
    cook("strong_ale", 3, [("barley", 3), ("hops", 2), ("honey_jar", 1)], count=3, stations=BV, skill="brewing", xp=12)
    cook("stout", 5, [("barley", 4), ("hops", 2), ("charcoal", 1)], count=3, stations=BV, skill="brewing", xp=18)
    cook("mead", 4, [("honey_jar", 3), ("clean_water", 2)], count=3, stations=BV, skill="brewing", xp=14, time=3.0)
    cook("cider", 2, [("apple", 6)], count=3, stations=BV, skill="brewing", xp=8)
    cook("perry", 3, [("pear", 6)], count=3, stations=BV, skill="brewing", xp=10)
    cook("red_wine", 5, [("grapes", 8), ("pottery_jug", 1)], count=3, stations=BV, skill="brewing", xp=20, time=3.0)
    cook("white_wine", 5, [("grapes", 8), ("pottery_jug", 1), ("sage", 1)], count=3, stations=BV, skill="brewing", xp=20, time=3.0)
    cook("berry_wine", 3, [("blackberries|elderberries", 6), ("honey_jar", 1), ("pottery_jug", 1)], count=3, stations=BV, skill="brewing", xp=12)
    cook("elder_cordial", 3, [("elderberries", 4), ("honey_jar", 1), ("clean_water", 1)], count=2, stations=HEARTH, xp=8)
    cook("apple_juice", 1, [("apple", 3)], count=2, stations=HEARTH, xp=3)
    cook("goat_milk_warm", 4, [("milk", 2), ("honey_jar", 1), ("cinnamon", 1)], stations=HEARTH, xp=8)
    cook("clean_water", 1, [("pottery_jug", 1)], count=1, stations=HEARTH, xp=1, rid="boil_water") if False else None
    cook("firewater", 6, [("barley", 4), ("red_wine|white_wine|berry_wine|cider", 1), ("charcoal", 1)], count=2, stations=BV, skill="brewing", xp=26, time=3.5)
    cook("green_tea", 4, [("tea_green", 1), ("clean_water", 1)], count=2, stations=HEARTH, xp=6)
    cook("black_tea", 4, [("tea_black", 1), ("clean_water", 1)], count=2, stations=HEARTH, xp=6)
    cook("mint_tea", 5, [("frostmint", 2), ("clean_water", 1), ("honey_jar", 1)], count=2, stations=HEARTH, xp=8)
    cook("ginseng_tea", 9, [("spirit_ginseng", 1), ("clean_water", 2), ("honey_jar", 1)], count=2, stations=HEARTH, xp=40)
    cook("rice_wine", 8, [("rice", 6), ("clean_water", 2), ("pottery_jug", 1)], count=3, stations=BV, skill="brewing", xp=26, time=3.0)
    cook("sake", 9, [("rice", 8), ("clean_water", 2), ("pottery_jug", 1)], count=3, stations=BV, skill="brewing", xp=32, time=3.5)
    cook("kumis", 6, [("milk", 6), ("goat_hide", 1)], count=3, stations=BV, skill="brewing", xp=16)
    cook("dwarven_stout", 9, [("barley", 6), ("hops", 3), ("mushroom", 2), ("charcoal", 2)], count=3, stations=BV, skill="brewing", xp=34, time=3.5)
    cook("sun_wine", 10, [("grapes", 10), ("honey_jar", 2), ("saffron", 1), ("pottery_jug", 2)], count=3, stations=BV, skill="brewing", xp=60, time=5.0)

    # ---- regional dishes ------------------------------------------------------------------------------------------------
    D("kingsreach_meat_pie", "Kingsreach Raised Pie", None, 60, "pie", "#c08a4a", "A tall hand-raised pie of venison and pork, the capital's pride.", 8, ("Crown's fare", "damage", 2, 5), heal=12, region="caldrenn", rarity=1)
    D("ashford_hotpot", "Ashford Hotpot", None, 48, "soup", "#a86a38", "Mutton and potato-less root hotpot baked under a lid.", 4, ("Village warmth", "max_health", 12, 4), heal=6, region="caldrenn")
    D("congee", "Ginger Congee", None, 34, "soup", "#f0ecd8", "Rice porridge with ginger and scallion. Shenlu's breakfast.", 10, ("Clear mind", "qi_regen", 0.2, 3), region="shenlu", sp=72)
    D("steamed_buns", "Steamed Pork Buns", None, 40, "bread", "#f4ecd8", "Soft white buns around savoury pork.", 10, ("Steady breath", "stamina_regen", 0.22, 3), region="shenlu")
    D("noodle_soup", "Hand-Pulled Noodle Soup", None, 50, "soup", "#e8c878", "Broth, noodles and mountain greens.", 12, ("Deep breath", "qi_regen", 0.3, 4), heal=8, region="shenlu", rarity=1)
    D("rice_balls", "Rice Balls", None, 26, "bread", "#f4f4ec", "Seirune travellers' food: salted rice around pickled plum.", 8, ("Travel-fit", "speed", 0.03, 3), region="seirune", sp=72)
    D("fish_skewers", "Seirune Grilled Skewers", None, 38, "fish", "#d8885a", "Fish and leek, brushed with a sweet glaze.", 10, ("Quick wrists", "speed", 0.04, 3), region="seirune")
    D("forest_loaf", "Veylwood Forest Loaf", None, 36, "bread", "#8a6a3a", "Acorn flour and elderberry, dense and sweet.", 10, ("Woodsy vigour", "max_health", 10, 4), region="veylwood")
    D("spiced_lamb", "Solmarch Spiced Lamb", None, 64, "meat", "#c86a3a", "Slow-roasted lamb with cinnamon and saffron.", 20, ("Sun-warmed", "damage", 3, 4), heal=12, region="solmarch", rarity=2)
    D("roast_mutton_steppe", "Steppe Roast Mutton", None, 56, "meat", "#b86a3a", "Whole-haunch mutton roasted over dung fire.", 10, ("Saddle-hardy", "stamina_regen", 0.3, 4), heal=8, region="ongur", rarity=1)
    D("dried_curd", "Dried Curd", None, 18, "cheese", "#f0ecd8", "Hard cheesy pebbles. A horse-rider's staple.", 6, ("Saddle-hardy", "stamina_regen", 0.12, 2), region="ongur", sp=3000, stack=20)
    D("cave_mushroom_stew", "Cave Mushroom Stew", None, 46, "soup", "#6a5a4a", "Earthy, thick and surprisingly filling.", 12, ("Stone-hearted", "armour", 2, 4), heal=8, region="hollowdeep", rarity=1)
    D("stone_bread", "Hollowdeep Stone Bread", None, 30, "bread", "#8a8070", "Rock-hard dwarf loaf. Soak in stout.", 12, ("Stone-hearted", "armour", 2, 4), region="hollowdeep", sp=2000)

    cook("kingsreach_meat_pie", 8, [("flour", 2), ("venison", 1), ("pork", 1), ("butter", 1), ("pepper", 1)], xp=40, stations=OV, skill="baking", time=3.0)
    cook("ashford_hotpot", 4, [("mutton", 2), ("carrot", 1), ("turnip", 1), ("onion", 1)], xp=18)
    cook("congee", 6, [("rice", 2), ("ginger", 1), ("onion", 1)], xp=16)
    cook("steamed_buns", 6, [("flour", 2), ("pork", 1), ("ginger", 1)], count=2, xp=20)
    cook("noodle_soup", 8, [("flour", 2), ("mutton|beef|pork", 1), ("leek", 1), ("ginger", 1)], xp=30)
    cook("rice_balls", 5, [("rice", 2), ("salt", 1), ("plum", 1)], count=2, xp=12)
    cook("fish_skewers", 6, [("perch|trout|pike|salmon", 2), ("leek", 1), ("honey_jar", 1)], xp=20)
    cook("forest_loaf", 6, [("hazelnuts", 2), ("flour", 1), ("elderberries", 2)], xp=18, stations=OV, skill="baking")
    cook("spiced_lamb", 10, [("mutton", 3), ("cinnamon", 1), ("saffron", 1), ("firewood", 2)], xp=60, time=4.0)
    cook("roast_mutton_steppe", 6, [("mutton", 3), ("salt", 1), ("firewood", 2)], xp=26)
    cook("dried_curd", 4, [("milk", 4), ("salt", 1)], count=3, xp=10)
    cook("cave_mushroom_stew", 7, [("mushroom", 4), ("redcap", 2), ("onion", 1), ("salt", 1)], xp=26)
    cook("stone_bread", 7, [("rye", 3), ("salt", 2)], count=2, stations=OV, skill="baking", xp=20)
