"""Glyph families: game-icons.net names (CC BY 3.0) used as item icons. An item's glyph is either a
literal glyph name or "fam:<family>" which cycles through the family's list so neighbours differ."""

FAM = {
    # materials
    "ore": ["ore", "rock", "stone-pile"],
    "ingot": ["gold-bar", "crystal-bars"],
    "log": ["log", "wood-pile", "wood-beam"],
    "plank": ["planks", "packed-planks", "wood-frame"],
    "hide": ["animal-hide"],
    "leather": ["leather-vest", "animal-hide", "belt"],
    "cloth": ["rolled-cloth", "clothes", "cloth-jar"],
    "thread": ["wool", "cloth-jar"],
    "herb": ["herbs-bundle", "oak-leaf", "maple-leaf", "curled-leaf", "flowers", "vine-leaf", "linden-leaf", "falling-leaf"],
    "flower": ["lotus-flower", "flower-star", "dandelion-flower", "fire-flower", "flowers", "twirly-flower"],
    "mushroom": ["mushroom", "mushrooms", "spotted-mushroom", "mushrooms-cluster"],
    "bone": ["broken-bone", "crossed-bones", "pelvis-bone"],
    "fang": ["fangs", "tooth", "saber-tooth", "bestial-fangs"],
    "claw": ["claws", "claw", "triple-claws"],
    "scale": ["scales", "dorsal-scales", "fish-scales"],
    "feather": ["feather", "two-feathers"],
    "crystal": ["crystal-shine", "crystal-cluster", "crystal-growth", "floating-crystal"],
    "gem": ["gems", "fire-gem", "crystal-shine"],
    "stone": ["stone-block", "stone-pile", "rock"],
    "brick": ["brick-pile", "clay-brick"],
    "eye": ["spider-eye", "beast-eye", "crystal-eye"],
    "blood": ["blood", "round-potion"],
    "skull": ["animal-skull", "horned-skull"],
    "core": ["crystal-ball", "orb-wand", "dragon-orb", "concentration-orb"],
    "oil": ["oil-can", "oil-drum", "round-potion"],
    "powder": ["powder-bag", "mortar"],
    "rope": ["rope-coil"],
    "nails": ["nails", "hammer-nails"],
    "barrel": ["barrel", "cellar-barrels"],
    "sack": ["swap-bag", "shoulder-bag", "duffel-bag"],
    # food
    "bread": ["bread", "bread-slice", "sliced-bread"],
    "cheese": ["cheese-wedge"],
    "meat": ["meat", "steak", "ham-shank"],
    "fish": ["fish-cooked", "fried-fish", "fish-smoking", "tropical-fish"],
    "fruit": ["shiny-apple", "grapes", "pumpkin", "carrot", "garlic", "corn"],
    "veg": ["carrot", "cabbage", "garlic", "pumpkin", "corn", "wheat"],
    "grain": ["wheat", "corn"],
    "soup": ["cooking-pot", "bowl-of-rice", "bubbling-bowl", "berries-bowl", "camp-cooking-pot"],
    "pie": ["pie-slice", "cake-slice", "cookie"],
    "drink": ["beer-stein", "beer-horn", "wine-glass", "wine-bottle", "brandy-bottle", "water-flask"],
    "bottle": ["wine-bottle", "sake-bottle", "brandy-bottle"],
    "egg": ["raw-egg", "fried-eggs", "egg-clutch"],
    "honey": ["honey-jar", "dripping-honey"],
    # alchemy
    "potion": ["health-potion", "magic-potion", "round-potion", "standing-potion", "potion-ball", "fizzing-flask", "bubbling-flask"],
    "pill": ["medicine-pills", "pill", "pill-drop"],
    "vial": ["vial", "poison-bottle", "bottle-vapors", "spiral-bottle"],
    "bomb": ["fire-bottle", "unstable-orb", "smoking-orb"],
    # weapons
    "dagger": ["plain-dagger", "broad-dagger", "diving-dagger", "sacrificial-dagger", "cloak-dagger", "flying-dagger", "thrown-daggers"],
    "sword": ["rusty-sword", "broadsword", "pointy-sword", "shining-sword", "piercing-sword", "winged-sword", "rune-sword"],
    "sabre": ["crossed-sabres", "sparkling-sabre", "katana", "dervish-swords", "curved-blade" if False else "katana", "sparkling-sabre", "energy-sword"],
    "greatsword": ["two-handed-sword", "ancient-sword", "shard-sword", "zeus-sword", "sword-in-stone", "fragmented-sword", "energy-sword"],
    "axe": ["stone-axe", "wood-axe", "sharp-axe", "war-axe", "fire-axe", "battle-axe", "magic-axe"],
    "battleaxe": ["battle-axe", "war-axe", "crossed-axes", "fire-axe", "magic-axe", "sharp-axe", "axe-swing"],
    "mace": ["wood-club", "bone-mace", "flanged-mace", "spiked-mace", "mace-head", "flail", "thor-hammer"],
    "warhammer": ["claw-hammer", "flat-hammer", "thor-hammer", "gear-hammer", "hammer-drop", "3d-hammer", "hammer-break"],
    "spear": ["stone-spear", "spears", "barbed-spear", "thrown-spear", "spear-hook", "sun-spear", "ice-spear"],
    "halberd": ["halberd", "sharp-halberd", "halberd", "sharp-halberd", "halberd", "halberd-shuriken", "halberd"],
    "shortbow": ["pocket-bow", "bow-arrow", "bow-string", "pocket-bow", "bow-arrow", "lightning-bow", "lightning-bow"],
    "longbow": ["bow-arrow", "bow-string", "bow-arrow", "lightning-bow", "bow-arrow", "lightning-bow", "lightning-bow"],
    "crossbow": ["crossbow"],
    "staff": ["wizard-staff", "crescent-staff", "skull-staff", "wizard-staff", "crescent-staff", "wizard-staff", "skull-staff"],
    "wand": ["orb-wand", "crystal-wand", "fairy-wand", "lunar-wand", "crystal-wand", "orb-wand", "crystal-wand"],
    "fist": ["brass-knuckles", "claws", "steel-claws", "mailed-fist", "thor-fist", "wolverine-claws", "flame-claws"],
    "buckler": ["round-shield" if False else "viking-shield", "tribal-shield", "viking-shield"],
    "shield": ["viking-shield", "cross-shield", "bordered-shield", "templar-shield", "crenulated-shield", "dragon-shield", "magic-shield"],
    "kite": ["roman-shield", "heart-shield", "edged-shield", "griffin-shield", "templar-shield", "dragon-shield", "energy-shield"],
    "tower": ["riot-shield", "bordered-shield", "crenulated-shield", "shield-opposition", "temporary-shield", "fire-shield", "energy-shield"],
    "arrow": ["plain-arrow", "barbed-arrow", "broadhead-arrow", "heavy-arrow", "flaming-arrow", "energy-arrow", "charged-arrow"],
    "bolt": ["plain-arrow", "fast-arrow", "heavy-arrow", "thorned-arrow", "charged-arrow"],
    # armour
    "helm": ["wooden-helmet", "light-helm", "brodie-helmet", "crested-helmet", "visored-helm", "heavy-helm", "overlord-helm"],
    "helm_leather": ["hood", "hood", "phrygian-cap", "hood", "warlock-hood", "hood", "warlock-hood"],
    "helm_cloth": ["hood", "turban", "pointy-hat", "magic-hat", "pilgrim-hat", "wizard-staff" if False else "magic-hat", "pointy-hat"],
    "chest_cloth": ["robe", "shirt", "robe", "robe", "robe", "robe", "robe"],
    "chest_leather": ["leather-vest", "leather-armor", "leather-vest", "armor-vest", "leather-armor", "layered-armor", "ninja-armor"],
    "chest_mail": ["mail-shirt", "scale-mail", "mail-shirt", "chest-armor", "layered-armor", "scale-mail", "heart-armor"],
    "chest_plate": ["breastplate", "chest-armor", "breastplate", "spiked-armor", "chest-armor", "heart-armor", "spiked-armor"],
    "gloves": ["gloves", "bracers", "gauntlet", "gauntlet", "mailed-fist", "gauntlet", "mailed-fist"],
    "gloves_cloth": ["gloves", "winter-gloves"],
    "legs_cloth": ["trousers"],
    "legs_leather": ["trousers", "armored-pants", "trousers"],
    "legs_heavy": ["greaves", "armor-cuisses", "greaves", "armored-pants"],
    "boots": ["boots", "leather-boot", "walking-boot", "metal-boot", "steeltoe-boots", "metal-boot", "steeltoe-boots"],
    "boots_cloth": ["sandal", "tabi-boot", "boots"],
    "cloak": ["cloak", "cape", "cape-armor", "vampire-cape", "wing-cloak", "cape", "cloak"],
    "pauldron": ["pauldrons", "shoulder-armor"],
    "belt": ["belt", "belt-buckles"],
    # accessories
    "ring": ["ring", "diamond-ring", "power-ring", "skull-ring", "swirl-ring", "frozen-ring", "globe-ring"],
    "amulet": ["necklace", "gem-necklace", "pendant-key", "tribal-pendant", "gem-pendant", "emerald-necklace", "intricate-necklace"],
    "talisman": ["rune-stone", "stone-tablet", "wax-seal", "horn-internal", "crystal-eye", "eye-of-horus", "sheikah-eye"],
    # tools
    "tool_axe": ["wood-axe", "axe-in-log", "sharp-axe"],
    "tool_pick": ["pick-of-destiny" if False else "gold-bar", "gold-bar"],
    "sickle": ["sickle"],
    "hammer": ["claw-hammer", "flat-hammer", "hammer-nails"],
    "rod": ["fishing-pole", "fishing-hook", "fishing-lure"],
    "saw": ["hand-saw", "crosscut-saw"],
    "chisel": ["chisel"],
    "shovel": ["shovel" if False else "stone-crafting", "stone-crafting"],
    "key": ["key", "skeleton-key", "house-keys", "boss-key", "star-key", "three-keys"],
    "book": ["book-cover", "open-book", "secret-book", "spell-book", "black-book", "white-book", "book-pile", "rule-book"],
    "scroll": ["tied-scroll", "scroll-unfurled", "scroll-quill"],
    "letter": ["love-letter", "wax-seal", "tied-scroll"],
    "chest": ["chest", "locked-chest", "open-chest"],
    "coin": ["coins-pile", "two-coins", "crown-coin", "coins"],
    "furniture_chair": ["wooden-chair", "rocking-chair", "bar-stool"],
    "furniture_table": ["table", "round-table"],
    "furniture_bed": ["bed", "bunk-beds"],
    "furniture_light": ["candle-holder", "candles", "old-lantern", "lantern", "magic-lamp", "candle-flame"],
    "furniture_storage": ["chest", "locked-chest", "bookshelf", "barrel"],
    "furniture_decor": ["porcelain-vase", "column-vase", "knight-banner", "tattered-banner", "trophies-shelf", "mirror-mirror", "flower-pot", "crown"],
    "tack": ["saddle", "hoof", "horse-head", "belt", "rope-coil"],
    "sack_food": ["swap-bag", "shoulder-bag"],
    "seed": ["plant-seed", "apple-seeds"],
    "trade": ["coins-pile", "swap-bag", "barrel", "chest", "wine-bottle", "perfume-bottle", "porcelain-vase"],
    "misc": ["knapsack" if False else "swap-bag", "hourglass"],
}

# glyphs whose name I wrote with a guard above must still resolve; build.py validates all names.
