"""Materials: ores, gems, ingots, timber, hides, cloth, herbs, monster parts, cores, stone, misc."""
from core import add, craft

F = "materials"


def mat(i, name, price, fam, tint, rarity=0, level=1, desc="", stack=30, weight=0.5, cat="material", **kw):
    return add(i, name, cat, F, price=price, stack=stack, weight=weight, rarity=rarity, level=level, desc=desc,
               tint=tint, glyph="fam:" + fam, **kw)


def build():
    # ---- ores & raw minerals --------------------------------------------------------------
    mat("tin_ore", "Tin Ore", 3, "ore", "#b8c2cc", 0, 4, "Soft grey stone. Smelted with copper it makes bronze.", cat="ore", weight=1.4, type="ore")
    mat("silver_ore", "Silver Ore", 14, "ore", "#dfe5ee", 1, 14, "Pale ore that glints in the seam. Jewellers want it.", cat="ore", weight=1.5, type="ore")
    mat("gold_nugget", "Gold Nugget", 38, "ore", "#ffd65c", 2, 18, "A heavy, buttery lump from the riverbed.", cat="ore", weight=0.4, type="ore", stack=40)
    mat("spirit_iron_ore", "Spirit-Iron Ore", 60, "ore", "#8fe9d0", 3, 42, "Dense green-lit ore that hums faintly near a cultivator.", cat="ore", weight=2.0, type="ore", stack=20)
    mat("rift_crystal", "Rift Crystal", 110, "crystal", "#c79bff", 3, 50, "Violet crystal that grows where the Rift leaks. Cold to hold and never quite still.", weight=0.6, type="crystal", stack=20)
    mat("sulfur", "Sulfur", 6, "powder", "#f0e068", 0, 6, "Yellow crust from hot springs. Alchemists burn it.", weight=0.4, type="mineral")
    mat("saltpetre", "Saltpetre", 8, "powder", "#e9efe6", 1, 10, "White crystalline salt, sharp on the tongue. It makes alchemist's fire bite.", weight=0.4, type="mineral")
    mat("flint", "Flint", 1, "stone", "#6f7480", 0, 1, "Knapped for sparks and arrow tips.", weight=0.6, type="mineral")
    mat("limestone", "Limestone", 2, "stone", "#d8d2c2", 0, 3, "Burned for lime, dressed for walls.", weight=1.6, type="mineral")
    mat("slate", "Slate", 3, "stone", "#707a88", 0, 5, "Splits clean into roof tiles.", weight=1.4, type="mineral")
    mat("marble", "Marble", 16, "stone", "#f3f0ea", 1, 16, "White stone for halls and statues.", weight=2.4, type="mineral", stack=20)
    mat("sand", "Sand", 1, "powder", "#e8d9a8", 0, 1, "Fine river sand.", weight=0.6, type="mineral")
    mat("quartz", "Rough Quartz", 6, "gem", "#e9f0ff", 0, 6, "Clear, lightly flawed stone.", weight=0.2, type="gem")
    mat("garnet", "Garnet", 24, "gem", "#d6405a", 1, 12, "Deep red, common in the hill seams.", weight=0.2, type="gem")
    mat("amethyst", "Amethyst", 42, "gem", "#b48cf0", 1, 18, "Purple crystal, prized by scholars.", weight=0.2, type="gem")
    mat("moonstone", "Moonstone", 72, "gem", "#cfe0ff", 2, 28, "Milky stone with a drifting light.", weight=0.2, type="gem", stack=20)
    mat("sapphire", "Sapphire", 120, "gem", "#4a7cf0", 2, 34, "Deep blue and flawless.", weight=0.2, type="gem", stack=20)
    mat("ruby", "Ruby", 150, "gem", "#e0323c", 2, 38, "A rich red that catches firelight.", weight=0.2, type="gem", stack=20)
    mat("ember_opal", "Ember Opal", 95, "gem", "#ff8a3c", 2, 30, "Fire-flecked opal found near Emberglass Mere.", weight=0.2, type="gem", stack=20)
    mat("spirit_jade", "Spirit Jade", 140, "gem", "#6fe0a0", 3, 40, "Jade that keeps a little qi. Cultivators carve it into talismans.", weight=0.3, type="gem", stack=20)
    mat("spirit_stone_lesser", "Lesser Spirit Stone", 30, "crystal", "#8fd0ff", 1, 10, "A chip of crystallised qi. Cultivators spend these like coin.", weight=0.1, type="spirit_stone", stack=50, qi=20)
    mat("spirit_stone", "Spirit Stone", 140, "crystal", "#6fb4ff", 2, 28, "Crystallised qi the size of a knuckle.", weight=0.2, type="spirit_stone", stack=40, qi=100)
    mat("spirit_stone_greater", "Greater Spirit Stone", 650, "crystal", "#4f8cff", 3, 45, "A luminous stone; a whole sect's month of cultivation sits in it.", weight=0.3, type="spirit_stone", stack=20, qi=500)

    # ---- ingots & metal goods ---------------------------------------------------------------
    mat("tin_ingot", "Tin Ingot", None, "ingot", "#c9d2db", 0, 4, "Soft silvery metal for alloying.", stack=20, weight=1.4, type="ingot")
    mat("bronze_ingot", "Bronze Ingot", None, "ingot", "#d9a15a", 0, 6, "Copper and tin. Holds an edge far better than copper.", stack=20, weight=1.8, type="ingot")
    mat("steel_ingot", "Steel Ingot", None, "ingot", "#dfe6f2", 1, 24, "Iron worked with coal until it rings.", stack=20, weight=2.0, type="ingot")
    mat("fine_steel_ingot", "Fine Steel Ingot", None, "ingot", "#f2f6ff", 2, 34, "Folded, quenched and folded again. Blades made of it keep their edge for years.", stack=20, weight=2.0, type="ingot")
    mat("silver_ingot", "Silver Ingot", None, "ingot", "#e6ebf4", 1, 14, "Bright and soft. Jewellers' staple.", stack=20, weight=1.6, type="ingot")
    mat("gold_ingot", "Gold Ingot", None, "ingot", "#ffd65c", 2, 20, "A small bar of gold, stamped by the mint.", stack=20, weight=2.4, type="ingot")
    mat("spirit_iron_ingot", "Spirit-Iron Ingot", None, "ingot", "#9fe8d6", 3, 44, "Metal that answers qi. Smiths of the sect yards keep the method close.", stack=20, weight=2.0, type="ingot")
    mat("rift_crystal_ingot", "Rift-Crystal Ingot", None, "ingot", "#c79bff", 3, 52, "Spirit-iron fused with Rift crystal. It is never warm.", stack=20, weight=2.2, type="ingot")
    mat("iron_nails", "Iron Nails", None, "nails", "#b7bcc6", 0, 2, "A fistful of nails, bundled with twine.", stack=60, weight=0.2, type="fitting")
    mat("hinges", "Iron Hinges", None, "nails", "#b7bcc6", 0, 4, "Pair of forged hinges for doors and chests.", stack=40, weight=0.4, type="fitting")
    mat("scrap_iron", "Scrap Iron", 2, "ore", "#8b8f98", 0, 1, "Bent, rusted bits. Worth melting down.", weight=0.8, type="scrap", stack=40)
    mat("rivets", "Rivets", None, "nails", "#b7bcc6", 0, 3, "Small iron rivets for armour and belts.", stack=80, weight=0.05, type="fitting")

    # ---- timber -------------------------------------------------------------------------------
    mat("oak_log", "Oak Log", 4, "log", "#b98a54", 0, 8, "Heavy oak from Duskbriar Wood.", weight=6.0, type="timber")
    mat("yew_log", "Yew Log", 9, "log", "#c4885b", 1, 14, "Springy, dense. Bowyers' wood.", weight=5.0, type="timber")
    mat("ironwood_log", "Ironwood Log", 20, "log", "#8a7058", 2, 30, "Wood so hard it dulls a saw. Takes a steel edge.", weight=7.0, type="timber", stack=20)
    mat("spiritwood_log", "Spiritwood Log", 80, "log", "#a8f0c8", 3, 44, "Trees that grew over old qi-veins. Sap like pale jade.", weight=5.0, type="timber", stack=20)
    mat("oak_plank", "Oak Plank", None, "plank", "#b98a54", 0, 8, "Seasoned oak board.", weight=2.4, type="timber")
    mat("ironwood_plank", "Ironwood Plank", None, "plank", "#8a7058", 2, 30, "Dense, dark plank that resists axes.", weight=3.0, type="timber")
    mat("spiritwood_plank", "Spiritwood Plank", None, "plank", "#a8f0c8", 3, 44, "A pale plank that faintly glows under moonlight.", weight=2.0, type="timber")
    mat("bark", "Oak Bark", 1, "log", "#8f6b45", 0, 2, "Tannin-rich bark for the tanner's pit.", weight=0.3, type="timber")
    mat("resin", "Pine Resin", 3, "oil", "#e8b860", 0, 2, "Sticky amber resin for glue and torches.", weight=0.2, type="timber")
    mat("charcoal", "Charcoal", None, "powder", "#3a3a40", 0, 2, "Clean-burning fuel for the forge.", weight=0.3, type="fuel")
    mat("bowstring", "Bowstring", None, "rope", "#d8cfae", 0, 3, "Waxed cord, strong enough to hold a bow drawn.", stack=20, weight=0.1, type="fitting")
    mat("arrow_shafts", "Arrow Shafts", None, "log", "#d4b98a", 0, 2, "Straight ash shafts, unfinished.", stack=60, weight=0.2, type="fitting")
    mat("goose_feather", "Goose Feathers", 1, "feather", "#f4f1e8", 0, 1, "For fletching arrows.", stack=60, weight=0.02, type="fitting")
    mat("shingles", "Wooden Shingles", None, "plank", "#a07c50", 0, 3, "Split shingles for a roof.", stack=40, weight=0.6, type="construction")

    # ---- hides, leather, furs ---------------------------------------------------------------------
    mat("rabbit_pelt", "Rabbit Pelt", 4, "hide", "#e0d0b8", 0, 1, "Small, soft and warm.", weight=0.2, type="hide")
    mat("goat_hide", "Goat Hide", 7, "hide", "#c7b79a", 0, 3, "Tough little hide.", weight=1.0, type="hide")
    mat("boar_hide", "Boar Hide", 11, "hide", "#8b6a4c", 0, 6, "Thick bristled hide. It turns a knife.", weight=2.0, type="hide")
    mat("bear_pelt", "Bear Pelt", 26, "hide", "#6b4a34", 1, 14, "A big brown pelt, heavy and warm.", weight=3.5, type="hide", stack=20)
    mat("troll_hide", "Troll Hide", 70, "hide", "#6f8a66", 2, 30, "Knobbled green-grey hide that slowly knits itself closed.", weight=4.0, type="hide", stack=10)
    mat("wyvern_hide", "Wyvern Hide", 150, "hide", "#a4703a", 3, 46, "Scaled, supple and nearly proof against steel.", weight=3.0, type="hide", stack=10)
    mat("tannin", "Tanning Liquor", 3, "oil", "#9a7048", 0, 3, "Oak-bark liquor for the pit.", weight=0.4, type="leather_aid", stack=20)
    mat("hardened_leather", "Hardened Leather", None, "leather", "#8b5a32", 1, 12, "Boiled and waxed until it rings.", stack=20, weight=0.8, type="leather")
    mat("wyvern_leather", "Wyvern Leather", None, "leather", "#c58a3c", 3, 46, "Wyvern hide worked into supple, scaled leather.", stack=20, weight=0.9, type="leather")
    mat("fur_trim", "Fur Trim", None, "leather", "#d8c8a8", 0, 4, "Strips of fur for collars and cuffs.", stack=30, weight=0.2, type="leather")
    mat("sinew", "Sinew", 2, "rope", "#e0cfa0", 0, 1, "Dried animal sinew. Stitches and strings.", stack=40, weight=0.1, type="fitting")
    mat("tallow", "Tallow", 3, "oil", "#f2e4b8", 0, 1, "Rendered fat for candles, salve and boots.", weight=0.4, type="fat")

    # ---- cloth, thread, dye -------------------------------------------------------------------------------
    mat("linen_thread", "Linen Thread", None, "thread", "#e8dcc0", 0, 2, "Spun flax.", stack=40, weight=0.05, type="thread")
    mat("wool_thread", "Wool Thread", None, "thread", "#d8d0c0", 0, 1, "Spun wool yarn.", stack=40, weight=0.05, type="thread")
    mat("linen_cloth", "Linen Cloth", None, "cloth", "#ece2c8", 0, 4, "Fine pale linen.", stack=20, weight=0.3, type="cloth")
    mat("felt", "Felt", None, "cloth", "#b8a890", 0, 3, "Pressed wool, dense and warm.", stack=20, weight=0.4, type="cloth")
    mat("silk_cocoon", "Silk Cocoon", 18, "thread", "#fdf4e0", 1, 12, "Imported from Shenlu. Unwinds into fine thread.", stack=30, weight=0.05, type="thread")
    mat("silk_thread", "Silk Thread", None, "thread", "#fff2e8", 1, 14, "Fine, strong and glossy.", stack=40, weight=0.03, type="thread")
    mat("silk_cloth", "Bolt of Silk", None, "cloth", "#f8ecf0", 2, 24, "Smooth silk that shrugs off a cold wind.", stack=20, weight=0.3, type="cloth")
    mat("spider_silk", "Spider Silk", 14, "thread", "#ecf0f4", 1, 18, "Sticky-strong web strands from giant spiders.", stack=40, weight=0.05, type="thread")
    mat("spidersilk_cloth", "Spidersilk Cloth", None, "cloth", "#e7eef6", 2, 22, "Light as breath and hard to tear.", stack=20, weight=0.25, type="cloth")
    mat("spirit_silk_cocoon", "Spirit-Silk Cocoon", 85, "thread", "#c8fff0", 3, 42, "Spun by moths that feed on qi-blossom.", stack=20, weight=0.05, type="thread")
    mat("spirit_silk", "Spirit Silk", None, "cloth", "#b8fbe6", 3, 44, "Cloth that holds qi like a cup holds water.", stack=20, weight=0.25, type="cloth")
    mat("rift_silk_thread", "Rift Silk Thread", 130, "thread", "#c79bff", 3, 50, "Threads drawn from the Rift's weaving. They move on their own.", stack=20, weight=0.03, type="thread")
    mat("riftweave_cloth", "Riftweave Cloth", None, "cloth", "#a985f0", 3, 52, "Woven Rift thread; it darkens when watched.", stack=20, weight=0.25, type="cloth")
    for k, n, c, hint in [("red", "Madder Red", "#c4424a", "madder root"), ("blue", "Woad Blue", "#3f63c4", "woad leaves"),
                          ("yellow", "Weld Yellow", "#e6c640", "weld flowers"), ("brown", "Walnut Brown", "#7a5434", "walnut husks"),
                          ("black", "Oak-Gall Black", "#2a2a30", "oak galls"), ("green", "Moss Green", "#5a8a4c", "nettle and alum")]:
        mat("dye_" + k, n + " Dye", None, "bottle", c, 0, 3, "A pot of dye made from %s." % hint, stack=20, weight=0.3, type="dye")

    # ---- herbs, mushrooms, flowers --------------------------------------------------------------------
    H = lambda i, n, p, tint, lvl, desc, r=0, fam="herb", **kw: mat(i, n, p, fam, tint, r, lvl, desc, weight=0.05, stack=40, type="herb", **kw)
    H("feverfew", "Feverfew", 3, "#c8e6b0", 3, "Bitter white-flowered herb. Breaks a fever.")
    H("nettle", "Nettle", 1, "#6fae5a", 1, "Stings the hand, cures the blood. Also makes cord.")
    H("yarrow", "Yarrow", 4, "#f0e0e8", 4, "Feathery leaves that stop bleeding.")
    H("willow_bark", "Willow Bark", 2, "#c4b088", 2, "Chewed for pain and fever.")
    H("moonpetal", "Moonpetal", 12, "#e8f0ff", 10, "Opens only at night. Steeped for sharp eyes in the dark.", 1, "flower")
    H("emberleaf", "Emberleaf", 10, "#ff9a4c", 8, "Red leaf that warms the belly.", 1)
    H("frostmint", "Frostmint", 8, "#b8ecf0", 8, "Cold, clean mint. Numbs and cools.", 1)
    H("ghostcap", "Ghostcap", 16, "#e8e8f4", 14, "Pale mushroom from graveyards. Quiets the body and dulls the mind.", 1, "mushroom")
    H("bloodmoss", "Bloodmoss", 9, "#b03040", 6, "Red moss from the wolf-runs. Knits flesh.", 0)
    H("sunroot", "Sunroot", 7, "#f0b050", 6, "Sweet root that keeps a walker going.", 0)
    H("wolfsbane", "Wolfsbane", 8, "#7a5aa0", 9, "Purple hood, deadly to handle bare-handed. Wards off beasts.", 1, "flower")
    H("nightshade", "Nightshade", 10, "#3a2858", 10, "Black berries. A little numbs; a lot kills.", 1)
    H("serpent_tongue", "Serpent's Tongue", 14, "#88b868", 16, "Forked leaf used against venom.", 1)
    H("redcap", "Redcap", 4, "#d8503c", 4, "Red mushroom with a peppery bite.", 0, "mushroom")
    H("puffball", "Puffball", 3, "#f0ecd8", 3, "Spore-heavy fungus; styptic when dried.", 0, "mushroom")
    H("spirit_ginseng", "Spirit Ginseng", 90, "#e8d8a8", 30, "A root with a man's shape. Fifty years old at least.", 3, "herb", qi=40)
    H("jade_lotus", "Jade Lotus", 120, "#a8f0c0", 36, "Blooms over qi-veins. Cultivators' prize.", 3, "flower")
    H("ember_blossom", "Ember Blossom", 60, "#ff7a3a", 26, "Petals glow at dusk. Found on the slopes above the Mere.", 2, "flower")
    H("qi_blossom", "Qi Blossom", 75, "#ffe890", 28, "Golden blossom that drinks qi from the air.", 2, "flower")
    H("ashroot", "Ashroot", 11, "#a09890", 12, "Grey root growing on burnt ground.", 1)
    H("thyme", "Thyme", 2, "#8ab86a", 1, "Kitchen herb.")
    H("sage", "Sage", 2, "#a8c8a0", 1, "Kitchen herb.")
    H("parsley", "Parsley", 1, "#58a850", 1, "Kitchen herb.")
    H("hemlock", "Hemlock", 6, "#b0c888", 8, "Spotted stem. Poisoner's herb.", 1)

    # ---- monster parts ----------------------------------------------------------------------------------
    P = lambda i, n, p, fam, tint, lvl, desc, r=0, **kw: mat(i, n, p, fam, tint, r, lvl, desc, stack=kw.pop("stack", 30), weight=kw.pop("weight", 0.3), type=kw.pop("type", "monster_part"), **kw)
    P("wolf_fang", "Wolf Fang", 5, "fang", "#f0ead8", 2, "Yellowed and sharp.")
    P("goblin_tooth", "Goblin Tooth", 3, "fang", "#e0d8a8", 2, "Filed to a point.")
    P("goblin_ear", "Goblin Ear", 4, "bone", "#7a9a5a", 2, "Bounty hunters count these.")
    P("orc_tusk", "Orc Tusk", 9, "fang", "#f2ecd0", 8, "Heavy tusk, carved by the Tuskridge clan.", 0)
    P("bone_shard", "Bone Shard", 1, "bone", "#e8e2d0", 3, "Brittle shard from a risen skeleton.")
    P("bone_dust", "Bone Dust", 6, "powder", "#efe9da", 6, "Ground bone. Good for tonics and worse things.", 0)
    P("spider_fang", "Spider Fang", 9, "fang", "#3a3a48", 10, "Hollow fang, slicked with venom.", 1)
    P("venom_sac", "Venom Sac", 14, "blood", "#6ea84c", 12, "A swollen gland. Handle with gloves.", 1, stack=20)
    P("bear_claw", "Bear Claw", 12, "claw", "#d8c8a8", 10, "Curved and thick as a thumb.", 1)
    P("troll_blood", "Troll Blood", 40, "blood", "#6f8a66", 28, "Sluggish green blood. A few drops close a wound.", 2, stack=10)
    P("troll_tooth", "Troll Tooth", 28, "fang", "#d8d0a8", 28, "Yellow and as long as a finger.", 2, stack=20)
    P("wyvern_fang", "Wyvern Fang", 90, "fang", "#f4ecd0", 44, "A fang as long as a dagger.", 3, stack=10)
    P("wyvern_scale", "Wyvern Scale", 80, "scale", "#b87a3c", 44, "Hard, light scale. Smiths pay handsomely.", 3, stack=20)
    P("wyvern_wing_membrane", "Wyvern Wing Membrane", 120, "hide", "#c89850", 46, "Thin, tough skin from a wyvern wing.", 3, stack=10)
    P("wyvern_venom_gland", "Wyvern Venom Gland", 100, "blood", "#7ac04c", 46, "Venom that dissolves iron.", 3, stack=10)
    P("ghost_essence", "Ghost Essence", 22, "blood", "#d8e8ff", 14, "Cold fluid that clings to the hand.", 1, stack=20)
    P("ash_residue", "Ash Residue", 5, "powder", "#8a8680", 6, "Grey ash with a pulse of warmth in it. Left by the Ash-Ghosts.", 0)
    P("scar_ichor", "Scar Ichor", 26, "blood", "#8a4ab8", 16, "Violet ooze from Scar-touched beasts.", 1, stack=20)
    P("rift_dust", "Rift Dust", 34, "powder", "#b894f0", 24, "Glittering dust left when Rift creatures die.", 2, stack=20)
    P("corrupted_fang", "Corrupted Fang", 14, "fang", "#9a6ac8", 12, "A fang streaked violet.", 1)
    P("boar_tusk_fine", "Prime Boar Tusk", 16, "fang", "#f6f0d8", 10, "A long curved tusk. Good ivory.", 1)
    P("hornet_honey", "Wild Honeycomb", 6, "honey", "#f0c040", 3, "Sticky comb from a wild hive.", 0, type="forage")

    # ---- monster cores & essences -------------------------------------------------------------------------
    C = lambda i, n, p, tint, lvl, desc, r, **kw: mat(i, n, p, "core", tint, r, lvl, desc, stack=kw.pop("stack", 20), weight=0.3, type="core", **kw)
    C("minor_core", "Minor Beast Core", 16, "#a8c8ff", 6, "A pea of hardened magicules from a small beast.", 1, qi=10)
    C("lesser_core", "Lesser Beast Core", 55, "#7fb0ff", 18, "A core the size of a walnut, warm to the touch.", 2, qi=40)
    C("beast_core", "Beast Core", 210, "#5a90ff", 32, "A strong core from an apex beast. Alchemists and cultivators both bid.", 3, qi=160, stack=10)
    C("greater_core", "Greater Beast Core", 780, "#8a70ff", 46, "A fist-sized core; light pulses inside.", 3, qi=600, stack=5)
    C("rift_core", "Rift Core", 1500, "#c79bff", 55, "A heart of Rift crystal from a creature that should not exist.", 3, qi=1200, stack=3)
    for el, col, n in [("fire", "#ff7a3a", "Fire"), ("water", "#4aa8ff", "Water"), ("wind", "#b8f0d8", "Wind"),
                       ("earth", "#b89860", "Earth"), ("lightning", "#fff070", "Lightning")]:
        mat("essence_" + el, n + " Essence", 34, "vial", col, 2, 16, "A vial of condensed %s magicules." % el.lower(), stack=20, weight=0.2, type="essence", element=el)

    # ---- construction & craft supplies ---------------------------------------------------------------------
    mat("brick", "Fired Brick", None, "brick", "#c4704c", 0, 4, "Fired clay brick.", weight=1.2, type="construction")
    mat("roof_tile", "Roof Tile", None, "brick", "#b85a3c", 0, 5, "Curved clay tile.", weight=0.8, type="construction")
    mat("lime", "Quicklime", None, "powder", "#f4f4ee", 0, 4, "Burned limestone. Mix with sand for mortar.", weight=0.6, type="construction")
    mat("mortar", "Mortar", None, "powder", "#b8b4a8", 0, 4, "Lime and sand for laying stone.", weight=1.0, type="construction")
    mat("glass", "Glass Pane", None, "gem", "#d8f0f4", 1, 10, "A clear pane, blown and flattened.", stack=20, weight=0.8, type="construction")
    mat("rope", "Hemp Rope", None, "rope", "#c8b48a", 0, 2, "Twisted hemp line, ten metres.", stack=20, weight=0.6, type="construction")
    mat("glue", "Hide Glue", None, "oil", "#d8c090", 0, 2, "Boiled down for joinery.", stack=20, weight=0.2, type="craft_aid")
    mat("wax", "Beeswax", 5, "honey", "#f0d890", 0, 2, "Golden wax, good for candles and sealing.", weight=0.2, type="craft_aid")
    mat("lamp_oil", "Lamp Oil", None, "oil", "#e8d070", 0, 2, "Rendered oil for a lantern.", stack=20, weight=0.4, type="fuel")
    mat("quench_oil", "Quenching Oil", None, "oil", "#6a5a3a", 1, 14, "Thick oil for tempering steel.", stack=20, weight=0.5, type="smith_aid")
    mat("flux", "Smith's Flux", None, "powder", "#e0d8b0", 1, 14, "Borax and sand. Cleans a weld.", stack=30, weight=0.3, type="smith_aid")
    mat("salt", "Salt", 2, "powder", "#f4f4f4", 0, 1, "A pouch of coarse salt.", stack=40, weight=0.3, type="preserve")
    mat("ash", "Wood Ash", 1, "powder", "#b0aca4", 0, 1, "Lye and lime for soap, dye and tanning.", stack=40, weight=0.3, type="craft_aid")
    mat("pottery_jug", "Clay Jug", None, "bottle", "#c4905c", 0, 3, "A fired jug with a cork stopper.", stack=20, weight=0.5, type="container")
    mat("empty_vial", "Glass Vial", None, "vial", "#d8f4f8", 0, 4, "A stoppered vial.", stack=40, weight=0.1, type="container")
    mat("waxed_cloth", "Waxed Cloth", None, "cloth", "#d8c890", 0, 4, "Oilcloth. Keeps the wet out.", stack=20, weight=0.3, type="cloth")
    mat("candle", "Tallow Candle", None, "oil", "#f6e9b8", 0, 1, "A lit hour in a stick.", stack=40, weight=0.1, type="fuel")

    # ---- recipes: smelting, alloys, processing --------------------------------------------------------------
    craft("tin_ingot", "smithing", "anvil", 1, [("tin_ore", 2), ("coal", 1)], xp=6)
    craft("bronze_ingot", "smithing", "anvil", 2, [("copper_ingot", 2), ("tin_ingot", 1)], count=3, xp=10)
    craft("steel_ingot", "smithing", "anvil", 5, [("iron_ingot", 2), ("coal", 1), ("flux", 1)], count=2, xp=26, time=3.0)
    craft("fine_steel_ingot", "smithing", "anvil", 7, [("steel_ingot", 2), ("charcoal", 1), ("quench_oil", 1)], xp=46, time=4.0)
    craft("silver_ingot", "smithing", "anvil", 3, [("silver_ore", 2), ("coal", 1)], xp=14)
    craft("gold_ingot", "smithing", "anvil", 4, [("gold_nugget", 4)], xp=20)
    craft("spirit_iron_ingot", "smithing", "anvil", 9, [("spirit_iron_ore", 3), ("fine_steel_ingot", 1), ("spirit_stone_lesser", 1)], xp=80, time=5.0)
    craft("rift_crystal_ingot", "smithing", "anvil", 10, [("rift_crystal", 3), ("spirit_iron_ingot", 1), ("spirit_stone", 1)], xp=120, time=6.0)
    craft("iron_nails", "smithing", "anvil", 1, [("iron_ingot", 1)], count=15, xp=4, time=1.0)
    craft("hinges", "smithing", "anvil", 2, [("iron_ingot", 1)], count=4, xp=6)
    craft("rivets", "smithing", "anvil", 2, [("iron_ingot", 1)], count=12, xp=5)
    craft("iron_ingot", "smithing", "anvil", 2, [("scrap_iron", 4), ("coal", 1)], xp=6, rid="iron_ingot_from_scrap", name="Smelt Scrap Iron")
    craft("charcoal", "smithing", "anvil", 1, [("log", 3)], count=2, xp=3)
    craft("oak_plank", "carpentry", "workbench", 2, [("oak_log", 1)], count=2, xp=5)
    craft("ironwood_plank", "carpentry", "workbench", 6, [("ironwood_log", 1)], count=2, xp=16, time=2.0)
    craft("spiritwood_plank", "carpentry", "workbench", 9, [("spiritwood_log", 1)], count=2, xp=40, time=3.0)
    craft("bowstring", "fletching", "workbench", 1, [("sinew", 2), ("wax", 1)], xp=4)
    craft("arrow_shafts", "fletching", "workbench", 1, [("plank", 1)], count=12, xp=4)
    craft("shingles", "carpentry", "workbench", 2, [("log", 1)], count=12, xp=5)
    craft("hardened_leather", "leatherwork", "workbench", 3, [("leather", 2), ("tallow", 1), ("tannin", 1)], xp=14, time=2.4)
    craft("wyvern_leather", "leatherwork", "workbench", 9, [("wyvern_hide", 2), ("tannin", 2), ("resin", 1)], xp=60, time=4.0)
    craft("fur_trim", "leatherwork", "workbench", 2, [("fox_pelt|rabbit_pelt|bear_pelt", 1)], count=3, xp=6)
    craft("linen_thread", "tailoring", "workbench", 1, [("flax", 2)], count=2, xp=4)
    craft("wool_thread", "tailoring", "workbench", 1, [("wool", 2)], count=2, xp=3)
    craft("linen_cloth", "tailoring", "loom", 2, [("linen_thread", 4)], xp=8)
    craft("felt", "tailoring", "workbench", 1, [("wool", 3), ("ash", 1)], xp=5)
    craft("silk_thread", "tailoring", "workbench", 3, [("silk_cocoon", 2)], count=2, xp=12)
    craft("silk_cloth", "tailoring", "loom", 4, [("silk_thread", 4)], xp=22, time=2.6)
    craft("spidersilk_cloth", "tailoring", "loom", 5, [("spider_silk", 5)], xp=26)
    craft("spirit_silk", "tailoring", "loom", 9, [("spirit_silk_cocoon", 3), ("silk_thread", 2)], xp=70, time=4.0)
    craft("riftweave_cloth", "tailoring", "loom", 10, [("rift_silk_thread", 4), ("spirit_silk", 1)], xp=110, time=5.0)
    craft("waxed_cloth", "tailoring", "workbench", 2, [("cloth", 1), ("wax", 1)], xp=6)
    for k, (src, extra) in {"red": ("ashroot", None), "blue": ("nettle", "ash"), "yellow": ("sunroot", None),
                            "brown": ("bark", None), "black": ("bark", "ash"), "green": ("nettle", None)}.items():
        ins = [(src, 2), ("ash", 1)] if extra is None else [(src, 2), (extra, 1)]
        craft("dye_" + k, "tailoring", "workbench", 2, ins, xp=6)
    craft("brick", "masonry", "workbench", 2, [("clay", 2), ("firewood", 1)], count=2, xp=5)
    craft("roof_tile", "masonry", "workbench", 3, [("clay", 2), ("firewood", 1)], count=3, xp=6)
    craft("lime", "masonry", "workbench", 2, [("limestone", 2), ("charcoal", 1)], xp=5)
    craft("mortar", "masonry", "workbench", 2, [("lime", 1), ("sand", 2)], count=2, xp=4)
    craft("glass", "masonry", "anvil", 4, [("sand", 4), ("ash", 1), ("charcoal", 2)], xp=14)
    craft("rope", "tailoring", "workbench", 1, [("flax", 3)], xp=4)
    craft("glue", "carpentry", "workbench", 1, [("hides", 1), ("firewood", 1)], count=3, xp=3)
    craft("lamp_oil", "cooking", "hearth", 1, [("tallow", 2)], count=2, xp=3)
    craft("quench_oil", "alchemy", "alchemy_table", 4, [("tallow", 2), ("resin", 1), ("sulfur", 1)], xp=10)
    craft("flux", "alchemy", "alchemy_table", 3, [("ash", 2), ("sand", 1), ("saltpetre", 1)], xp=8)
    craft("pottery_jug", "masonry", "workbench", 2, [("clay", 3), ("firewood", 1)], xp=5)
    craft("empty_vial", "masonry", "anvil", 3, [("glass", 1)], count=3, xp=6)
    craft("candle", "carpentry", "workbench", 1, [("tallow", 1), ("linen_thread", 1)], count=4, xp=3)
    craft("tannin", "leatherwork", "workbench", 1, [("bark", 3), ("ash", 1)], count=2, xp=3)
