#!/bin/bash
# Generates kingdom/data/region1/world/meshy_extra.json: placements of previously unused meshy_free models
# (docs/qa/MESHY_PLACEMENT.md). Hand layout; heights come from a size table (name w h d) so every model keeps scale 1.0.
# Usage: bash kingdom/tools/region1/gen_meshy_extra.sh <sizes.txt> > kingdom/data/region1/world/meshy_extra.json
SIZES=${1:?sizes.txt}
h() { awk -v n="$1" '$1==n {printf "%.1f", $3; exit}' "$SIZES"; }
# P cat/name x z yaw [collide=0] [y=0]   -> one part row
P() { local hh; hh=$(h "$1"); [ -z "$hh" ] && { echo "NO SIZE $1" >&2; hh=2.0; }; echo "[\"free:$1@$hh\",$2,$3,$4,${5:-0},${6:-0}],"; }
rows() { local out; out=$(cat); echo "${out%,}"; }   # strip the last comma
# site id name clear center dmin dmax : a ring outside the town edge (radius*1.15 + clear + dmin .. + dmax)
site() {
  echo "{\"id\":\"$1\",\"name\":\"$2\",\"kind\":\"roadside\",\"clear\":$3,\"flatten\":true,\"center\":\"$4\",\"dmin\":$5,\"dmax\":$6,\"parts\":["
}
endsite() { echo "]},"; }

echo '{"version":1,"_doc":"Placements of unused meshy_free models (docs/qa/MESHY_PLACEMENT.md). add_parts: extra parts appended to an existing site by r1id. extra_sites: new roadside sites on a ring outside each town (Region1World.plan). Generated by kingdom/tools/region1/gen_meshy_extra.sh. Part = [asset, x, z, yaw_deg, collide, y_offset].","add_parts":{'

echo '"dawn_chapel":['
{
 P churches/chapel_stone_small -16 4 90 1; P churches/church_white_red_spire 20 2 -90 1
 P lighting/lantern_post_wood -11 8 0; P props/well_wood_roof 12 12 0 1
} | rows
echo ']'
echo '},"extra_sites":['

# Canon sites are capped (tests: Highwatch Keep <= 40 parts, canon <= 45), so their extras are separate sites around them.
site highwatch_standards "Highwatch Standards Yard" 22 "site:Highwatch Keep" 62 110
{
 P banners/banner_spear_top -12 4 0; P banners/banner_spiked_base 12 4 0; P banners/banner_stand_chains -6 -3 180
 P banners/banner_stand_hanging_chains 6 -3 180; P banners/banner_stand_iron_frame 0 8 0; P banners/banner_stand_spiked_base 0 -8 180
 P lighting/torch_hand_silver -3 0 0; P lighting/torch_hand_silver 3 0 0
} | rows
endsite
site eastern_gate_outer "Eastern Gate Outer Towers" 30 "site:The Eastern Gate" 60 110
{
 P castle/gate_dark_towers 0 -12 180 1; P castle/gate_twin_towers_blue 0 14 0 1
 P banners/banner_crossbar -14 4 0; P banners/banner_tall_cross 14 4 0
} | rows
endsite
site kingsreach_ward "Kingsreach Outer Ward" 34 Kingsreach 4 60
{
 P castle/keep_small_on_plinth 0 -14 0 1; P castle/castle_sandstone_a -24 -6 20 1; P castle/castle_sandstone_b 24 -6 -20 1
 P castle/gate_wall_ivy -33 14 90 1
 P furniture/throne_carved_wood -10 14 0; P furniture/throne_dark_red_studded -6 14 0; P furniture/throne_gold_red -2 14 0
 P furniture/throne_gothic_gold 2 14 0; P furniture/throne_leather_cushion 6 14 0; P furniture/throne_red_gothic 10 14 0
 P furniture/lectern_desk 0 18 180
 P interior/bed_canopy_red 20 14 -90 1
 P lighting/street_lamp_twin_gold -14 20 0; P lighting/street_lantern_gothic 14 20 0; P lighting/lamp_post_purple_bracket -7 22 0; P lighting/lantern_post_purple 7 22 0
 P castle/wall_battlement_block 26 18 0 1
} | rows
endsite
site kingsreach_fair "Kingsreach Gate Fair" 24 Kingsreach 4 60
{
 P market/stall_meat_shingle -12 -6 0 1; P market/stall_potatoes -4 -6 0 1; P market/stall_open_roof 4 -6 0 1; P market/shed_striped_awning 12 -7 0 1
 P signs/sign_shop_lion -12 -1.5 20; P signs/sign_blank_bracket -4 -1.5 -10; P signs/sign_blank_rope 4 -1.5 15
 P lighting/lamp_post_timber_cross -8 3 0; P lighting/street_lantern_whimsical 8 3 0
 P furniture/table_tavern_trestle -10 11 0 1; P furniture/table_tavern_thick -3 11 0 1; P furniture/table_barrel_top 3 11 0; P furniture/tavern_set_barrels_b 11 11 90 1
 P furniture/chair_simple_a -10 13.2 180; P furniture/chair_simple_b -3 13.2 180; P furniture/chair_armchair_wood 3 13.2 180
 P furniture/chair_high_back -12.5 11 90; P furniture/chair_gothic_tall -0.5 8.8 0; P furniture/chair_ornate_red 8 8.8 0
 P interior/bookshelf_glass_cabinet -17 -2 90 1; P interior/bookshelf_tall_rustic -17 3 90 1; P interior/bookshelf_wide_low -17 8 90 1
 P interior/tapestry_hunt 17 -3 -90 0 0.4; P interior/wall_shield_heater 17 2 -90; P interior/wall_shield_iron_studded 17 5 -90
} | rows
endsite
site harrowgate_church "Harrowgate Chapel Close" 26 Harrowgate 4 60
{
 P churches/church_gothic_red 0 -8 0 1; P churches/church_dark_small -16 6 90 1
 P buildings/house_dark_roof 15 4 -90 1; P buildings/house_ivy_damaged 14 -12 -90 1
 P fences/fence_picket_tall -6 10 0; P fences/fence_picket_tall -2 10 0; P fences/fence_broken_rail 2 10 0; P fences/wall_stone_railing 6 10 0
 P lighting/lantern_post_wood 0 12 0; P props/well_stone_shingle 9 12 0 1
} | rows
endsite
site emberfall_minster "Emberfall Minster Yard" 28 Emberfall 4 60
{
 P churches/church_spire_tan -8 -6 0 1; P churches/church_spire_small 12 -4 0 1; P churches/church_old_brick -2 -26 0 1
 P creatures/dragon_green_armored 0 8 180; P creatures/dragon_fire_small -14 10 150
 P lighting/street_lantern_gothic -6 14 0; P lighting/street_lantern_gothic 6 14 0
} | rows
endsite
site saltwick_harbour "Saltwick Landing" 30 Saltwick 4 60
{
 P water/dock_circular_wood 0 -10 0 1; P water/boat_longship_sail -9 4 20 1; P water/boat_rowing 9 2 -30 1
 P props/chest_blue_iron -4 -2 30; P props/chest_silver_lock -2.8 -2.4 -10; P props/chest_orange_riveted 4 -2 45
 P churches/chapel_island_small 14 -14 -45 1; P churches/church_stone_island -16 -14 45 1
 P lighting/lantern_hanging_blue -7 -10 0 0 2.0; P lighting/lantern_hanging_green 7 -10 0 0 2.0
 P lighting/lamp_post_timber_cross 0 6 0
} | rows
endsite
site oakvale_farm "Pennick Farm Yard" 24 Oakvale 4 60
{
 P farm/shed_thatch_small -8 -6 0 1; P farm/shed_plank_low 0 -7 0 1; P farm/shed_wood_shingle 8 -6 0 1
 P farm/chicken_coop_fenced -14 2 90 1; P farm/chicken_hen -12 5 20; P farm/chicken_rooster -11 3.5 -40; P farm/chicken_hen -15.2 5.5 100
 P farm/hay_bale_lowpoly -6 4 10; P farm/hay_bale_rect_a -3.5 4 80; P farm/hay_bale_round 3 5 0; P farm/hay_bale_yellow_large 6 4 40
 P fences/fence_board_gate 0 12 90; P fences/fence_gate_rail 4 12 0; P fences/fence_plank_panel -4 12 0; P fences/fence_picket_low 8 12 0
 P fences/fence_rail_grass_a 12 12 0; P fences/fence_rail_grass_b -8 12 0
 P props/well_covered_planks 14 3 0 1
} | rows
endsite
site eastmere_dairy "Eastmere Dairy Barns" 22 Eastmere 4 60
{
 P farm/shed_plank_low -6 -5 0 1; P farm/shed_thatch_small 4 -5 0 1; P farm/hay_bale_round -10 3 0; P farm/hay_bale_round -8.5 4.5 40
 P fences/fence_gate_rail 0 8 0; P fences/fence_rail_grass_a -4 8 0; P fences/fence_rail_grass_b 4 8 0; P fences/fence_plank_panel 8 8 0
} | rows
endsite
site brackenmoor_row "Brackenmoor Cottage Row" 24 Brackenmoor 4 60
{
 P buildings/house_cottage_chimney -10 -4 0 1; P buildings/house_dark_roof 0 -6 0 1; P buildings/house_ivy_damaged 10 -4 0 1
 P props/well_covered_planks 0 6 0 1; P farm/hay_bale_rect_a 14 6 30
} | rows
endsite
site westfen_row "Westfen Stilt Row" 24 Westfen 4 60
{
 P buildings/house_two_story_shingle -8 -4 0 1; P buildings/house_two_story_tall_timber 4 -5 0 1; P buildings/butcher_house 14 -2 0 1
 P props/well_stone_roofed 0 6 0 1; P flora/bush_raspberry -12 8 0; P flora/mushroom_glow_brown 12 8 0; P flora/bouquet_wild 8 8 0
} | rows
endsite
site dunhallow_gate "Dunhallow Gatehouse Yard" 24 Dunhallow 4 60
{
 P castle/gate_wall_ivy 0 -6 0 1; P castle/wall_battlement_block -12 -6 0 1; P castle/wall_battlement_block 12 -6 0 1
 P banners/banner_stand_spiked_base -4 4 0; P lighting/torch_hand_silver 4 4 0
} | rows
endsite
site highcliff_forge "Highcliff Forge Yard" 24 Highcliff 4 60
{
 P buildings/blacksmith_thatch_stone -8 -4 0 1; P buildings/blacksmith_timber_thatch 6 -6 0 1
 P props/axe_long_handle -2 6 40; P props/chest_metal_wood 2 6 0; P props/chest_copper_lock 4 6.5 20
 P lighting/torch_stake 0 7 0
} | rows
endsite
site greywatch_ring "Greywatch Wall Ring" 28 Greywatch 4 60
{
 P castle/tower_octagon_wall 0 -6 0 1; P castle/tower_pink_flag -16 -4 0 1; P castle/wall_battlement_block 12 -4 0 1; P castle/wall_battlement_block 16 -4 0 1
 P lighting/sconce_torch_bracket 12 -4 0 0 1.9; P lighting/sconce_torch_ornate 16 -4 0 0 1.9
 P lighting/sconce_wall_bowl_a -4 8 0; P lighting/sconce_wall_bowl_b 4 8 0
 P lighting/lantern_wall_iron 12 -2.9 0 0 1.3; P lighting/lantern_wall_scroll 16 -2.9 0 0 1.3
} | rows
endsite
site wolfsend_den "Wolfsend Den" 20 Wolfsend 4 60
{
 P creatures/wolf_brown -3 0 30 1; P creatures/wolf_ghost 3 2 -30 1; P creatures/spirit_fox_blue 7 -3 200
 P creatures/treant_forest -10 -6 0 1; P nature/tree_pine 12 -8 0 1
} | rows
endsite
site ravenscar_warren "Ravenscar Goblin Warren" 22 Ravenscar 4 60
{
 P creatures/goblin_a -4 0 30; P creatures/goblin_armored 0 2 180; P creatures/goblin_b 4 0 -30; P creatures/goblin_knife 2 -4 90; P creatures/goblin_ragged -3 -4 -90
 P props/chest_gold 8 -2 -30; P props/chest_pink 10 0 10; P props/chest_red_black 9 2 40; P props/chest_orange_metal -9 0 30
 P lighting/torch_dungeon_cage 0 6 0; P lighting/lantern_hanging_green -6 6 0; P loot/coin_gold_big 6 0 0 0 0.02; P loot/coin_silver_big 6.5 0.4 30 0 0.02
} | rows
endsite
site ward_glade "Ward-Stone Glade" 22 Stonehollow 4 60
{
 P magic/crystal_blue_pedestal -8 -4 0; P magic/crystal_cyan_pedestal -4 -6 0; P magic/crystal_green_pedestal_a 0 -7 0; P magic/crystal_green_pedestal_b 4 -6 0
 P magic/crystal_green_pedestal_c 8 -4 0; P magic/crystal_egg_purple 0 0 0; P magic/orb_purple_roots 0 8 0
 P magic/portal_blue_arch -12 4 90 1; P magic/portal_elf_mound 12 4 -90 1; P magic/portal_ice_arch 0 -14 0 1; P magic/portal_vine_arch 0 14 180 1
} | rows
endsite
site hollowmere_ruins "Hollowmere Old Arches" 22 Hollowmere 4 60
{
 P ruins/arch_dark_pedestal 0 -4 0 1; P ruins/ruin_arch_side -10 4 30 1; P ruins/ruin_arch_wall 10 4 -30 1; P ruins/ruin_pergola 0 10 0 1
 P nature/tree_cartoon_green_a -14 -6 0 1; P nature/tree_cartoon_green_b 14 -6 0 1
} | rows
endsite
site ashford_garden "Ashford Gardens" 18 Ashford 4 60
{
 P props/well_stone_roofed 0 0 0 1; P flora/bush_raspberry -5 3 0; P flora/bouquet_wild 5 3 0; P flora/mushroom_glow_brown 4 -4 0
 P fences/fence_picket_tall -6 6 0; P fences/fence_picket_tall -2 6 0; P fences/fence_picket_tall 2 6 0
} | rows
endsite
echo '{"id":"_end","parts":[]}]}'
