#!/usr/bin/env python3
"""Builds data/powers/bending_clips.json (per-clip playback data of UAL_CMU_Bending.glb) from two measurements:
  godot --headless --path kingdom -s tools/anim/measure_events.gd -- --glb=res://assets/incoming/mocap/cmu/clips/UAL_CMU_Bending.glb --json=events.json --limbs=all
  godot --headless --path kingdom -s tools/anim/bending_measure.gd -- --json=sink.json
  python3 tools/anim/make_bending_sidecar.py events.json sink.json
Per clip: hit (s, strike / release frame inside the played window; 0 = no strike, the clip is not retimed),
trim [t0, t1] (long takes are cut around the strike), lift ([[t, m], ...] pelvis lift in skeleton units that keeps the
lowest bone out of the floor: Fire_Box_Combo_A, Fire_Stride_Strike_F, Water_Whirl sank 5-7 cm), blend_out (s, the
tail eases back to the first pose: Earth_Punch_Hold_Deep ends crouched)."""
import json, sys, os

ev = json.load(open(sys.argv[1]))
sk = json.load(open(sys.argv[2]))
# Strike moment (s, source time) where the fastest-limb peak is the real technique (kicks, lunges).
PEAK_HIT = {"Fire_Punch_Kick": 2.4, "Fire_Stride_Strike_F": 2.75}
# Flow, stance and evasion clips: no strike frame, played whole (not retimed).
NO_HIT = {"Water_Flow_SunSalute", "Water_Dance_ArmsHigh", "Water_Lean_Sway_A", "Water_Lean_Sway_B", "Water_SpinReach_L",
          "Air_Evade_L", "Air_Evade_R", "Air_Duck_Weave_L", "Air_Balance_OneLeg", "Cultivate_Yoga_Floor_Flow",
          "Guard_Ready_Defensive", "Earth_Crouch_Reach_L", "Earth_Crouch_Reach_R", "Earth_Punch_Hold_Deep"}
FIXED_TRIM = {"Earth_Punch_Hold_Deep": [0.0, 4.6], "Water_Flow_SunSalute": [0.2, 3.6], "Cultivate_Yoga_Floor_Flow": [0.0, 6.0]}
BLEND_OUT = {"Earth_Punch_Hold_Deep": 0.7}
LEAD = 0.55        # anticipation kept before the strike
TAIL = 1.5         # follow-through kept after it
MAX_PLAIN = 2.6    # longer takes with a strike are trimmed

out = {}
for name in sorted(ev):
    e = ev[name]
    ln = float(e["len_s"])
    hit_src = 0.0
    if name in PEAK_HIT:
        hit_src = PEAK_HIT[name]
    elif name not in NO_HIT and e["hits"]:
        hit_src = float(e["hits"][0]["hit_s"])
    row = {}
    trim = FIXED_TRIM.get(name)
    if trim is None and hit_src > 0 and ln > MAX_PLAIN:
        t0 = round(max(0.0, hit_src - LEAD), 2)
        trim = [t0, round(min(ln, t0 + LEAD + TAIL), 2)]
    start = trim[0] if trim else 0.0
    row["hit"] = round(hit_src - start, 3) if hit_src > 0 else 0.0
    if trim:
        row["trim"] = trim
    lift = sk.get(name, {}).get("lift", [])
    if lift:
        row["lift"] = lift
    if name in BLEND_OUT:
        row["blend_out"] = BLEND_OUT[name]
    row["source_len"] = ln
    out[name] = row
dst = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "data", "powers", "bending_clips.json")
doc = {"_doc": "Playback data for the CMU bending clips (assets/incoming/mocap/cmu/clips/UAL_CMU_Bending.glb), read by "
       "scripts/actors/bending_library.gd. Generated by tools/anim/make_bending_sidecar.py: hit = strike frame inside the "
       "played window (0 = not retimed), trim = window cut from the source take, lift = pelvis lift curve [[t, m]] in source "
       "time (skeleton units), blend_out = seconds the tail eases back to the first pose.", "version": 1, "clips": out}
open(dst, "w").write(json.dumps(doc, indent=1) + "\n")
print("wrote", dst, len(out), "clips")
