"""Archetype-level dialogue for tools/towns/gen_town.py: lines every resident of an archetype can say beside their role's own
(greetings by time of day, a rain remark, rumours), what a friend hears from each trait, and the templates that make a line
about this very town (its landmark, its trade). The generator draws from these without repeating a line inside a town."""

ARCH_LINES = {
    "farming": {
        "greets": ["Fields do not wait for visitors, but I will spare a moment.", "Good boots. The fields are that way.", "Harvest is the only holiday we keep. The rest is work."],
        "rumours": ["Crows gather on the east field in a ring. Not feeding. Standing.", "The wheat came up thin on the stone side and thick on the far side. Odd.",
                    "The hedgerows grow faster than the hedger can trim. I trimmed twice this month.", "A cart of seed went missing between the barn and the mill. No tracks.",
                    "The old well tastes of iron this season. I do not say the stones are why.", "Wolves keep to the hedge line and never cross it. As if the hedge were a wall.",
                    "The scarecrow by the north field has moved twice. The farmer says he did not touch it.", "Barn cats bring in too many rats and too few mice. Odd, that.", "A well on the east road runs dry every dusk and fills by dawn. Nobody wants to ask why.", "The reeve's tally says forty sacks. The barn says thirty-eight. The barn is honest."],
        "morning": "Early start. The field has been awake an hour.", "evening": "Last light. The work is done or it is dark. Both are fine.",
        "night": "Shouldn't you be inside? The fields are quiet, but the dark has ears.", "rain": "Rain. Good for the barley, bad for the knees. Bless it.",
    },
    "pastoral": {
        "greets": ["Watch where you step. The flock has right of way.", "If a sheep looks at you, look back. They are judging.", "The downs are windy, the wool is warm and the dogs know best."],
        "rumours": ["A ewe lambed twins and went silent. Ewes are never silent.", "The wolves took no sheep this month. They took the bell ram. Only the bell ram.",
                    "Fleece grades are down. The buyers blame the shepherds. The shepherds blame the grass.", "A line of cairns appeared on the ridge. We did not build them.",
                    "The dogs refuse the east pasture. They sit at the gate and whine.", "Shearing went well, but the wool came off with a grey tint. Not age. Something in the grass.",
                    "A stray lamb turned up at the fold, not ours, with a ribbon on its neck. The ribbon was silk.", "The shepherds talk of a white ewe that leads the flock where nobody sends it.", "Wool prices rose last week and fell again before the carters left. Somebody is gaming the buyers.", "The old drove road is quieter than it should be. No bells, no dust, no drovers."],
        "morning": "Morning. The flock is out and the dogs are bored.", "evening": "Folding time. The sheep go in and the stories come out.",
        "night": "Quiet night. Listen for the bell. If it stops, shout.", "rain": "Rain. Wool soaks and stays wet. We smell of sheep and regret.",
    },
    "craft": {
        "greets": ["Mind the workshop. Everything here is half finished and fully dangerous.", "Good tools, good timber, good time. Pick any two.", "Buying or looking? Looking is free until you break something."],
        "rumours": ["Apprentices are fewer every year. The ones who stay learn fast and leave faster.", "A guild inspector came last month and left a list. We are still decoding it.",
                    "Somebody is copying our patterns and selling them downriver. Cheaper, and worse.", "A tool went missing from the bench. Then another. Then the bench.",
                    "Orders are good and the deadlines are cruel. The festival is early and the work is late.", "Prices at the market are off. Our work is the same. Our wages are not.",
                    "A rival workshop in the next valley pays double for our apprentices. The apprentices are listening.", "The big order came with a seal nobody recognised. The pay was real. We did not ask.", "Someone keeps leaving unfinished work on our benches overnight. It is always very good work.", "Wood is up, iron is up, and the market will not pay more. Craft is a squeeze."],
        "morning": "Morning. The shop is open if you are.", "evening": "Closing up. Come back tomorrow and bring coin.",
        "night": "Lamps are lit. Craft does not end at dusk, only the pay does.", "rain": "Rain on the roof. Good for the colour, bad for the drying.",
    },
    "mining": {
        "greets": ["Dust is the town's second weather. Mind your lungs.", "Lamp up and mind the timber. We say it twice and mean it.", "You look clean. Give it an hour."],
        "rumours": ["Pit props are failing on the third level. The foreman says rot. The crew says a knock.", "The ore carts run late. The road is fine. The carters are afraid.",
                    "A new shaft hit water and nobody could stop it. The water was warm.", "The rock dust has a taste lately. Sweet, like iron and old pennies.",
                    "Strange scratches on the tunnel wall, above head height. We stopped the dig.", "The deepest miner swears the rock breathes. He is not drunk, which is the worrying part.",
                    "The mine cat will not go below the second level. He is the best judge of air we have.", "A lamp flame leaned sideways in a sealed gallery. There is a draught from somewhere with no door.", "The pit ponies shy at the same turning every shift. The foreman has stopped using that turning.", "Pay day was delayed and nobody complained. When miners stop complaining, worry."],
        "morning": "Shift is up. Bring a lamp, bring a prayer.", "evening": "Shift is done. Wash the dust off, if the water allows.",
        "night": "Night shift. Keep your voice low. The rock listens.", "rain": "Rain. The pit floods and the pumps groan. Everybody bails.",
    },
    "fortress": {
        "greets": ["State your business and stand where I can see you.", "Keep to the road. The ditch is for enemies.", "Discipline is the one wall that needs no mortar."],
        "rumours": ["The ditch and stakes held last winter. Barely. Nobody wants a harder test.", "Recruits are keener since the stones dimmed. Keen is not the same as ready.",
                    "Messengers ride in at night and out before dawn. They wear no colours.", "The armoury is short on arrowheads. The smith is short on iron. The iron is short on road.",
                    "A sentry saw a figure on the wall, tall and still. By the time he called out, nothing.", "Wolves test the line at dusk. Men test it at dawn. We hold either way.",
                    "The beacon on the hill was lit for a moment last night and put out. Nobody ordered it.", "A cart of provisions came in with a weapon crate hidden under the grain. No papers.", "Old soldiers say the wall is built on something older. They stop talking when a recruit walks past.", "Messengers get thinner every month. Messages get shorter. That is the real pattern."],
        "morning": "Dawn drill. You are in the way.", "evening": "Evening watch. Stand easy, but not too easy.",
        "night": "Night watch. If you hear something, say nothing. Tell me.", "rain": "Rain on the wall. The sentries grumble. The mud grumbles louder.",
    },
    "hunting": {
        "greets": ["Soft voice. The wood listens.", "Boots light, bow dry, mouth shut. That is the code.", "Game does not come to the loud. Neither do I."],
        "rumours": ["A stag with a broken antler still leads the herd. Nobody dares hunt him.", "Wolves came down off the ridge in daylight. Daylight. Bold as sheep.",
                    "A hunting party found a camp with a cold fire and no tracks.", "Pelts are thick this winter. The cold came early and does not feel natural.",
                    "A lost dog came back with a collar nobody has seen. Silver, and warm.", "A hart stood in the lodge yard at dawn and left a pile of shed antlers. A gift or a warning.",
                    "A fox with a white tail ran through the lodge yard at noon and the dogs did not bark.", "The best tracker in town came back from the ridge in silence and has not hunted since.", "Hides from the north are cut wrong. Not by a hand. By something with claws.", "A flock of ravens follows the hunters now. They take nothing. They wait."],
        "morning": "Dawn hunt. If you are coming, keep quiet.", "evening": "Back from the trail. Boots wet, bags light.",
        "night": "Dark wood. Keep a fire and keep your eyes open.", "rain": "Rain keeps the deer in and the hunters out. Tempers are shorter than the days.",
    },
    "religious": {
        "greets": ["Peace on your road. Mind the step, it is older than the faith.", "Sit, if you like. Silence is free.", "All are welcome. Some are more welcome, depending on their boots."],
        "rumours": ["Pilgrims come in greater numbers and ask harder questions.", "A candle burned all night at the shrine, though none lit it.",
                    "The old tales say the stones were once voices. Now they hum. Is that better or worse?", "A traveller left a gift at the shrine and no name. A gold ring. Real gold.",
                    "The envoy's men were seen at the crossroads. They bless nothing and write everything.", "The bell rings itself at odd hours. We stopped checking.",
                    "A pilgrim fell asleep at the shrine and woke speaking a tongue nobody knows. He is perfectly well.", "The offering bowl is heavier each morning. We have not counted. We are afraid to.", "The almonry has more mouths than bread and more bread than it should. We pray over the arithmetic.", "Someone has been mending the shrine wall at night. Mortar, still wet, in the morning."],
        "morning": "Morning prayers are done. You are welcome in the garden.", "evening": "Evening vigil begins at dusk. Quiet, please.",
        "night": "Late. The shrine lamp is lit. You may sit.", "rain": "Rain on the shrine roof. A fine sound and a leaking corner.",
    },
    "merchant": {
        "greets": ["Come in, come in. Browsing is free. Buying is better.", "Time is coin. You are spending mine.", "Everything here has a price. Some things even have a fair one."],
        "rumours": ["Caravans come in later every week. The roads are quiet, which is not the same as safe.", "A rival house is undercutting us. By a little. A deliberate little.",
                    "The toll posts doubled and so did the prices. The customers did not.", "A Solkar trader paid in coin I did not know. Heavy, warm, stamped with a sun.",
                    "Contracts get signed fast and read slow. I read slow.", "Someone is buying every spare mule. For what, nobody will say.",
                    "The guild has a new seal and nobody will say who approved it.", "A man bought forty lanterns, forty ropes and nothing else. He did not say where he is going.", "Coin from three kingdoms in one purse. The man who paid had clean hands and dirty boots.", "The market bell rang at midnight. The watch swears nobody touched it."],
        "morning": "The market opens at dawn. Early buyers get the best and the worst.", "evening": "Stalls closing. Last chance for bargains and bad decisions.",
        "night": "Closed, closed. Come back in the morning and bring coin.", "rain": "Rain kills trade. Buyers hide, goods rot. I sell cloaks on the side.",
    },
    "scholarly": {
        "greets": ["Careful. Some of this is fragile and some is merely valuable.", "Do not touch the apparatus. If you must, use the left hand.", "I have a theory. It is not finished. Neither is my tea."],
        "rumours": ["The crystal in the kiln hums at night. We measured it. It matches no known note.", "Scholars from the Academy asked about the old star. We told them it is a rock.",
                    "The glass came out the wrong colour. Red where it should be clear. It was beautiful.", "A lamp lit itself in the cold room. We checked the wick. No fault.",
                    "The books say the fallen star is dead. The kiln says otherwise.", "Lenses grown near the crater see further than lenses grown anywhere else.",
                    "A visitor from the Academy measured the kiln glow with a brass instrument and went pale.", "The apprentice who copies the old notes began humming a tune the notes do not contain.", "A lens ground last week shows a second moon. We wrote it down and told no one.", "The glassworkers argue over whether the crystal is growing or the room is shrinking."],
        "morning": "Morning. The experiment is running, so keep your voice down.", "evening": "Evening. The light is best now for reading and worst for remembering.",
        "night": "Lamps at night. We call it work. Everyone else calls it madness.", "rain": "Rain. The roof leaks onto the third shelf. Move the books, move the books.",
    },
    "criminal": {
        "greets": ["You did not see me. I did not see you. Lovely.", "Looking for something? I know a man who knows where it is.", "Quiet streets are a gift. Do not spoil them."],
        "rumours": ["A cart passed in the night with the lantern covered. Nobody asked what was in it.", "Someone paid in old coin, very old. The face on it was not a king we know.",
                    "A pedlar lost his pack and found it two days later, repacked and slightly lighter.", "Fewer guards on the pass this month. More folk who do not want to be seen.",
                    "A debt was forgiven last week. That is how we know someone is dead.", "The ravens have learned some people's faces. They avoid the same ones.",
                    "The watch does not come past the third post after dark. That is the arrangement.", "A man in grey asked about a debt older than he is. We sent him to the ravens.", "A very good lock was sold here last week, and a very good lockpick the day after. Coincidence, say the sellers.", "Whoever sells the best pelts in the pass has never been seen to hunt."],
        "morning": "Early. Sleep is for the respectable.", "evening": "Dusk. The good hours start now.",
        "night": "Night. Business is brisk. Mind your pockets.", "rain": "Rain covers footprints. A blessing for some of us.",
    },
    "fishing": {
        "greets": ["Tide waits for nobody, and neither does a net.", "Smell that? That is the sea. Or the fish. Hard to say.", "If it floats, I have fished from it. If it sank, I have fished it up."],
        "rumours": ["The shoals went deep a month early. The old fishers say the cold comes from below.", "A boat came back empty with its sail torn, as if something had pulled at it.",
                    "The tide marks on the pier are wrong. Higher than last year, higher than the old stone.", "Fish tasted of iron last week. Not bad. Not right.",
                    "A light under the water off the point moves against the current.", "A seal followed my boat for a mile and spoke. I did not answer.",
                    "The gulls leave the harbour every evening in a line. They did not use to.", "A net came up with a coil of old chain in it, links as long as a forearm. We put it back.", "Tides follow the moon, they say. Ours follow something else. The old men have stopped betting.", "A boy swore he saw a ship at the mouth of the bay with no mast and no crew. The tide took it."],
        "morning": "Dawn tide. The boats are out.", "evening": "Boats are in. The catch is salted. Supper is fish.",
        "night": "Night tide. Quiet water, loud thoughts.", "rain": "Rain on the water. The fish bite better and so do the midges.",
    },
    "royal": {
        "greets": ["The court is busy. You are, I assume, expected.", "The Crown has eyes in every doorway, and so do I.", "Welcome to Kingsreach. Please touch nothing with a crest."],
        "rumours": ["The royal kitchens doubled their order of salt and did not say why.", "The guard changes at the keep every four hours now. It used to be six.",
                    "The great market is louder every day. Louder is not the same as richer.", "A tourney herald lost his voice. Someone put something in his ale, or he ran out of words.",
                    "The old chapel gets visitors from the Dawn Throne after dark. The King does not ask.", "Nobody has seen the Crown Princess ride in. Everyone has seen her ride out.",
                    "The kitchens have a new cook and nobody knows who hired her. The soup is excellent.", "The Lists were swept at midnight and swept again at dawn. Neither crew was ordered.", "Heralds have started to wear plain tabards at night. They say it is practical.", "A petitioner has waited three days outside the Chamberlain's door. He brought his own chair."],
        "morning": "The court rises early. The rest of us rise earlier.", "evening": "Evening. The torches are lit and the gossip is warm.",
        "night": "Night in the capital. Keep to the lit streets.", "rain": "Rain on the cobbles and the banners limp. Not the finest day for pageantry.",
    },
}

# What a friend hears: the first of the resident's traits that has a line here (trait names use hyphens as in town_text.TRAITS).
TRAIT_ASIDES = {
    "stubborn": "Friend, you know I will not change my mind. Ask anyway. I enjoy refusing you.",
    "hardworking": "Excuse the dust. Work does not stop for friends, though it does pause.",
    "superstitious": "Knock on wood, friend. Now touch iron. There. Safe, for a while.",
    "practical": "Good to see you. Now, what do you need, and what can you spare?",
    "dry-humoured": "You came. I am delighted. I have rehearsed this expression.",
    "protective": "Stay close to the lamp tonight, friend. I would rather fuss than regret.",
    "gloomy": "Ah. You. I would say nice day, but it is not, and you would know.",
    "wise": "A friend is a rare coin. I have spent worse.",
    "restless": "Walk with me? I cannot stay still, and you are good company on the move.",
    "kind": "Come in, sit, eat. I will hear no argument.",
    "patient": "Take your time, friend. I am in no hurry. I am, in fact, very good at waiting.",
    "gruff": "Hmph. You again. Fine. Sit. I did not say I was glad.",
    "honest": "You look tired, friend. I will not lie. Rest.",
    "proud": "You know me. You know my work. I will not insult either by modesty.",
    "warm": "There you are. I was just thinking of you, which is rare, and a compliment.",
    "gossipy": "Sit. I have news. Three pieces, one of them true, I think.",
    "jovial": "Ha! Friend! Pull up a stool, I have a story and half a loaf.",
    "nosy": "Tell me everything. No, truly. I will not ask twice. I will ask three times.",
    "disciplined": "Punctual as ever, friend. I admire that. I also resent it.",
    "tired": "Forgive me. It has been a long week and a longer day. Still, it is good to see you.",
    "sharp-eyed": "You have a new scar, and fewer coins than last time. Sit.",
    "quiet": "Hello. A pause. I am glad you came. That is all.",
    "brave": "No fear when you are here. Or little. Or I hide it better.",
    "gentle": "Friend. Gently, now. Sit. I will make something warm.",
    "curious": "What did you see on the road? Tell me every bit. I will keep the details.",
    "sentimental": "My friend. Come, I kept something for you. A small thing. It means a lot to me.",
    "thrifty": "Welcome. Wipe your boots. Please. Soap is dear and floors are dearer.",
    "cheerful": "A bright day and a bright friend! What luck!",
    "suspicious": "Ah. You. Let me look at you a moment. Fine. You pass. Come in.",
    "loyal": "Whatever you need, friend. Ask. I will not make you ask twice.",
    "sly": "Friend. I have a deal. A small one, and only a little crooked.",
    "hot-tempered": "Argh! Oh, it is you. Sorry. The kettle and I had words. Sit.",
    "meticulous": "Mind the order of things, friend. There. Now we can talk.",
    "forgetful": "Welcome, welcome. Your name is right there. On the tip of my tongue.",
    "blunt": "You look rough. Eat something. That is not advice, it is an order.",
    "solitary": "I do not say this often. It is good to see a face I do not need to avoid.",
    "serene": "Peace to you, friend. The day opens like a book. Sit and read with me.",
    "tart": "Look what the wind dragged in. Sit. Do not touch the pie.",
    "early-riser": "Up before dawn, friend? Then you saw the best of the day. I saw it first.",
    "night-owl": "Evening already? Good. My day is just starting.",
    "fond-of-puns": "Punctual as ever. I would say a pun-ctual friend, but you heard it last time.",
    "deaf-when-convenient": "Eh? Oh, it is you. I heard that. I always hear friends.",
    "weather-wise": "Smell the air, friend. Rain by supper. Bring a cloak, or come in.",
    "earnest": "I mean it when I say it is good to see you. I always mean it. Is that strange?",
    "cautious": "Close the door, friend. Gently. There. Now we can speak.",
    "generous": "Take something. Anything. No, a bigger something. I insist.",
    "bold": "Friend! I have a plan. It is a terrible plan. It is going to be wonderful.",
    "imaginative": "I dreamed of you last night. You were a heron. It suited you.",
}

# About this very town: {town}, {landmark} (the identity landmark), {flavour} ("quarry and masons"), {tagline}.
TOWN_GREETS = [
    "Welcome to {town}. Mind the {landmark}. Everyone does, eventually.",
    "First time in {town}? The {landmark} is the place to start.",
    "{town} is a small place with a long memory. State your name slowly.",
    "Folk come to {town} for {flavour}. Some stay for the quiet.",
    "You will hear {town} before you see it. Ask at the {landmark}.",
    "The {landmark} is not much to look at. It is, however, ours.",
    "Strangers in {town} get one warning and one welcome. You are on the welcome.",
    "{town} is {tagline}. Nobody thinks to say it, but it is true.",
]
TOWN_RUMOURS = [
    "The {landmark} has seen odder days than this. Nobody remembers when.",
    "Ask anyone in {town} about the {landmark}. You will get four stories and one fact.",
    "{town} lives by {flavour}. When that fails, so do we.",
    "Whatever you hear about {town}, half of it is true. We argue about which half.",
    "The {landmark} was busy last week. Something is stirring, or somebody is.",
    "If trade slows, {town} feels it first. If it speeds up, {town} feels it last.",
    "Folk say {town} was founded by someone who wanted to be left alone. We have not forgotten.",
    "The {landmark} drew a stranger last month. He asked questions and bought nothing.",
    "Every few years {town} has a winter nobody forgets. The old folk say this one is early.",
    "Ask in {town} who built the {landmark} and you will get a different name each time.",
    "A stranger asked at the {landmark} for the oldest person in {town}. We sent him to the wrong house, on purpose.",
    "When {town} is quiet we say it is peaceful. When it is very quiet we say nothing.",
]


# What the keepers of the three lots every town has say about their trade, by archetype: one rumour each, so the inn, the shop and the
# smithy of a mining town and a fishing town do not sound alike.
KEEPER_ARCH = {
    "innkeeper": {
        "farming": "Harvest crews drink the barley they cut. Somebody should tax that circle.",
        "pastoral": "Shepherds come in smelling of lanolin and leave smelling of ale. Fair trade.",
        "craft": "Half my regulars have coloured hands. The mugs gave up showing it.",
        "mining": "Miners drink quick and tip slow. I water the first and ignore the second.",
        "fortress": "Soldiers pay on pay day and owe the rest of the month. I keep two ledgers.",
        "hunting": "Hunters tell the same stories each night, bigger each time. The stag is now a monster.",
        "religious": "Pilgrims eat modestly and drink modestly. The rooms are clean and the profit is modest.",
        "merchant": "Caravan men haggle over the bill, then tip like kings. I have learnt to quote high.",
        "scholarly": "Scholars pay in ideas, mostly. I accept coin. I even accept the odd formula.",
        "criminal": "Nobody signs the book. I stopped asking years ago. The rooms are never empty.",
        "fishing": "The fishers come in at dawn and drink till noon. Their wives come at one.",
        "royal": "Court folk sit in the corner and pretend not to be here. They tip well for it.",
    },
    "shopkeeper": {
        "farming": "Seed, rope and lamp oil. The three things every farmer remembers on the last day.",
        "pastoral": "Shears, salt and string. A shepherd can make anything from those.",
        "craft": "Needles, thread, pins. I sell small things to people who make large ones.",
        "mining": "Candles, picks, tallow. Everything is bought by the dozen and burned by dusk.",
        "fortress": "Whetstones and bandages go first. I try not to think about what that means.",
        "hunting": "Bowstring, bait and bandages. A hunter's list is short and urgent.",
        "religious": "Candles, incense and a rack of small bells. Pilgrims buy the bells and lose them.",
        "merchant": "I stock what the caravans forgot. It is a surprisingly good trade.",
        "scholarly": "Ink and quills go first. Then sand, then wax. Scholars lose pens like breath.",
        "criminal": "Locks are the one thing I do not stock. Customers find that funny.",
        "fishing": "Hooks, floats and twine. If it is thin and sharp, it is a bestseller.",
        "royal": "I sell to the court's servants, never the court. They are the real customers.",
    },
    "blacksmith": {
        "farming": "Plough blades, sickles, hinges. Honest iron for honest mud.",
        "pastoral": "Shears, bells and crooks. Every blade in the fold passed my anvil.",
        "craft": "Hooks, needles, hasps. A craftsman wants a small tool made well.",
        "mining": "Picks wear out in a week and wedges in a day. I keep a pile ready.",
        "fortress": "Spear heads, mail repair, shield bosses. The army eats iron.",
        "hunting": "Broadheads, knives, trap springs. I sharpen what bites.",
        "religious": "Candle snuffers, lamp hooks, reliquary hinges. The faith has small needs and fussy ones.",
        "merchant": "Wagon tyres, chain, padlocks. The caravans keep my coals warm.",
        "scholarly": "Tongs, crucible hooks, lens frames. Fine work, fussy customers.",
        "criminal": "I make locks and I make keys. I do not ask who the keys are for.",
        "fishing": "Hooks, gaffs and anchors. If it holds a boat, I forged it.",
        "royal": "Tourney helms, guard halberds and a weathervane for the keep. The Crown's iron is paid late.",
    },
}
