"""Roles for tools/towns/gen_town.py beyond the first set in town_text.py: the extra lines every older role gets (so each has three
greetings and four rumours to draw from), and the roles the identities need (authorities, the trade kits, the capital's court).
Same tone as town_text.py: dry, terse, practical; one idea per line; 120 characters or fewer; no dashes.

NEW_ROLES: role -> (job, schedule kind, [3 greetings], [3 rumours]); job indices as in town_text.py
(0 farmer, 1 blacksmith, 2 merchant, 3 guard, 4 laborer, 5 woodcutter).
EXTRA: older role -> ([1 greeting], [2 rumours]).
Court roles (CHAMBERLAIN .. treasury clerk) belong to Kingsreach only; none of them is a steward, lord or noble (the Steward's Post,
the keep hall and the nobility system are other people's work, and the Herald Corwin Vale is the settlement's own named NPC)."""

EXTRA = {
    "innkeeper": (["Rooms are clean. The beds are honest about their age."],
                  ["A man paid for a room and asked which way the stones face. I put him by the stairs.",
                   "The cellar is cold and the cellar is empty. I ordered more. The order came back as promises."]),
    "blacksmith": (["Quick job or good job? I charge for both."],
                   ["Plough blades sell slow and spear heads sell fast. I do not like what that says.",
                    "The forge hums when the stones dim. Not loud. Enough to notice."]),
    "shopkeeper": (["If it is not on the shelf, I can find it. If it cannot be found, I can find you something similar."],
                   ["Rope sells out first, then candles, then nails. In that order, every week.",
                    "Folk buy more than they need, then bring half back. Fear shops strangely."]),
    "baker": (["Loaf, bun, or the heel nobody wants? The heel is free."],
              ["A sack of flour came in short, twice. The miller swears by his scales.",
               "The oven draws better in cold weather. So does the queue."]),
    "herbalist": (["Tell me where it hurts. Then tell me what you did before it hurt."],
                  ["Willowbark is short. Everyone has a headache this season. Draw your own conclusions.",
                   "A child asked me for something to keep the dark away. I gave her mint. It worked."]),
    "guard captain": (["Papers, if you have them. A good story, if you do not."],
                      ["My night watch wants a second lantern each. I want a second night watch.",
                       "Fewer travellers on the road, more strange footprints at the verge. I count both."]),
    "guard": (["Halt. Ah. Not a thief. Carry on."],
              ["Cold on the wall these nights. Colder than the season has a right to be.",
               "A stone by the gate flickered at midnight. I wrote it down. Nobody reads it."]),
    "reeve": (["Bring me a problem with a name and a number. Then we can talk."],
              ["Everyone owes everyone a little. Nobody agrees on the sum.",
               "Tithe is due and the barns are thin. Guess which of those I get blamed for."]),
    "elder": (["Come closer. My ears are old and your voice is young."],
              ["Winters were colder, summers longer, and the wolves stayed home. Or so I choose to remember.",
               "The old stones had names. Nobody writes them down. Nobody asks me."]),
    "child": (["Do you have a dog? I do not have a dog. Yet."],
              ["The big kids say there is a ghost in the barn. I have not checked. Yet.",
               "Mum says do not go past the last post. I am only going to the one before it."]),
    "farmer": (["Soil does not care who you are. It cares what you do on Tuesdays."],
               ["Seed is dear and wheat is cheap. Somebody is laughing and it is not me.",
                "The field by the hedge goes quiet at dusk. No crickets. I stopped sowing there."]),
    "woodcutter": (["Mind the stack. It looks tidy. It is not forgiving."],
                   ["Fewer deer in the cut this year. Fewer birds too. The wood is holding its breath.",
                    "Found an axe head grown into a trunk, old as my grandmother. Nobody here owns it."]),
    "laborer": (["Need a strong back? I have one, a bit used."],
                ["Wages are the same as last year. Prices are not. Someone is doing sums I am not.",
                 "Dug a drain and hit a flat stone with marks on it. The foreman said fill it in. I did."]),
    "carter": (["Road is mud, axle is mud, I am mud. Hello."],
               ["Wolves tracked a cart for two miles last week. I counted the miles, not the wolves.",
                "Toll keepers keep changing. Their prices are the only thing that stays the same."]),
    "miller": (["Grain is weight, flour is weight, patience is the one thing I cannot sell."],
               ["The race froze early. I broke the ice at dawn like a fool with a hammer.",
                "The mice left the mill. All of them, in one night. That is not a good sign."]),
    "shepherd": (["Do not stand between a ewe and her lamb. She will not read the sign."],
                 ["The wethers stand all night facing the same hill. I have not asked why.",
                  "Count at dusk, count at dawn, count when the dog looks worried."]),
    "dairymaid": (["The cream is the cream. You can pay for it or admire it."],
                  ["Butter came out grey twice this week. The churn is clean. The cows are tired.",
                   "A calf was born with a white blaze like a hand. Folk say it is a sign. I say it is a calf."]),
    "cheesemaker": (["Do not touch the rind. The rind is working."],
                    ["The cave stays cold in summer. Too cold. I do not go in alone after dark.",
                     "Merchants pay well and ask no questions about the age. They get what they pay for."]),
    "wool buyer": (["Staple length, crimp, grease. Tell me about your wool or I will tell you about my prices."],
                   ["A bale came in marked fine and weighed heavy. Wet. Someone is cheating the scale.",
                    "Spinners complain of knots in the clip. The shepherds blame the burrs. The burrs blame nobody."]),
    "dyer": (["Gloves are by the door. Hands stay blue for days without them."],
             ["Madder is dear this year, woad is cheap, and nobody wants yellow. Fashion is a fever.",
              "A bolt came out the wrong colour. The wrong colour sold for more. Do not ask me why."]),
    "weaver": (["Mind the loom. It has a temper, and so do I."],
               ["Good wool, bad warp. We lose a day to a single thread. Always the same thread.",
                "A shuttle knocked itself off the loom at midnight. No draught. No cat. Just the knock."]),
    "cloth merchant": (["Linen for the summer, wool for the winter, silk for the lies you tell yourself."],
                       ["Bolts from Silverford come folded wrong. Someone opens them and refolds them. Who has the time?",
                        "Colour fades if the cloth is rushed. Quality takes weeks. Customers take days."]),
    "miner": (["Lamp up, helmet down. We talk later."],
              ["The roof sang at dawn, a low note. Everyone stopped. Then everyone went back to work.",
               "A tunnel we closed in spring was open this morning. Nobody dug it."]),
    "ore sorter": (["Hands on the belt. Not that one. That one bites."],
                   ["More waste than ore this month. Either the seam is dying or someone is hiding the good stuff.",
                    "A lump rang like a bell when I dropped it. Rang for a minute. Dull lead, I told the foreman."]),
    "smelter": (["Steel does not wait for talkers. State your business."],
                ["The furnace draws like a bellows even when the bellows rest. I check the flue twice a day.",
                 "Slag came out glassy last week. Never seen that. The foreman waved it off."]),
    "quarryman": (["Dust on the boots stays on the boots. That is how you tell a quarryman from a visitor."],
                  ["The old cut has a step in it. Too neat for a quarryman, too wide for a mason. We do not go there.",
                   "A block cracked down the middle at the first strike. Perfect stone, sound ring. It cracked anyway."]),
    "fisher": (["Quiet, please. Fish can hear you, or so my father insisted."],
               ["Fish came up with eyes gone white. Could be the cold. Could be the water. We threw them back.",
                "A light on the water last night, low, moving against the current. Nobody was out."]),
    "net mender": (["Hold the line. Not that way. Over, under, over."],
                   ["Nets come back torn at the same corner. The same hand did it, or the same hook.",
                    "A net came back with a boot caught in it. Old, big, nothing in it. I hung it up."]),
    "boatwright": (["Pitch is hot, planks are cold, and my temper falls in between."],
                   ["Someone ordered a boat with a shallow draft and no name. I built it for coin.",
                    "The oak I want grows past the ward line. The oak I get grows where I can reach."]),
    "salter": (["A pinch of this keeps meat for a month. A pinch of me keeps you out of my pans."],
               ["The brine pans froze in the night, in autumn. I skimmed ice off the salt in September.",
                "A wagon left with salt and came back without the driver. The mule knew the road."]),
    "hunter": (["Step light. If something is watching, it is the wood, and the wood is patient."],
               ["A stag stood in the road this morning and did not move. Looked at me like I owed it something.",
                "Tracks by the ridge, twice the width of a wolf's. I turned back. I have a family."]),
    "trapper": (["Mind your step. Traps are cheaper than doctors."],
                ["A snare was sprung and empty, the wire bent, not broken. Not an animal's work.",
                 "The foxes are leaving. Not dying, leaving. They know something."]),
    "tanner": (["Hold your breath or hold your coin. Either way, welcome."],
               ["Hides come in with strange scars lately. Clean cuts, not teeth.",
                "The vats turned black overnight. Not rot. Something in the bark."]),
    "charcoal burner": (["Black hands, warm heart. One of those is true."],
                        ["The kiln mound hissed when it should have been silent. I opened it. Nothing. I closed it quick.",
                         "Wood is scarce near the moor. We walk further each season and the trees get older."]),
    "glasswright": (["Do not breathe on the rod. It remembers."],
                    ["Ember-crystal turns up in the sand after rain. Small, warm to the touch. We leave it.",
                     "A pane came out with a figure in it, tall and hooded. I broke it. It came out again the next day."]),
    "lamp-maker": (["Wick, oil, patience. A light that stays lit is a small miracle."],
                   ["Orders doubled since autumn. People want light they can carry.",
                    "One lamp burns blue and will not go out. Nobody has bought it. Nobody will."]),
    "scribe": (["The pen is quicker than the sword and a good deal less likely to start a fight."],
               ["Letters from the Council come sealed twice now. They do not want them read at the gate.",
                "A list of names came to me for copying. Half were crossed out. I copied the crossings too."]),
    "trader": (["Everything has a price. Sometimes the price is the question you did not ask."],
               ["Spice is up, salt is down, rumour is free. Take what you like.",
                "A Solkar caravan skipped us this month. Their guide said the road was warm. I did not ask."]),
    "weigh-master": (["Fair weight, fair price, fair temper. Choose two."],
                     ["A set of weights came in light, lead scraped from the underside. I know the hand.",
                      "Carts leave heavier than they arrive. Nobody weighs what goes out."]),
    "soldier": (["At ease. No, you at ease. I am working."],
                ["Orders say hold the line. Nobody says against what.",
                 "Boots wear out faster than armour. Nobody budgets for boots."]),
    "drillmaster": (["Again! No, not you. The rest of you. Again!"],
                    ["A third of the recruits cannot tell left from right. A third cannot tell either from a wall.",
                     "We train against wolves now. They are the only ones who turn up."]),
    "armourer": (["Fit is everything. A plate that pinches is a plate that kills."],
                 ["Orders for helmets doubled. Nobody says why. I do not ask.",
                  "A shipment of rivets came short, every one. The maker is a friend. I will ask him."]),
    "stablehand": (["Hold the lead. Gently. He is thinking of kicking and I am thinking of billing you."],
                   ["A horse bolted at dusk and came back at dawn with no mud on its legs. No mud anywhere.",
                    "The chargers whinny at night. Not at the wind. At something over the hill."]),
    "beekeeper": (["Walk slowly. They notice hurry. They respect calm."],
                  ["The hives went quiet for a night. Total silence. Then humming again, as if nothing had happened.",
                   "The honey is dark this year. Dark and sweet and with a smell I cannot place."]),
    "spinner": (["Thread is time. I sell it by the yard."],
                ["A cart of fleece arrived damp. Someone left it in the rain on purpose, I think.",
                 "I spun a skein that glowed faintly in the dark. I told no one. I am telling you."]),
    "chaplain": (["Sit, if you like. No sermon unless you ask. I am out of sermons anyway."],
                 ["Pilgrims bring stories and I do not know which to believe. I believe the ones with muddy boots.",
                  "The vigil lamp went out at the third hour and nobody had touched it. We relit it. It went out again."]),
    "pilgrim guide": (["Dry boots first, prayers second. Pilgrims forget the order."],
                      ["Pilgrims come with their children now. Children ask questions I cannot answer.",
                       "A stranger asked the way to a shrine that is on no map. I told him. I regret it."]),
}

NEW_ROLES = {
    # --- authorities (the quest giver of the town's first quest) -------------------------------------
    "yard-boss": (4, "reeve",
                  ["Boss here. Short for the one who gets blamed.", "The shift bell is the only law in the pit. Mind it.", "Questions after shift. Complaints never."],
                  ["Output is down and everyone looks at me. I look at the roof.", "Foremen are quitting. Not for money. For sleep.",
                   "A seam we mapped does not match the rock. Somebody moved the markers."]),
    "watch-commander": (3, "reeve",
                        ["Commander. Speak plain and I will listen plain.", "Walls first, comfort second. State your case.", "Quiet watch. Keep it quiet."],
                        ["Orders say hold. Hold what, and for whom, is above my rank.", "Wolves test the line at dusk. Men test it at dawn.",
                         "Recruits come, officers go. The ledger says we are even."]),
    "huntmaster": (5, "reeve",
                   ["Huntmaster. If it moves in this wood, it has been in my book.", "Bring meat or bring news. Both pay.", "Quiet in the lodge. Pelts are drying and so are tempers."],
                   ["Game is thin near the ridge. Something is hunting the hunters' ground.", "Pelts are up in price and down in number. Do the sum yourself.",
                    "A hunter did not come back. His dogs did, and would not say."]),
    "factor": (2, "reeve",
               ["Factor of the guild. Time is money. You are costing me a little.", "Contracts first, pleasantries after. Often never.", "Show me goods or show me coin. Either opens the door."],
               ["Three contracts slipped this month, all in the same hand. Mine, as it happens.", "The roads are risky and the insurance is dearer. Merchants are learning prudence.",
                "A rival house is courting our carters. I am courting them back."]),
    "harbourmaster": (4, "reeve",
                      ["Harbourmaster. I keep the tide book. The tide keeps me.", "Boats in by dusk. After dusk, boats are the sea's business.", "Keep the pier clear, the nets dry and your questions short."],
                      ["The tide tables are off by a quarter hour. For a week. The water is learning new habits.", "A boat came in with nobody aboard. Fish still in the net. Warm tea in the cup.",
                       "Salt tax is up and fish are down. The tide is the only thing behaving."]),
    "headman": (4, "reeve",
                ["I am the headman. Nobody voted. Nobody objected.", "Business is business and I am the business.", "Walk quiet, speak quieter, and we get on."],
                ["Things move through here at night. I do not look at what.", "A new face asked about the old road. I sent him the long way.",
                 "The law is far, the pass is near, and I am in between."]),
    "chamberlain": (2, "reeve",
                    ["The Chamberlain's office. Appointments are weeks out. Today is exceptional.", "State your name and your business. In that order. Briefly.", "The court does not wait, but the Chamberlain will, once."],
                    ["The Council meets thrice this month. The Wardens will vote on the same thing three times.", "The Crown Princess's guard doubled again. Nobody tells the Chamberlain who pays.",
                     "A letter for the throne was opened before it arrived. I did not do it."]),
    # --- trade kits ----------------------------------------------------------------------------
    "mason": (4, "day",
              ["Chisel, mallet, square. Three tools and a lifetime.", "Stone is patient. I am less so.", "That wall will outlast us both, so mind the corners."],
              ["A block came in with a mark nobody on the crew made. It fit the wall perfectly.", "Mortar does not set in the cold. Neither do tempers.",
               "The old waymark at the ford is cracked. Not worn. Struck."]),
    "wheelwright": (1, "day",
                    ["A wheel is a circle you can stand on. Mind your weight.", "Oak for the rim, elm for the hub, ash for the spokes. Argue and I will explain.", "Bring the cart, or the wheel. Not just the complaint."],
                    ["A wagon came in with the axle snapped. Not worn. Sawn halfway, then snapped.", "Everyone wants iron tyres now. Iron is dear. Oak is patient.",
                     "A cart went by in the night with no driver I could see."]),
    "ferryman": (4, "dawn",
                 ["Fare first, then the story. In that order.", "Rope is good, current is bad. Hold on.", "Keep your feet dry if you can. Keep your coin dry if you cannot."],
                 ["The river carried a lantern past last night, floating upright. Nobody sent it.", "Fewer travellers, more cargo. Nobody asks what is under the tarp.",
                  "The water is higher than the marks say. Someone moved the marks."]),
    "rope-maker": (4, "day",
                   ["Twist it right and it holds a boat. Twist it wrong and it holds a grudge.", "Hemp, tar, patience. In that order.", "Do not stand in the walk. The line is longer than it looks."],
                   ["Rope goes missing in lengths, not coils. Somebody is cutting, not stealing.", "A coil came back from the water tied in a knot I do not know.",
                    "Ferries want new line every month. The river eats rope."]),
    "reed-cutter": (4, "dawn",
                    ["Mind the mud. It looks solid. It is a liar.", "Cut low, cut clean, cut early. Cut late and the toads win.", "Reeds are thatch, baskets and bad temper."],
                    ["The reed bed hums at dusk. Not wind. Not frogs. Something else.", "The beds are thinner near the mere. Something is feeding on the roots.",
                     "I found a boardwalk plank snapped from underneath. Not worn. Pushed."]),
    "herbwife": (2, "shop",
                 ["Bog myrtle, sweet gale, feverfew. Tell me what ails you and I will tell you what grows.", "Do not pick what you cannot name. Many have tried.", "Sit. Boil water. The rest is waiting."],
                 ["Marsh fever is early. The boardwalks creak louder at night.", "The best herbs grow past the last pole. The best herbwives send a boy.",
                  "Peat smoke keeps the toads off. For a while."]),
    "granary keeper": (2, "shop",
                       ["Everything in here is counted. Twice. Stand where I can see you.", "Seed corn is sacred. Do not look at it with hunger.", "Wheat is gold, rats are thieves, I am the law."],
                       ["Rats are in the lower bins and they have learned the latch.", "Tithe grain came in light. Half of it damp. Half the half chaff.",
                        "The count is off by a sack. One sack. It is always one sack."]),
    "oak warden": (4, "day",
                   ["The oak was here before the town. Do not forget who owes whom.", "Do not carve it. Do not climb it. Do not dream under it, if you can help it.", "Acorns are free. Opinions about the oak are not."],
                   ["Birds roost in the great oak in rows. Neat rows. I have never seen birds do that.", "A branch fell on a still day. No wind, no rot. It just fell.",
                    "The oak has a new hollow. The children say a face lives in it. I told them it is a knot."]),
    "stallholder": (2, "shop",
                    ["Best prices in the row. Do not ask about the other rows.", "Look, do not touch. Touch, you buy.", "Fresh this morning. Or yesterday morning. Same thing, mostly."],
                    ["Prices doubled at the south end of the row. Nobody agrees why.", "A thief works the market. He steals things nobody misses until they need them.",
                     "Fair day is coming. Everybody smiles. Nobody is pleased."]),
    "guild clerk": (2, "shop",
                    ["Guild seal, guild stamp, guild fee. The fee is not optional.", "Take a number. Do not take two. Do not take mine.", "Contracts, copies, counter-copies. We run on paper."],
                    ["A contract got lost between two rooms in the same building. Nobody saw it leave.", "The guild raised its dues. It raised its voice when we asked why.",
                     "Apprentices are fewer. The ones who stay want more pay."]),
    "caravan guard": (3, "day",
                      ["Hands off the crates. Eyes off the cargo.", "Watch the verge. Not me. The verge.", "The caravan leaves at dawn. Be ready or be gone."],
                      ["Dust on the south road, heavy, and not trade. Something is moving that is not a caravan.", "A guide stopped coming. Another took his place. Same horse, different hat.",
                       "Fewer bandits, more wolves. The pay is the same."]),
    "drover": (4, "dawn",
               ["Mind the herd. The herd minds nothing.", "Mules know the road better than I do. Ask a mule.", "Dust, dung and daylight. That is the trade."],
               ["The mules refuse the ford. Every one. They look at the water and sit.", "The bell on the lead mule went silent for an hour, then rang again. Nobody touched it.",
                "They say the south road is warm this year. Warm in a bad way."]),
    "raven keeper": (4, "day",
                     ["Do not stare at the black one. He stares back and he keeps count.", "Ravens keep better records than the guild. Ask me what they saw.", "Feed them first. Then ask. They are fair."],
                     ["The ravens circled the pass all night. They never do that. Something was walking.", "A raven brought me a ring. A real ring. I did not ask whose.",
                      "The flock grows every month. They are not breeding. They are arriving."]),
    "go-between": (2, "shop",
                   ["I know a man who knows a man. For a fee.", "Looking for something? I find things. Do not ask where.", "No names, no receipts, no problems."],
                   ["Prices are up on the pass, and so is the number of people who ask no questions.", "A trapper came with silver furs. I did not ask. He did not say.",
                    "Somebody is buying roads. Not owning them. Buying their silence."]),
    "chandler": (2, "shop",
                 ["Beeswax, tallow, wicks. Pick your light.", "A good candle burns slow, clean and sweet. A bad one lies about all three.", "Smell that? That is patience, melted."],
                 ["Candles burn quicker lately. Same wax, same wick. The flame is hungrier.", "A shrine ordered a hundred, then a second hundred in a hurry.",
                  "Mice go for tallow, never beeswax. I put that on the sign and sold double."]),
    "smoker": (4, "day",
               ["The smoke gets in your eyes. Then your coat. Then your dreams.", "Alder for fish, oak for ham, patience for both.", "Hang it high, hang it long, hang it away from the cat."],
               ["The smoke goes up and sideways. Wrong wind this week. Something is pushing the air.", "A rack of fish came down in the night. Chewed, not stolen.",
                "Smoked fish keeps till spring. Spring keeps getting later."]),
    "collier": (4, "day",
                ["Coal on the hands, coal in the stew. That is life.", "Sack up, sling up, shut up. In that order.", "Mind the dust. It is in the lungs by dusk."],
                ["A seam caught fire underground. We sealed it. It is still warm.", "Smoke from the heap goes straight up on windy days. That is not natural.",
                 "The price of coal is up and wages are not. The carts leave fuller each week."]),
    "night fisher": (4, "night",
                     ["Out at dusk, back at dawn. Sleep is for the rich.", "Lamp low, voice lower. Fish listen.", "Do not shine that at the water. They hate it."],
                     ["Something swims under the lamp, large and slow, circling. I stopped fishing that spot.", "A lantern bobbing in the mist, and no boat under it. We stayed in.",
                      "The catch is bigger at night. The nights are longer. Odd arithmetic."]),
    "basket weaver": (4, "day",
                      ["Willow, reed, rush. A good basket holds a promise.", "Mind your fingers. The reed bites back.", "No two baskets alike, and no two buyers either."],
                      ["A basket came back full of feathers, no bird in sight. Not mine, not anyone's.", "The best willow grows by the mere. Nobody cuts there after noon.",
                       "My hands remember a pattern I never learned."]),
    "fletcher": (4, "day",
                 ["Goose feather, ash shaft, steel head. Straight is all that matters.", "Do not test the point on your thumb. Everyone does. Everyone bleeds.", "A good arrow is a promise with a small end."],
                 ["Orders for broadheads doubled. Nobody hunts that much.", "Goose quills are scarce. The geese left early this year.",
                  "A hunter returned an arrow to me with a tooth stuck in the shaft. Not a wolf's."]),
    # --- the capital's court (Kingsreach) -------------------------------------------------------------
    "court scribe": (2, "shop",
                     ["The court record, taken daily. Do not stand on the page.", "State it once, briefly. I will write it better.", "The Council's minutes are not for sale. Their margins sometimes are."],
                     ["Votes go on the record one way and in the hall another. I write the record.", "The Wardens argue over a stone count that has not changed in a decade.",
                      "A line was struck from the record by a hand not mine. The ink was newer than the page."]),
    "tourney marshal": (3, "day",
                        ["Marshal of the Lists. No weapons in the stands. No wagers at the barrier.", "Heats at noon, finals at dusk. Do not wander onto the sand.", "Rules are three: fair, quick, and nobody dies. We get two on a good day."],
                        ["Entries are up. Skill is down. Pride is the only thing growing.", "A knight arrived with no banner, no squire and no name. He wins by not losing.",
                         "The Lists drain badly. After rain the sand is soup. A tourney in soup is a comedy."]),
    "household knight": (3, "day",
                         ["Sir Knight, if you like. The title is on loan.", "Keep clear of the keep gate. It is not aimed at you. It is aimed at everyone.", "Duty before duty. A knight has two."],
                         ["Orders from the Crown change by the hour. The sword stays the same weight.", "There is a stillness in the keep these nights. It is not peace.",
                          "A knight does not question. A knight does take notes."]),
    "falconer": (4, "dawn",
                 ["Hood up, glove on, voice down.", "She is not tame. She is willing. There is a difference.", "Do not wave. Do not run. Do not be interesting."],
                 ["The birds will not fly over the old chapel. They circle wide, as if it were a fire.", "A merlin came back with a ribbon on its leg. Not mine. Dawn Throne colours.",
                  "Gamebirds are thin this year. The court blames the weather. The falcons blame the court."]),
    "master of horse": (4, "dawn",
                        ["The royal stable. Hands out of the feed. Hands off the greys.", "A good horse is half a good rider. The other half is stubbornness.", "Stable rules: do not run, do not shout, do not stand behind."],
                        ["A royal charger refused the north gate this morning. Planted, then bolted.", "The Crown Princess rode out with four guards and came back with ten horses, not six. I counted.",
                         "Horses know when an envoy is lying. Mine shy from the Dawn Throne's man."]),
    "courtier": (2, "shop",
                 ["Charmed. Truly. Your boots are most honest.", "I am in the middle of eleven conversations. Pick one, if you like.", "Court is only theatre where everyone is cast and audience both."],
                 ["The Council has voted again. I voted too, on what to wear to the next vote.", "Whisper: the envoy is not what he says. Everyone whispers. No one acts.",
                  "A dowry has gone missing. The wedding is still on. Weddings are brave."]),
    "royal cook": (4, "early",
                   ["Dinner for two hundred. You are the two hundred and first. Wait.", "Salt, fire, patience. The kitchen has all three, the king has none.", "No samples. Taste is earned."],
                   ["The pantry runs short of everything but flour. Pies will be plain this week.", "The high table sends back more than it eats. We eat well below stairs.",
                    "A tourney crowd is eating the city dry. Good for trade, bad for sleep."]),
    "treasury clerk": (2, "shop",
                       ["Coin count in progress. Please do not breathe on the ledger.", "All receipts are filed. Not found, filed. The distinction matters.", "The treasury opens at nine. It closes when the arithmetic ends."],
                       ["The numbers do not match, in three different ways. I have submitted all three.", "Tithes come late. The envoy's gold comes early. Neither is mine to question.",
                        "A coin turned up that is older than the mint. It went into the ledger as a rounding error."]),
}

# Roles for each trade kit of data/world/town_identity.json ("kits"): the town gets one of each (up to three) before the archetype's
# general workers fill the roster. Every role named here exists in town_text.ROLES or NEW_ROLES.
KIT_ROLES = {
    "great_oak": ["oak warden"],
    "mills": ["miller"], "granary": ["granary keeper"], "big_fields": ["farmer"],
    "quarry": ["quarryman", "mason"], "dairy": ["dairymaid", "cheesemaker"], "dyers": ["dyer", "weaver"], "stalls": ["stallholder"],
    "brewery": ["laborer"], "haystacks": ["farmer"],
    "barracks": ["drillmaster", "soldier"], "watch": ["soldier"], "stables": ["stablehand", "armourer"],
    "hunters": ["hunter", "trapper", "fletcher"], "herbs": ["herbwife"], "reeds": ["reed-cutter", "basket weaver"],
    "guild": ["guild clerk", "scribe"], "caravan": ["caravan guard", "drover"],
    "salt": ["salter", "net mender"], "ferry": ["ferryman", "rope-maker"], "boats": ["boatwright", "rope-maker"],
    "kilns": ["charcoal burner"], "wagons": ["wheelwright", "carter"], "glass": ["glasswright"], "lanterns": ["lamp-maker", "night fisher"],
    "smugglers": ["go-between", "trapper"], "ravens": ["raven keeper"],
    "fair_green": ["stallholder", "wool buyer"], "wool": ["wool buyer", "spinner"], "pens": ["shepherd"],
    "smokehouse": ["smoker", "trapper"], "candles": ["chandler"], "bees": ["beekeeper"], "forge_smoke": ["smelter", "collier"],
    "tannery": ["tanner"], "shrines": ["chaplain"], "academy": ["scribe"], "mine": ["miner"],
}

# What a role does on the roster of its town: a door other than the settlement works ("keep" = the capital's keep gate).
ROLE_WORK = {
    "chamberlain": "keep", "court scribe": "keep", "courtier": "keep", "royal cook": "keep", "treasury clerk": "keep", "household knight": "keep",
    "tourney marshal": "works", "falconer": "works", "master of horse": "works",
}
