extends RefCounted
## The pool of reusable street scenes (docs/design/VERTICAL_SLICE.md P1: "50-100 reusable micro-events").
## Pure data: scripts/population/micro_events.gd weighs and picks, micro_scene.gd builds. Add a scene by adding
## an entry (and, for a new kind of staging, a template in micro_scene.gd).
##
## Entry:
##   id        unique name
##   tpl       staging template: vehicle walkers vignette chase eject kids procession shutters lamp gate fire
##             broken_cart carry (micro_scene.gd)
##   w         base weight (relative frequency while its conditions hold)
##   cd        cooldown, real seconds, before the same scene may run again (a game hour is 30 s)
##   dur       [min, max] real seconds the scene runs
##   when      hard conditions, any failing gives weight 0:
##               h [a, b]      hours (wraps midnight when b < a)
##               rain -1 / 1   only dry / only rain
##               need [flags]  all must hold   not [flags] none may hold
##               kinds [..]    settlement kinds ("town", "frontier_town", "village", "castle")
##               dom [m, r]    only on days with day % m == r
##   bell      [[hour, width], ..] weight rises towards those hours (x0.25 .. x1)
##   mods      {flag: multiplier} applied for every context flag that holds
##   dw        {district: multiplier, "*": default} (market craft poor admin inn military)
##   p         template parameters (see micro_scene.gd)
##
## Context flags (micro_events.make_context): rain night dusk dawn day market_open war festival rest scarce mourn
## monster curfew crime plague fire shutters_down.

const POOL := [
	# ------------------------------------------------------------------ vehicles
	{"id": "cart_through", "tpl": "vehicle", "w": 1.0, "cd": 70, "dur": [40, 60], "when": {"h": [6.5, 18.5]},
		"mods": {"rain": 0.6, "market_open": 1.3, "curfew": 0.3}, "dw": {"market": 1.6, "inn": 1.4, "*": 1.0},
		"p": {"body": "cart", "animals": ["horse_draft"], "driver": "worker", "speed": 1.5, "from": "gate", "to": "gate", "bark": "delivery"}},
	{"id": "hay_wagon", "tpl": "vehicle", "w": 0.7, "cd": 120, "dur": [45, 70], "when": {"h": [7, 17.5]},
		"mods": {"rain": 0.5, "monster": 0.4}, "dw": {"poor": 1.6, "craft": 1.1, "admin": 0.4, "*": 0.8},
		"p": {"body": "cart", "animals": ["ox"], "driver": "villager", "speed": 1.15, "from": "gate", "to": "gate", "bark": "farmer_home"}},
	{"id": "wood_cart", "tpl": "vehicle", "w": 0.7, "cd": 120, "dur": [40, 60], "when": {"h": [6, 16.5]},
		"mods": {"rain": 0.6, "monster": 0.4}, "dw": {"craft": 2.0, "poor": 1.0, "market": 0.7, "admin": 0.3, "*": 0.6},
		"p": {"body": "cart", "animals": ["donkey"], "driver": "worker", "speed": 1.3, "from": "gate", "to": "gate", "bark": "delivery"}},
	{"id": "noble_carriage", "tpl": "vehicle", "w": 0.6, "cd": 360, "dur": [60, 80], "when": {"h": [9, 18], "kinds": ["town", "frontier_town", "castle"]},
		"mods": {"festival": 2.2, "rest": 1.3, "war": 0.5, "monster": 0.15, "rain": 0.6, "mourn": 0.4, "curfew": 0.2}, "dw": {"admin": 2.4, "market": 1.6, "inn": 1.2, "poor": 0.2, "*": 0.5},
		"p": {"body": "covered_wagon", "animals": ["horse", "horse"], "driver": "worker", "escorts": ["guard", "guard"], "passengers": ["noble", "noble"],
			"speed": 1.9, "from": "gate", "to": "plaza", "stop": 20.0, "bark": "noble", "pax_bark": "noble", "hitch": 3.0}},
	{"id": "delivery_to_shops", "tpl": "vehicle", "w": 1.3, "cd": 160, "dur": [60, 85], "when": {"h": [6, 10.5]}, "bell": [[8.0, 2.0]],
		"mods": {"rest": 0.3, "festival": 0.5, "rain": 0.7, "scarce": 0.5, "war": 0.8}, "dw": {"market": 2.8, "craft": 1.0, "*": 0.4},
		"p": {"body": "covered_wagon", "animals": ["horse_draft"], "driver": "worker", "carriers": 2, "stop": 32.0, "from": "gate", "to": "stall",
			"speed": 1.4, "bark": "delivery"}},
	{"id": "caravan_arrival", "tpl": "vehicle", "w": 0.8, "cd": 300, "dur": [60, 85], "when": {"h": [8, 18]},
		"mods": {"war": 0.7, "monster": 0.3, "rain": 0.7, "scarce": 1.3}, "dw": {"inn": 3.2, "market": 1.6, "military": 1.1, "*": 0.4},
		"p": {"body": "covered_wagon", "animals": ["horse_draft", "horse_draft"], "driver": "merchant", "escorts": ["adventurer", "adventurer", "guard"],
			"passengers": ["merchant"], "speed": 1.3, "from": "gate", "to": "inn", "stop": 26.0, "bark": "delivery", "pax_bark": "traveller"}},
	{"id": "grain_relief_wagon", "tpl": "vehicle", "w": 3.0, "cd": 280, "dur": [60, 85], "when": {"h": [7, 17], "need": ["scarce"]},
		"mods": {"war": 0.8}, "dw": {"market": 2.5, "poor": 1.5, "*": 0.6},
		"p": {"body": "covered_wagon", "animals": ["ox", "ox"], "driver": "worker", "escorts": ["guard", "guard"], "carriers": 3, "stop": 34.0,
			"from": "gate", "to": "stall", "speed": 1.2, "bark": "delivery"}},
	{"id": "supply_wagons", "tpl": "vehicle", "w": 2.0, "cd": 200, "dur": [45, 65], "when": {"h": [6, 19], "need": ["war"]},
		"mods": {"rain": 0.7}, "dw": {"military": 3.0, "market": 1.3, "*": 0.7},
		"p": {"body": "covered_wagon", "animals": ["ox", "ox"], "driver": "soldier", "escorts": ["soldier", "soldier", "soldier"], "speed": 1.2,
			"from": "gate", "to": "gate", "bark": "war_talk"}},
	{"id": "refugee_cart", "tpl": "vehicle", "w": 1.2, "cd": 260, "dur": [50, 75], "when": {"h": [7, 19], "need": ["war"]},
		"mods": {"monster": 1.5}, "dw": {"poor": 2.0, "inn": 1.4, "*": 0.8},
		"p": {"body": "cart", "animals": ["donkey"], "driver": "elder", "passengers": ["woman", "child", "child"], "stop": 14.0, "from": "gate", "to": "plaza",
			"speed": 0.95, "bark": "shortage", "pax_bark": "shortage"}},
	{"id": "tax_collector", "tpl": "vehicle", "w": 0.7, "cd": 400, "dur": [60, 80], "when": {"h": [9, 16], "kinds": ["town", "frontier_town", "castle"], "not": ["rest", "festival"]},
		"mods": {"war": 1.6, "scarce": 0.4, "rain": 0.6}, "dw": {"admin": 2.4, "market": 1.8, "*": 0.5},
		"p": {"body": "covered_wagon", "animals": ["horse"], "driver": "worker", "escorts": ["guard", "guard"], "passengers": ["merchant"], "stop": 24.0,
			"from": "gate", "to": "stall", "speed": 1.4, "bark": "tax", "pax_bark": "tax"}},
	{"id": "broken_cart", "tpl": "broken_cart", "w": 0.8, "cd": 320, "dur": [70, 100], "when": {"h": [7, 18]},
		"mods": {"rain": 1.2, "monster": 0.3, "curfew": 0.2}, "dw": {"poor": 1.4, "market": 1.0, "craft": 1.2, "*": 0.7}, "p": {}},
	# ------------------------------------------------------------------ groups on the move
	{"id": "travelling_adventurers", "tpl": "walkers", "w": 1.0, "cd": 160, "dur": [40, 60], "when": {"h": [8, 20]},
		"mods": {"monster": 1.5, "war": 0.6, "rain": 0.6}, "dw": {"inn": 3.0, "military": 1.4, "market": 1.1, "*": 0.4},
		"p": {"from": "gate", "to": "inn", "speed": 1.25, "clip": "Walking_A", "end": "stay",
			"members": [{"role": "adventurer", "say": "adventurer"}, {"role": "adventurer"}, {"role": "adventurer"}, {"role": "adventurer", "lat": 1.2}],
			"after": {"clips": ["Life_Ambient_Look_Around", "Life_Talk_Casual", "Life_Social_Point_Directions"], "t": 10.0}}},
	{"id": "pilgrims", "tpl": "walkers", "w": 0.8, "cd": 220, "dur": [45, 65], "when": {"h": [6, 17]},
		"mods": {"rest": 2.2, "festival": 1.6, "mourn": 1.5, "monster": 0.3, "war": 0.8}, "dw": {"admin": 2.5, "poor": 1.0, "*": 0.5},
		"p": {"from": "gate", "to": "temple", "speed": 1.0, "clip": "Life_Walk_Careful", "end": "stay",
			"members": [{"role": "monk"}, {"role": "elder"}, {"role": "woman"}, {"role": "elder"}],
			"after": {"clips": ["Life_Pray_Kneel", "Life_Pray_Stand"], "t": 14.0}}},
	{"id": "patrol_returning", "tpl": "walkers", "w": 1.0, "cd": 140, "dur": [40, 55], "when": {"h": [5.5, 22]},
		"mods": {"war": 2.0, "monster": 1.6, "curfew": 1.4, "crime": 1.5, "festival": 0.8}, "dw": {"military": 3.0, "market": 1.2, "admin": 1.2, "*": 0.5},
		"p": {"from": "gate", "to": "plaza", "speed": 1.15, "clip": "Life_Walk_March", "end": "stay",
			"members": [{"role": "guard", "say": "shift", "hold": [{"id": "spear", "hand": "r"}]}, {"role": "guard", "hold": [{"id": "spear", "hand": "r"}]},
				{"role": "guard", "hold": [{"id": "spear", "hand": "r"}]}, {"role": "sergeant", "back": -3.0, "lat": 0.0}],
			"after": {"clips": ["Life_Guard_Attention", "Life_Social_Nod"], "t": 6.0}}},
	{"id": "soldiers_marching", "tpl": "walkers", "w": 2.0, "cd": 220, "dur": [45, 65], "when": {"h": [6, 19], "need": ["war"]},
		"mods": {"rain": 0.8}, "dw": {"military": 2.5, "market": 1.5, "*": 0.7},
		"p": {"from": "gate", "to": "gate", "speed": 1.3, "clip": "Life_Walk_March", "end": "leave",
			"members": [{"role": "sergeant", "say": "war_talk"}, {"role": "soldier"}, {"role": "soldier", "lat": 1.0}, {"role": "soldier", "lat": -1.0},
				{"role": "soldier"}, {"role": "soldier", "lat": 1.0}, {"role": "soldier", "lat": -1.0}]}},
	{"id": "wounded_return", "tpl": "walkers", "w": 1.4, "cd": 300, "dur": [50, 70], "when": {"h": [7, 19], "need": ["war"]},
		"mods": {"monster": 0.6}, "dw": {"military": 2.0, "inn": 1.4, "admin": 1.5, "*": 0.7},
		"p": {"from": "gate", "to": "plaza", "speed": 0.8, "clip": "Life_Walk_Limp", "end": "stay",
			"members": [{"role": "soldier"}, {"role": "soldier", "clip": "Life_Walk_Tired"}, {"role": "woman", "clip": "Walking_A", "lat": 1.2, "say": "mourning"}],
			"after": {"clips": ["Life_Mocap_Sad", "Life_Social_Mourn_Stand"], "t": 10.0, "say": "war_talk"}}},
	{"id": "hunters_return", "tpl": "walkers", "w": 0.9, "cd": 200, "dur": [40, 55], "when": {"h": [13.5, 20]},
		"mods": {"monster": 1.4, "war": 0.8}, "dw": {"poor": 1.6, "market": 1.2, "inn": 1.2, "*": 0.6},
		"p": {"from": "gate", "to": "stall", "speed": 1.1, "clip": "Walking_A", "end": "stay",
			"members": [{"role": "hunter", "upper": "Life_Carry_Sack_Upper", "say": "hunter"}, {"role": "hunter", "upper": "Life_Carry_Sack_Upper"}],
			"after": {"clips": ["Life_Market_Hand_Over", "Life_Talk_Casual"], "t": 8.0}}},
	{"id": "farmers_return_dusk", "tpl": "walkers", "w": 1.3, "cd": 130, "dur": [40, 55], "when": {"h": [16.5, 20.5], "kinds": ["village", "town", "frontier_town"]},
		"mods": {"monster": 2.0, "rain": 0.8, "festival": 0.3}, "dw": {"poor": 1.8, "craft": 0.9, "market": 0.5, "admin": 0.3, "*": 0.8},
		"p": {"from": "gate", "to": "street", "speed": 1.05, "clip": "Life_Walk_Tired", "end": "leave",
			"members": [{"role": "worker", "hold": [{"id": "hoe", "hand": "r"}], "say": "farmer_home"}, {"role": "villager", "hold": [{"id": "rake", "hand": "r"}]},
				{"role": "woman", "hold": [{"id": "sickle", "hand": "r"}]}, {"role": "worker", "hold": [{"id": "pitchfork", "hand": "r"}]}]}},
	{"id": "farmers_out_dawn", "tpl": "walkers", "w": 1.2, "cd": 130, "dur": [40, 55], "when": {"h": [5.3, 7.8], "not": ["rest", "festival", "monster"]},
		"mods": {"rain": 0.6}, "dw": {"poor": 1.8, "craft": 0.9, "*": 0.6},
		"p": {"from": "street", "to": "gate", "speed": 1.15, "clip": "Walking_A", "end": "leave",
			"members": [{"role": "worker", "hold": [{"id": "hoe", "hand": "r"}], "say": "wake"}, {"role": "villager", "hold": [{"id": "shovel", "hand": "r"}]},
				{"role": "woman", "hold": [{"id": "milk_pail", "hand": "r"}]}]}},
	{"id": "flock_through", "tpl": "walkers", "w": 0.8, "cd": 220, "dur": [45, 65], "when": {"h": [6.5, 17], "kinds": ["village", "frontier_town", "town"]},
		"mods": {"rain": 0.5, "monster": 0.2}, "dw": {"poor": 2.0, "craft": 0.8, "market": 0.5, "admin": 0.2, "*": 0.6},
		"p": {"from": "gate", "to": "gate", "speed": 0.95, "clip": "Walking_A", "end": "leave", "animals": ["sheep", "sheep", "sheep", "sheep", "sheepdog"],
			"members": [{"role": "villager", "hold": [{"id": "cane", "hand": "r"}], "say": "farmer_home"}]}},
	{"id": "cattle_home", "tpl": "walkers", "w": 0.7, "cd": 240, "dur": [45, 65], "when": {"h": [16, 19.5], "kinds": ["village"]},
		"mods": {"rain": 0.6, "monster": 0.4}, "dw": {"poor": 2.0, "*": 0.7},
		"p": {"from": "gate", "to": "street", "speed": 0.9, "clip": "Walking_A", "end": "leave", "animals": ["cow", "cow", "cow", "dog"],
			"members": [{"role": "worker", "say": "farmer_home"}]}},
	{"id": "couple_stroll", "tpl": "walkers", "w": 0.7, "cd": 180, "dur": [40, 55], "when": {"h": [17.5, 21.5], "rain": -1},
		"mods": {"rest": 1.5, "festival": 1.5, "mourn": 0.2, "curfew": 0.15, "monster": 0.2, "war": 0.7}, "dw": {"market": 1.8, "admin": 1.5, "inn": 1.3, "poor": 0.8, "*": 0.8},
		"p": {"from": "plaza", "to": "street", "speed": 0.95, "clip": "Life_Walk_Happy", "end": "stay",
			"members": [{"role": "villager", "lat": -0.5}, {"role": "woman", "lat": 0.5, "back": 0.2}],
			"after": {"clips": ["Life_Social_Hug_A", "Life_Talk_Casual"], "t": 8.0}}},
	{"id": "night_watch_rounds", "tpl": "walkers", "w": 1.4, "cd": 100, "dur": [40, 55], "when": {"h": [21, 5]},
		"mods": {"curfew": 2.5, "crime": 2.0, "monster": 1.8, "war": 1.5, "festival": 0.4}, "dw": {"military": 2.0, "poor": 1.4, "market": 1.2, "*": 1.0},
		"p": {"from": "street", "to": "street", "speed": 0.95, "clip": "Life_Guard_Patrol_Walk", "end": "leave",
			"members": [{"role": "guard", "say": "shift", "hold": [{"id": "spear", "hand": "r"}]}, {"role": "guard", "hold": [{"id": "spear", "hand": "r"}]}]}},
	# ------------------------------------------------------------------ crowds and performances
	{"id": "street_performer", "tpl": "vignette", "w": 1.2, "cd": 150, "dur": [55, 80], "when": {"h": [10, 21.5]},
		"mods": {"festival": 2.2, "rest": 1.9, "rain": 0.12, "mourn": 0.1, "curfew": 0.0, "war": 0.6, "monster": 0.2, "scarce": 0.7},
		"dw": {"market": 3.0, "inn": 2.4, "admin": 1.2, "craft": 0.8, "poor": 0.5, "military": 0.3},
		"p": {"site": "plaza", "dmin": 6, "dmax": 40,
			"members": [{"role": "bard", "clips": ["Life_Music_Lute", "Life_Music_Lute_Sit"], "hold": [{"id": "lute", "hand": "l"}], "say": ["performer", 18.0]}],
			"audience": {"n": 5, "roles": ["villager", "woman", "child", "elder", "worker"], "say": "audience"},
			"report": {"kind": "FESTIVAL", "radius": 32.0, "strength": 0.7}}},
	{"id": "town_crier", "tpl": "vignette", "w": 1.1, "cd": 200, "dur": [45, 65], "when": {"h": [8, 18], "kinds": ["town", "frontier_town", "castle"]},
		"mods": {"war": 1.5, "festival": 1.3, "rest": 0.8, "rain": 0.4, "curfew": 0.3}, "dw": {"admin": 2.6, "market": 2.0, "inn": 0.8, "*": 0.5},
		"p": {"site": "plaza", "dmin": 6, "dmax": 40,
			"members": [{"role": "merchant", "clips": ["Life_Market_Call_Out", "Life_Social_Point_Directions", "Life_Talk_Emphatic"], "say": ["@news", 10.0]}],
			"audience": {"n": 4, "roles": ["villager", "woman", "elder", "worker"], "clips": ["Life_Talk_Listen_Nod", "Life_Talk_Listen_Hips", "Life_Social_Shake_Head"]},
			"report": {"kind": "FESTIVAL", "radius": 26.0, "strength": 0.5}}},
	{"id": "street_sermon", "tpl": "vignette", "w": 0.8, "cd": 200, "dur": [50, 70], "when": {"h": [7.5, 19]},
		"mods": {"rest": 4.0, "mourn": 2.2, "festival": 1.6, "rain": 0.5, "curfew": 0.0, "plague": 1.8, "monster": 1.2}, "dw": {"admin": 3.2, "poor": 1.0, "*": 0.4},
		"p": {"site": "temple", "dmin": 4, "dmax": 50,
			"members": [{"role": "monk", "clips": ["Life_Talk_Emphatic", "Life_Talk_Explain", "Life_Pray_Stand"], "say": ["sermon", 10.0]}],
			"audience": {"n": 5, "roles": ["elder", "woman", "villager", "elder", "child"], "clips": ["Life_Talk_Listen_Nod", "Life_Pray_Kneel", "Life_Social_Nod"], "r0": 2.8, "r1": 4.6}}},
	{"id": "recruiters_calling", "tpl": "vignette", "w": 3.0, "cd": 180, "dur": [50, 75], "when": {"h": [9, 18.5], "need": ["war"]},
		"mods": {"rest": 1.4, "festival": 1.3, "rain": 0.5}, "dw": {"market": 2.6, "military": 2.2, "admin": 1.2, "*": 0.5},
		"p": {"site": "plaza", "dmin": 6, "dmax": 42,
			"members": [{"role": "sergeant", "clips": ["Life_Market_Call_Out", "Life_Social_Point_Directions", "Life_Talk_Emphatic"], "say": ["recruiter", 8.0], "off": [0.0, 0.0]},
				{"role": "soldier", "clips": ["Life_Guard_Attention", "Life_Guard_Look_Out"], "off": [-2.2, -0.8], "hold": [{"id": "spear", "hand": "r"}]},
				{"role": "soldier", "clips": ["Life_Guard_Attention", "Life_Guard_Lean_Spear"], "off": [2.2, -0.8], "hold": [{"id": "spear", "hand": "r"}]}],
			"audience": {"n": 4, "roles": ["worker", "villager", "worker", "elder"], "clips": ["Life_Talk_Listen_Nod", "Life_Social_Shake_Head", "Life_Ambient_Scratch_Head"]},
			"props": [{"key": "banner_pole", "off": [-3.4, -1.6], "scale": 1.0}],
			"report": {"kind": "FESTIVAL", "radius": 30.0, "strength": 0.6}}},
	{"id": "festival_dancers", "tpl": "vignette", "w": 3.0, "cd": 120, "dur": [60, 90], "when": {"h": [11, 23.5], "need": ["festival"]},
		"mods": {"rain": 0.5, "mourn": 0.3}, "dw": {"market": 3.0, "admin": 1.5, "inn": 1.5, "*": 0.5},
		"p": {"site": "plaza_c", "dmin": 0, "dmax": 60, "ring": {"n": 6, "r": 2.4, "roles": ["villager", "woman", "worker", "woman", "child", "villager"],
				"clips": ["Dance", "Life_Tavern_Cheer", "Life_Mocap_Happy", "Dance"]},
			"members": [{"role": "bard", "clips": ["Life_Music_Lute", "Life_Music_Flute"], "hold": [{"id": "lute", "hand": "l"}], "off": [0.0, -3.4], "say": ["performer", 20.0]}],
			"audience": {"n": 4, "roles": ["elder", "villager", "woman", "child"], "r0": 5.0, "r1": 7.0, "clips": ["Life_Social_Laugh", "Life_Tavern_Cheer", "Life_Talk_Casual"], "say": "festival_talk"},
			"report": {"kind": "FESTIVAL", "radius": 45.0, "strength": 1.0}}},
	{"id": "tavern_music", "tpl": "vignette", "w": 0.9, "cd": 170, "dur": [50, 75], "when": {"h": [17, 23.5]},
		"mods": {"festival": 2.0, "rest": 1.4, "mourn": 0.2, "curfew": 0.0, "scarce": 0.6, "rain": 0.7}, "dw": {"inn": 4.0, "market": 1.0, "*": 0.2},
		"p": {"site": "inn", "dmin": 3, "dmax": 55, "frame": "inn",
			"members": [{"role": "bard", "clips": ["Life_Music_Lute_Sit", "Life_Music_Lute"], "hold": [{"id": "lute", "hand": "l"}], "off": [1.5, 2.6], "say": ["performer", 20.0]},
				{"role": "villager", "clips": ["Life_Tavern_Toast", "Life_Tavern_Cheer"], "off": [-1.4, 2.8]},
				{"role": "worker", "clips": ["Life_Tavern_Drink", "Life_Tavern_Toast"], "off": [-0.2, 3.4]}],
			"report": {"kind": "FESTIVAL", "radius": 22.0, "strength": 0.4}}},
	{"id": "training_drills", "tpl": "vignette", "w": 1.4, "cd": 170, "dur": [55, 80], "when": {"h": [8, 17], "kinds": ["town", "frontier_town", "castle"], "not": ["festival"]},
		"mods": {"war": 3.0, "monster": 1.5, "rain": 0.15, "rest": 0.5}, "dw": {"military": 4.0, "*": 0.2},
		"p": {"site": "drill", "dmin": 0, "dmax": 70, "frame": "centre", "grid": [3, 2, 1.8], "grid_role": "guard",
			"grid_clips": ["Sword_Attack", "Life_Guard_Attention", "Punch_Jab", "Sword_Attack"], "sergeant": true}},
	{"id": "sparring_pair", "tpl": "vignette", "w": 0.8, "cd": 140, "dur": [40, 60], "when": {"h": [8, 18], "kinds": ["town", "frontier_town", "castle"]},
		"mods": {"war": 2.0, "rain": 0.2, "festival": 0.5}, "dw": {"military": 3.5, "inn": 0.8, "*": 0.2},
		"p": {"site": "drill", "dmin": 0, "dmax": 70, "frame": "centre",
			"members": [{"role": "soldier", "clips": ["Sword_Attack", "Punch_Cross"], "off": [-1.2, 0.0], "face": "centre"},
				{"role": "soldier", "clips": ["Hit_Chest", "Sword_Attack", "Life_Guard_Attention"], "off": [1.2, 0.0], "face": "centre"}],
			"audience": {"n": 2, "roles": ["worker", "guard"], "r0": 3.4, "r1": 4.4, "clips": ["Life_Tavern_Cheer", "Life_Social_Laugh", "Life_Talk_Listen_Nod"]}}},
	{"id": "merchant_argument", "tpl": "vignette", "w": 1.2, "cd": 110, "dur": [35, 55], "when": {"h": [9, 18.5]},
		"mods": {"scarce": 2.2, "festival": 0.5, "rain": 0.4, "war": 1.2, "mourn": 0.4}, "dw": {"market": 3.2, "craft": 1.0, "*": 0.3},
		"p": {"site": "stall", "dmin": 4, "dmax": 45,
			"members": [{"role": "merchant", "clips": ["Life_Social_Argue_A", "Life_Mocap_Quarrel_A"], "off": [-0.9, 0.0], "face": "centre", "say": ["merchant_a", 7.0]},
				{"role": "merchant", "clips": ["Life_Social_Argue_B", "Life_Mocap_Quarrel_B"], "off": [0.9, 0.0], "face": "centre", "say": ["merchant_b", 7.0], "delay": 2.0}],
			"audience": {"n": 3, "roles": ["villager", "woman", "worker"], "r0": 3.0, "r1": 4.6, "clips": ["Life_Talk_Listen_Hips", "Life_Talk_Gossip", "Life_Social_Shrug"]},
			"report": {"kind": "FIGHT", "radius": 22.0, "strength": 0.4}}},
	{"id": "couple_quarrel", "tpl": "vignette", "w": 0.6, "cd": 150, "dur": [30, 45], "when": {"h": [16, 23]},
		"mods": {"scarce": 2.0, "war": 1.4, "festival": 0.4, "curfew": 0.4, "mourn": 0.3}, "dw": {"poor": 2.5, "craft": 1.2, "inn": 1.2, "admin": 0.3, "*": 0.8},
		"p": {"site": "door", "dmin": 6, "dmax": 40,
			"members": [{"role": "villager", "clips": ["Life_Mocap_Quarrel_A", "Life_Social_Argue_A"], "off": [-0.8, 0.0], "face": "centre"},
				{"role": "woman", "clips": ["Life_Mocap_Quarrel_B", "Life_Social_Argue_B"], "off": [0.8, 0.0], "face": "centre", "say": ["merchant_b", 9.0]}]}},
	{"id": "laundry_day", "tpl": "vignette", "w": 1.3, "cd": 160, "dur": [60, 90], "when": {"h": [8, 15], "rain": -1, "dom": [7, 2]},
		"mods": {"mourn": 0.5, "monster": 0.2, "curfew": 0.2}, "dw": {"poor": 3.0, "craft": 1.2, "market": 0.5, "admin": 0.2, "*": 0.6},
		"p": {"site": "door", "dmin": 5, "dmax": 38,
			"members": [{"role": "woman", "clips": ["Life_Chore_Laundry_Scrub", "Life_Chore_Laundry_Wring"], "off": [-1.2, 0.8], "say": ["laundry", 15.0]},
				{"role": "woman", "clips": ["Life_Chore_Hang_Washing", "Life_Chore_Laundry_Wring"], "off": [1.2, 0.6]},
				{"role": "child", "clips": ["Life_Kid_Skip", "Life_Kid_Tag_Touch"], "off": [0.2, 2.6]}],
			"props": [{"key": "washing_line", "off": [0.0, -1.0]}, {"key": "barrel", "off": [-2.2, 0.6], "scale": 0.9}]}},
	{"id": "gossips_at_well", "tpl": "vignette", "w": 1.2, "cd": 120, "dur": [45, 70], "when": {"h": [7, 19]},
		"mods": {"mourn": 1.4, "war": 1.3, "scarce": 1.4, "rain": 0.4, "monster": 0.7}, "dw": {"poor": 2.2, "market": 1.3, "craft": 1.0, "admin": 0.6, "*": 0.8},
		"p": {"site": "well", "dmin": 4, "dmax": 45,
			"members": [{"role": "woman", "clips": ["Life_Talk_Gossip", "Life_Talk_Emphatic"], "off": [-1.0, 1.9], "face": "centre", "say": ["gossip_well", 10.0]},
				{"role": "woman", "clips": ["Life_Talk_Listen_Nod", "Life_Social_Laugh"], "off": [1.0, 1.9], "face": "centre"},
				{"role": "elder", "clips": ["Life_Talk_Listen_Hips", "Life_Talk_Casual"], "off": [0.0, 2.9], "face": "centre"}]}},
	{"id": "street_sweeper", "tpl": "vignette", "w": 0.9, "cd": 120, "dur": [45, 60], "when": {"h": [5.5, 8.5]}, "bell": [[7.0, 1.6]],
		"mods": {"rain": 0.2, "festival": 1.3, "rest": 0.6}, "dw": {"market": 2.5, "admin": 1.6, "inn": 1.4, "poor": 0.6, "*": 0.8},
		"p": {"site": "plaza", "dmin": 5, "dmax": 40,
			"members": [{"role": "worker", "clips": ["Life_Chore_Sweep", "Life_Mocap_Sweep"], "off": [0.0, 0.0], "say": ["wake", 20.0]},
				{"role": "elder", "clips": ["Life_Chore_Sweep"], "off": [2.6, 0.8]}]}},
	{"id": "evening_sweepers", "tpl": "vignette", "w": 0.7, "cd": 150, "dur": [40, 55], "when": {"h": [18.5, 21.5]}, "bell": [[19.5, 1.0]],
		"mods": {"rain": 0.2, "festival": 0.4, "curfew": 0.5}, "dw": {"market": 2.5, "inn": 1.5, "*": 0.5},
		"p": {"site": "stall", "dmin": 5, "dmax": 40,
			"members": [{"role": "worker", "clips": ["Life_Chore_Sweep", "Life_Mocap_Sweep"], "off": [0.0, 0.0]}, {"role": "worker", "clips": ["Life_Mocap_Move_Box", "Life_Carry_Pick_Up"], "off": [2.0, 0.6]}]}},
	{"id": "beggar", "tpl": "vignette", "w": 1.0, "cd": 180, "dur": [60, 90], "when": {"h": [7, 19]},
		"mods": {"scarce": 2.6, "war": 1.5, "rain": 0.6, "festival": 0.6, "curfew": 0.2}, "dw": {"poor": 3.0, "admin": 1.8, "market": 1.6, "inn": 1.2, "military": 0.2, "craft": 0.8},
		"p": {"site": "street", "dmin": 6, "dmax": 40,
			"members": [{"role": "elder", "clips": ["Life_Rest_Sit_Ground", "Life_Mocap_Sad", "Life_Social_Shrug"], "off": [0.0, 0.0], "say": ["beggar", 14.0]}]}},
	{"id": "monk_alms", "tpl": "vignette", "w": 0.7, "cd": 220, "dur": [40, 60], "when": {"h": [7, 18]},
		"mods": {"scarce": 2.2, "rest": 2.0, "mourn": 1.4, "festival": 1.3, "rain": 0.5}, "dw": {"admin": 2.6, "poor": 1.6, "market": 1.0, "*": 0.3},
		"p": {"site": "temple", "dmin": 4, "dmax": 50,
			"members": [{"role": "elder", "clips": ["Life_Rest_Sit_Ground", "Life_Mocap_Sad"], "off": [-0.8, 1.6], "face": "centre"},
				{"role": "monk", "clips": ["Life_Market_Hand_Over", "Life_Mocap_Pay", "Life_Talk_Casual"], "off": [0.5, 0.2], "face": "centre", "say": ["thanks", 12.0]}]}},
	{"id": "peddler", "tpl": "vignette", "w": 0.9, "cd": 130, "dur": [45, 65], "when": {"h": [9, 18]},
		"mods": {"scarce": 0.7, "rain": 0.4, "festival": 1.6, "rest": 1.4}, "dw": {"market": 2.4, "poor": 1.4, "inn": 1.2, "*": 0.5},
		"p": {"site": "street", "dmin": 6, "dmax": 42,
			"members": [{"role": "merchant", "clips": ["Life_Market_Call_Out", "Life_Market_Hand_Over"], "hold": [{"id": "basket", "hand": "l"}], "say": ["peddler", 9.0]},
				{"role": "woman", "clips": ["Life_Market_Browse", "Life_Talk_Casual"], "off": [1.4, 1.8], "face": "centre"}]}},
	{"id": "market_haggling", "tpl": "vignette", "w": 1.3, "cd": 90, "dur": [35, 55], "when": {"h": [8, 18.5]},
		"mods": {"scarce": 1.4, "festival": 1.3, "rain": 0.5, "curfew": 0.0, "mourn": 0.6}, "dw": {"market": 3.0, "*": 0.3},
		"p": {"site": "stall", "dmin": 4, "dmax": 45,
			"members": [{"role": "merchant", "clips": ["Life_Market_Call_Out", "Life_Market_Hand_Over", "Life_Shop_Tally"], "off": [0.0, -0.9], "face": "away"},
				{"role": "woman", "clips": ["Life_Market_Browse", "Life_Mocap_Buy", "Life_Talk_Casual"], "off": [-0.6, 1.0], "face": "centre"},
				{"role": "villager", "clips": ["Life_Market_Browse", "Life_Mocap_Pay"], "off": [0.9, 1.4], "face": "centre"}]}},
	{"id": "teacher_lesson", "tpl": "vignette", "w": 0.8, "cd": 220, "dur": [45, 65], "when": {"h": [9, 12.5], "not": ["rest", "festival", "monster", "curfew"], "kinds": ["town", "frontier_town", "castle", "village"]},
		"mods": {"rain": 0.3, "war": 0.7}, "dw": {"admin": 2.5, "poor": 0.8, "market": 0.8, "*": 0.3},
		"p": {"site": "temple", "dmin": 4, "dmax": 50,
			"members": [{"role": "monk", "clips": ["Life_Mocap_Teach", "Life_Talk_Explain", "Life_Read_Stand"], "hold": [{"id": "book", "hand": "r"}], "say": ["teacher", 12.0]}],
			"audience": {"n": 4, "roles": ["child"], "r0": 2.4, "r1": 3.6, "clips": ["Life_Talk_Listen_Nod", "Life_Kid_Clap_Jump", "Life_Talk_Listen_Hips"]}}},
	{"id": "mourners_at_temple", "tpl": "vignette", "w": 3.0, "cd": 150, "dur": [50, 70], "when": {"h": [8, 19], "need": ["mourn"]},
		"mods": {"rest": 1.4, "plague": 1.4}, "dw": {"admin": 3.0, "poor": 1.2, "*": 0.4},
		"p": {"site": "temple", "dmin": 4, "dmax": 55,
			"members": [{"role": "woman", "clips": ["Life_Social_Mourn_Kneel", "Life_Mocap_Cry"], "off": [-1.2, 0.5], "face": "centre", "say": ["mourning", 14.0]},
				{"role": "elder", "clips": ["Life_Social_Mourn_Stand", "Life_Pray_Stand"], "off": [1.0, 1.0], "face": "centre"},
				{"role": "child", "clips": ["Life_Social_Mourn_Stand"], "off": [-0.2, 1.4], "face": "centre"}],
			"report": {"kind": "FUNERAL", "radius": 28.0, "strength": 0.6}}},
	{"id": "healer_rounds", "tpl": "vignette", "w": 3.0, "cd": 160, "dur": [45, 65], "when": {"h": [8, 18], "need": ["plague"]},
		"mods": {"mourn": 1.3}, "dw": {"poor": 2.5, "craft": 1.0, "*": 0.6},
		"p": {"site": "door", "dmin": 6, "dmax": 45,
			"members": [{"role": "monk", "clips": ["Life_Talk_Explain", "Life_Chore_Hang_Washing", "Life_Talk_Casual"], "hold": [{"id": "basket", "hand": "l"}], "off": [0.0, 0.0], "say": ["healer", 12.0]},
				{"role": "villager", "clips": ["Life_Rest_Sit_Ground", "Life_Rest_Doze_Bench", "Life_Mocap_Cold"], "off": [1.4, 1.2], "face": "centre"},
				{"role": "woman", "clips": ["Life_Mocap_Comfort_A", "Life_Social_Shake_Head"], "off": [-1.4, 1.2], "face": "centre"}]}},
	# ------------------------------------------------------------------ chases and crimes
	{"id": "thief_running", "tpl": "chase", "w": 1.0, "cd": 160, "dur": [30, 45], "when": {"h": [8, 22]},
		"mods": {"crime": 2.0, "curfew": 0.6, "scarce": 1.8, "festival": 1.3, "war": 0.8}, "dw": {"market": 3.0, "poor": 1.6, "inn": 1.6, "admin": 0.8, "*": 0.6},
		"p": {"from": "stall", "to": "gate", "runner": {"role": "thief", "clip": "Running_A", "speed": 4.8, "say": "thief"}, "chasers": ["guard", "guard"],
			"chaser_say": "stop_thief", "victim": "merchant", "victim_say": "stop_thief", "delay": 2.0, "crime": {"kind": "pickpocket", "after": 0.6}}},
	{"id": "pickpocket", "tpl": "chase", "w": 0.9, "cd": 140, "dur": [30, 45], "when": {"h": [9, 21]},
		"mods": {"crime": 2.0, "festival": 2.2, "rest": 1.4, "scarce": 1.6, "curfew": 0.3}, "dw": {"market": 3.2, "inn": 2.0, "poor": 1.2, "admin": 0.7, "*": 0.4},
		"p": {"from": "plaza", "to": "street", "runner": {"role": "thief", "clip": "Life_Walk_Brisk", "speed": 1.9}, "chasers": [], "victim": "villager",
			"victim_say": "stop_thief", "crime": {"kind": "pickpocket", "after": 2.5}}},
	{"id": "dog_chasing_chickens", "tpl": "chase", "w": 0.9, "cd": 120, "dur": [30, 45], "when": {"h": [7, 19]},
		"mods": {"rain": 0.4, "mourn": 0.6, "curfew": 0.2}, "dw": {"poor": 2.2, "craft": 1.2, "inn": 1.2, "market": 0.8, "admin": 0.3, "*": 0.8},
		"p": {"from": "plaza", "to": "street", "runner_animal": "dog", "runner": {"speed": 3.6}, "scatter": ["chicken", "chicken", "rooster"],
			"chasers": ["woman", "child"], "chaser_say": "dog", "delay": 1.5, "chaser_speed": 0.7}},
	{"id": "courier_runs", "tpl": "chase", "w": 0.5, "cd": 160, "dur": [25, 40], "when": {"h": [6, 20]},
		"mods": {"war": 5.0, "monster": 2.0, "crime": 1.4, "rain": 0.7}, "dw": {"admin": 2.4, "military": 2.0, "market": 1.2, "*": 0.6},
		"p": {"from": "gate", "to": "plaza", "runner": {"role": "soldier", "clip": "Running_A", "speed": 4.4, "say": "courier"}, "chasers": []}},
	{"id": "monster_alarm", "tpl": "chase", "w": 3.5, "cd": 150, "dur": [25, 40], "when": {"need": ["monster"]},
		"mods": {"night": 1.3}, "dw": {"military": 2.0, "poor": 1.5, "*": 1.0},
		"p": {"from": "gate", "to": "plaza", "runner": {"role": "hunter", "clip": "Running_A", "speed": 4.8, "say": "hunter"}, "chasers": ["guard", "guard"],
			"chaser_say": "guard_respond", "chaser_speed": 0.8, "delay": 1.5, "scream": true}},
	{"id": "children_chasing", "tpl": "kids", "w": 1.4, "cd": 100, "dur": [35, 55], "when": {"h": [8, 18.5], "rain": -1},
		"mods": {"rest": 1.8, "festival": 1.5, "mourn": 0.5, "war": 0.8, "monster": 0.1, "scarce": 0.8, "curfew": 0.0}, "dw": {"poor": 2.2, "market": 1.5, "inn": 0.8, "admin": 0.6, "craft": 1.0, "military": 0.2},
		"p": {"site": "plaza", "n": 3, "radius": 8.0}},
	{"id": "kids_hopscotch", "tpl": "kids", "w": 0.9, "cd": 110, "dur": [35, 55], "when": {"h": [8, 18], "rain": -1},
		"mods": {"rest": 1.5, "mourn": 0.4, "war": 0.7, "monster": 0.1}, "dw": {"poor": 2.6, "craft": 1.3, "market": 0.8, "military": 0.1, "*": 0.5},
		"p": {"site": "door", "n": 4, "radius": 3.6, "clips": ["Life_Kid_Hopscotch", "Life_Kid_Skip", "Life_Kid_Clap_Jump"]}},
	{"id": "apprentice_errand", "tpl": "carry", "w": 0.9, "cd": 100, "dur": [35, 55], "when": {"h": [8, 17.5], "not": ["rest", "festival"]},
		"mods": {"rain": 0.5, "curfew": 0.0}, "dw": {"market": 1.8, "craft": 2.0, "*": 0.6},
		"p": {"from": "door", "to": "door", "role": "child", "n": 1, "cycles": 2, "upper": "Life_Carry_Basket_Upper", "speed": 1.9, "back_speed": 2.4, "say": "peddler"}},
	# ------------------------------------------------------------------ errands and work
	{"id": "water_carriers", "tpl": "carry", "w": 1.3, "cd": 90, "dur": [45, 70], "when": {"h": [5.5, 19]}, "bell": [[7.2, 1.8], [16.8, 1.8]],
		"mods": {"rain": 0.4, "festival": 0.7, "monster": 0.5}, "dw": {"poor": 2.2, "craft": 1.3, "market": 0.8, "admin": 0.4, "*": 0.7},
		"p": {"from": "well", "to": "door", "role": "woman", "n": 2, "cycles": 2, "upper": "Life_Carry_Two_Buckets_Upper", "fill": ["Life_Chore_Well_Crank"], "fill_t": 5.0,
			"speed": 0.95, "say": "gossip_well", "drop": ["Life_Carry_Put_Down"]}},
	{"id": "baker_delivery", "tpl": "carry", "w": 1.0, "cd": 140, "dur": [40, 60], "when": {"h": [5.5, 9.5]}, "bell": [[7.0, 1.4]],
		"mods": {"scarce": 0.4, "rest": 0.5, "rain": 0.7}, "dw": {"market": 2.8, "craft": 1.3, "*": 0.4},
		"p": {"from": "door", "to": "stall", "role": "baker", "n": 1, "cycles": 3, "upper": "Life_Carry_Basket_Upper", "speed": 1.15, "back_speed": 1.5, "say": "delivery"}},
	{"id": "crate_haul", "tpl": "carry", "w": 1.0, "cd": 100, "dur": [45, 65], "when": {"h": [7, 17], "not": ["rest", "festival"]},
		"mods": {"rain": 0.7, "scarce": 0.6, "curfew": 0.0}, "dw": {"market": 2.4, "craft": 2.0, "inn": 1.2, "poor": 0.5, "*": 0.3},
		"p": {"from": "street", "to": "stall", "role": "worker", "n": 2, "cycles": 3, "upper": "Life_Carry_Crate_Upper", "speed": 1.05, "back_speed": 1.4, "say": "delivery",
			"drop": ["Life_Carry_Put_Down", "Life_Mocap_Move_Box"]}},
	{"id": "grain_porters", "tpl": "carry", "w": 0.8, "cd": 120, "dur": [45, 65], "when": {"h": [7, 16.5], "not": ["rest", "festival"]},
		"mods": {"scarce": 1.5, "rain": 0.5}, "dw": {"market": 1.8, "craft": 2.0, "poor": 0.8, "*": 0.3},
		"p": {"from": "stall", "to": "door", "role": "worker", "n": 2, "cycles": 3, "upper": "Life_Carry_Sack_Upper", "speed": 1.0, "back_speed": 1.4, "drop": ["Life_Carry_Put_Down"]}},
	# ------------------------------------------------------------------ the town's own clockwork
	{"id": "market_closing", "tpl": "shutters", "w": 4.0, "cd": 300, "dur": [40, 50], "when": {"h": [17.5, 20.5], "not": ["festival", "curfew"]}, "bell": [[18.7, 0.9]],
		"mods": {"rain": 1.4, "monster": 1.6, "war": 1.1}, "dw": {"market": 5.0, "inn": 0.8, "*": 0.3}, "p": {"close": true, "max": 6}},
	{"id": "market_opening", "tpl": "shutters", "w": 4.0, "cd": 300, "dur": [35, 45], "when": {"h": [6.5, 9.5], "need": ["shutters_down"]}, "bell": [[7.8, 0.9]],
		"mods": {"rest": 0.4}, "dw": {"market": 5.0, "*": 0.3}, "p": {"close": false, "max": 6}},
	{"id": "lamp_lighter", "tpl": "lamp", "w": 3.0, "cd": 330, "dur": [50, 70], "when": {"h": [17.0, 20.7]}, "bell": [[18.4, 1.0]],
		"mods": {"rain": 0.8, "monster": 0.7}, "dw": {"market": 2.0, "admin": 2.0, "inn": 2.0, "poor": 1.0, "military": 0.8, "craft": 1.0}, "p": {}},
	{"id": "gates_closing", "tpl": "gate", "w": 4.5, "cd": 380, "dur": [45, 60], "when": {"h": [20.0, 22.8], "kinds": ["town", "frontier_town", "castle"]}, "bell": [[21.2, 0.9]],
		"mods": {"monster": 1.8, "war": 1.5, "curfew": 1.3, "festival": 0.6}, "dw": {"military": 6.0, "*": 0.15}, "p": {"mode": "close", "dmax": 85.0, "latecomer": true}},
	{"id": "gates_opening", "tpl": "gate", "w": 4.5, "cd": 380, "dur": [40, 55], "when": {"h": [5.0, 7.2], "kinds": ["town", "frontier_town", "castle"]}, "bell": [[5.9, 0.8]],
		"mods": {"monster": 0.8}, "dw": {"military": 6.0, "*": 0.15}, "p": {"mode": "open", "dmax": 85.0}},
	{"id": "guard_shift_change", "tpl": "gate", "w": 3.0, "cd": 320, "dur": [45, 60], "when": {"h": [5.0, 19.5], "kinds": ["town", "frontier_town", "castle", "village"]}, "bell": [[6.0, 0.8], [18.0, 0.9]],
		"mods": {"war": 1.4, "monster": 1.3}, "dw": {"military": 5.0, "*": 0.25}, "p": {"mode": "shift", "dmax": 85.0}},
	{"id": "guard_questions_traveller", "tpl": "gate", "w": 1.3, "cd": 130, "dur": [40, 55], "when": {"h": [6, 22]},
		"mods": {"war": 1.8, "monster": 1.2, "curfew": 1.6, "crime": 1.6, "festival": 0.8}, "dw": {"military": 4.0, "inn": 1.2, "*": 0.3},
		"p": {"mode": "question", "dmax": 80.0, "traveller": "adventurer"}},
	{"id": "curfew_straggler", "tpl": "vignette", "w": 2.5, "cd": 110, "dur": [30, 45], "when": {"h": [20, 24], "need": ["curfew"]},
		"mods": {"crime": 1.6}, "dw": {"inn": 2.0, "poor": 1.6, "market": 1.4, "*": 1.0},
		"p": {"site": "street", "dmin": 6, "dmax": 45,
			"members": [{"role": "guard", "clips": ["Life_Guard_Attention", "Life_Talk_Emphatic", "Life_Social_Point_Directions"], "hold": [{"id": "spear", "hand": "r"}], "off": [-0.8, 0.0], "face": "centre", "say": ["guard_ask", 8.0]},
				{"role": "drunk", "clips": ["Life_Social_Shrug", "Life_Mocap_Shift_Weight", "Life_Social_Nod"], "off": [0.9, 0.2], "face": "centre"}]}},
	# ------------------------------------------------------------------ town life with a story
	{"id": "drunk_ejected", "tpl": "eject", "w": 1.4, "cd": 100, "dur": [30, 45], "when": {"h": [19, 1]},
		"mods": {"festival": 2.0, "rest": 1.5, "scarce": 0.4, "mourn": 0.3, "curfew": 0.1, "rain": 0.7}, "dw": {"inn": 5.0, "market": 0.5, "*": 0.1},
		"p": {"fight": false, "dmax": 55.0}},
	{"id": "tavern_brawl", "tpl": "eject", "w": 0.5, "cd": 240, "dur": [40, 55], "when": {"h": [20, 1]},
		"mods": {"festival": 1.6, "war": 1.4, "crime": 1.5, "scarce": 1.3, "mourn": 0.2, "curfew": 0.1}, "dw": {"inn": 5.0, "*": 0.1},
		"p": {"fight": true, "dmax": 55.0}},
	{"id": "funeral_procession", "tpl": "procession", "w": 0.5, "cd": 420, "dur": [70, 95], "when": {"h": [9, 17], "not": ["festival"]},
		"mods": {"mourn": 7.0, "plague": 4.0, "war": 1.4, "monster": 1.2, "rain": 0.8}, "dw": {"admin": 1.6, "poor": 1.5, "*": 0.8},
		"p": {"kind": "funeral", "mourners": 5}},
	{"id": "wedding_procession", "tpl": "procession", "w": 0.4, "cd": 500, "dur": [70, 95], "when": {"h": [10, 17.5], "rain": -1, "not": ["mourn", "monster"]},
		"mods": {"rest": 3.0, "festival": 3.0, "war": 0.3, "scarce": 0.3}, "dw": {"admin": 2.0, "market": 1.6, "*": 0.8},
		"p": {"kind": "wedding"}},
	{"id": "small_fire", "tpl": "fire", "w": 0.1, "cd": 300, "dur": [45, 65], "when": {"h": [6, 23]},
		"mods": {"fire": 60.0, "scarce": 1.2}, "dw": {"poor": 1.5, "craft": 1.4, "*": 1.0}, "p": {"n": 5}},
]
