"""Procedural faceted low-poly birds + rabbit, styled to sit next to the Quaternius animals.
Original work generated by this script -> CC0. Rigged (<= 12 bones) and animated.
blender -b --python make_small_animals.py -- <out_dir> [species ...]"""
import bpy, bmesh, sys, os, math, json, mathutils
from mathutils import Vector, Matrix
sys.path.insert(0, os.path.dirname(__file__))
import animlib as L

args = sys.argv[sys.argv.index("--") + 1:]
OUT = args[0]; ONLY = set(args[1:])
X, Y, Z = (1, 0, 0), (0, 1, 0), (0, 0, 1)
F = (0, -1, 0)  # forward

# ------------------------------------------------------------------ mesh parts
PARTS = []  # (obj, bone)

def _obj(bm, name, colour, bone):
    me = bpy.data.meshes.new(name); bm.to_mesh(me); bm.free()
    o = bpy.data.objects.new(name, me); bpy.context.scene.collection.objects.link(o)
    mat = bpy.data.materials.get(colour) or bpy.data.materials.new(colour)
    me.materials.append(mat)
    vg = o.vertex_groups.new(name=bone); vg.add([v.index for v in me.vertices], 1.0, "REPLACE")
    PARTS.append((o, bone)); return o

def blob(name, colour, bone, centre, size, rot=(0, 0, 0), seg=8, rings=6, taper=0.0, jitter=0.0, seed=1):
    """faceted ellipsoid; taper narrows the -Y (front) or +Y end: taper>0 narrows back end"""
    bm = bmesh.new()
    bmesh.ops.create_uvsphere(bm, u_segments=seg, v_segments=rings, radius=0.5)
    import random; r = random.Random(seed)
    for v in bm.verts:
        v.co.x *= size[0]; v.co.y *= size[1]; v.co.z *= size[2]
        if taper:
            k = 1 - taper * (v.co.y / max(size[1], 1e-6) + 0.5)
            v.co.x *= max(k, 0.2); v.co.z *= max(0.35 + 0.65 * k, 0.2)
        if jitter:
            v.co += Vector((r.uniform(-1, 1), r.uniform(-1, 1), r.uniform(-1, 1))) * jitter
    m = mathutils.Euler([math.radians(a) for a in rot]).to_matrix().to_4x4()
    bmesh.ops.transform(bm, matrix=Matrix.Translation(Vector(centre)) @ m, verts=bm.verts)
    return _obj(bm, name, colour, bone)

def cone(name, colour, bone, base, tip, r1, r2=0.0, sides=5, flat=1.0):
    bm = bmesh.new()
    d = Vector(tip) - Vector(base); ln = d.length
    bmesh.ops.create_cone(bm, cap_ends=True, cap_tris=False, segments=sides, radius1=r1, radius2=max(r2, 0.0005), depth=ln)
    for v in bm.verts: v.co.x *= flat; v.co.z += ln / 2
    q = Vector((0, 0, 1)).rotation_difference(d.normalized())
    bmesh.ops.transform(bm, matrix=Matrix.Translation(Vector(base)) @ q.to_matrix().to_4x4(), verts=bm.verts)
    return _obj(bm, name, colour, bone)

def plate(name, colour, bone, pts, thick=0.004):
    """flat polygon (list of 3D points) extruded slightly"""
    bm = bmesh.new()
    vs = [bm.verts.new(p) for p in pts]
    f = bm.faces.new(vs)
    ext = bmesh.ops.extrude_face_region(bm, geom=[f])
    nv = [e for e in ext["geom"] if isinstance(e, bmesh.types.BMVert)]
    f.normal_update()
    bmesh.ops.translate(bm, vec=f.normal * -thick, verts=nv)
    bmesh.ops.recalc_face_normals(bm, faces=bm.faces)
    return _obj(bm, name, colour, bone)

# ------------------------------------------------------------------ rig
def build_rig(bones):
    """bones: list of (name, head, tail, parent)"""
    ad = bpy.data.armatures.new("AnimalRig"); arm = bpy.data.objects.new("AnimalArmature", ad)
    bpy.context.scene.collection.objects.link(arm)
    bpy.context.view_layer.objects.active = arm
    bpy.ops.object.mode_set(mode="EDIT")
    eb = {}
    for n, h, t, p in bones:
        b = ad.edit_bones.new(n); b.head = h; b.tail = t
        if p: b.parent = eb[p]
        eb[n] = b
    bpy.ops.object.mode_set(mode="OBJECT")
    return arm

def assemble(arm):
    bpy.ops.object.select_all(action="DESELECT")
    for o, b in PARTS: o.select_set(True)
    bpy.context.view_layer.objects.active = PARTS[0][0]
    bpy.ops.object.join()
    obj = bpy.context.view_layer.objects.active; obj.name = "Body"
    # merge coincident verts inside the same part is not needed; keep faceted
    obj.parent = arm
    m = obj.modifiers.new("Armature", "ARMATURE"); m.object = arm
    PARTS.clear()
    return obj

# ------------------------------------------------------------------ birds
BIRDS = {
 # body len/wid/hei, body z, neck len, neck angle(deg from vertical fwd), head r, beak len, beak kind, leg len, colours
 "chicken":  dict(bl=0.30, bw=0.20, bh=0.22, bz=0.22, nl=0.09, na=25, hr=0.055, bk=0.035, beak="pointed", legz=0.13,
                  body="hen", wing="hen_dark", head="hen", tail="hen_dark", beakc="beak", leg="leg_yellow", comb="comb_red", tailk="hen", fly=False),
 "rooster":  dict(bl=0.32, bw=0.21, bh=0.24, bz=0.26, nl=0.12, na=18, hr=0.06, bk=0.038, beak="pointed", legz=0.16,
                  body="rooster_gold", wing="hen_dark", head="rooster_gold", tail="rooster_tail", beakc="beak", leg="leg_yellow", comb="comb_red", tailk="rooster", fly=False),
 "duck":     dict(bl=0.34, bw=0.20, bh=0.17, bz=0.15, nl=0.08, na=20, hr=0.055, bk=0.06, beak="flat", legz=0.07,
                  body="duck_brown", wing="duck_brown", head="duck_green", tail="duck_brown", beakc="duck_bill", leg="duck_bill", comb=None, tailk="short", fly=True),
 "goose":    dict(bl=0.50, bw=0.28, bh=0.26, bz=0.26, nl=0.30, na=12, hr=0.065, bk=0.07, beak="goose", legz=0.14,
                  body="goose", wing="goose_grey", head="goose", tail="goose_grey", beakc="goose_bill", leg="goose_bill", comb=None, tailk="short", fly=True),
 "pigeon":   dict(bl=0.22, bw=0.13, bh=0.13, bz=0.11, nl=0.05, na=20, hr=0.035, bk=0.018, beak="pointed", legz=0.05,
                  body="pigeon", wing="pigeon_dark", head="pigeon_neck", tail="pigeon_dark", beakc="face_dark", leg="pig_snout", comb=None, tailk="fan", fly=True),
 "crow":     dict(bl=0.30, bw=0.15, bh=0.15, bz=0.16, nl=0.06, na=25, hr=0.045, bk=0.05, beak="crow", legz=0.08,
                  body="crow", wing="crow_sheen", head="crow", tail="crow_sheen", beakc="black", leg="black", comb=None, tailk="fan", fly=True),
}

def make_bird(name, p):
    bl, bw, bh, bz = p["bl"], p["bw"], p["bh"], p["bz"]
    tilt = -12  # tail up
    blob("body", p["body"], "body", (0, 0.02 * bl, bz), (bw, bl, bh), rot=(tilt, 0, 0), seg=8, rings=6, taper=0.35, seed=len(name))
    # breast lighter / belly: small blob in front
    nb = Vector((0, -bl * 0.38, bz + bh * 0.25))
    ang = math.radians(p["na"])
    nt = nb + Vector((0, -math.sin(ang), math.cos(ang))) * p["nl"]
    cone("neck", p["head"] if p["nl"] > 0.1 else p["body"], "neck", nb - Vector((0, -0.01, 0.03)), nt, bw * 0.28, bw * 0.2, sides=6)
    hc = nt + Vector((0, -p["hr"] * 0.35, p["hr"] * 0.35))
    blob("head", p["head"], "head", hc, (p["hr"] * 1.8, p["hr"] * 2.2, p["hr"] * 1.9), seg=7, rings=5)
    # eyes
    for s in (-1, 1):
        blob("eye", "black", "head", hc + Vector((s * p["hr"] * 0.82, -p["hr"] * 0.35, p["hr"] * 0.25)), (p["hr"] * 0.28,) * 3, seg=4, rings=3)
    bb = hc + Vector((0, -p["hr"] * 0.95, -p["hr"] * 0.1))
    if p["beak"] == "flat":
        cone("beak", p["beakc"], "head", bb, bb + Vector((0, -p["bk"], -p["bk"] * 0.2)), p["hr"] * 0.45, p["hr"] * 0.3, sides=4, flat=1.6)
    elif p["beak"] == "goose":
        cone("beak", p["beakc"], "head", bb, bb + Vector((0, -p["bk"], -p["bk"] * 0.15)), p["hr"] * 0.45, p["hr"] * 0.2, sides=5, flat=1.2)
    elif p["beak"] == "crow":
        cone("beak", p["beakc"], "head", bb, bb + Vector((0, -p["bk"], -p["bk"] * 0.25)), p["hr"] * 0.42, 0, sides=4, flat=0.9)
    else:
        cone("beak", p["beakc"], "head", bb, bb + Vector((0, -p["bk"], -p["bk"] * 0.3)), p["hr"] * 0.32, 0, sides=4)
    if p["comb"]:
        big = 1.6 if name == "rooster" else 1.0
        top = hc + Vector((0, 0, p["hr"] * 0.85))
        plate("comb", p["comb"], "head", [top + Vector((0, p["hr"] * 0.6, -0.005)), top + Vector((0, p["hr"] * 0.35, p["hr"] * 0.55 * big)),
              top + Vector((0, 0, p["hr"] * 0.45 * big)), top + Vector((0, -p["hr"] * 0.3, p["hr"] * 0.6 * big)), top + Vector((0, -p["hr"] * 0.6, -0.005))], 0.012)
        wt = bb + Vector((0, 0.005, -p["hr"] * 0.35))
        plate("wattle", p["comb"], "head", [wt, wt + Vector((0, -p["hr"] * 0.2, -p["hr"] * 0.55 * big)), wt + Vector((0, p["hr"] * 0.3, -p["hr"] * 0.4 * big))], 0.012)
    # wings: folded plates on the flanks
    for s, side in ((-1, "R"), (1, "L")):
        w0 = Vector((s * bw * 0.46, -bl * 0.25, bz + bh * 0.22))
        blob("wing" + side, p["wing"], "wing." + side, w0 + Vector((s * 0.004, bl * 0.28, -bh * 0.05)),
             (bw * 0.16, bl * 0.72, bh * 0.55), rot=(tilt - 6, s * 8, 0), seg=6, rings=4, taper=0.55, seed=3)
    # tail
    tb = Vector((0, bl * 0.42, bz + bh * 0.12))
    if p["tailk"] == "rooster":
        for i, (dx, up) in enumerate(((-0.02, 0.9), (0.0, 1.1), (0.02, 0.8))):
            plate("tail%d" % i, p["tail"], "tail", [tb + Vector((dx, -0.02, -0.01)), tb + Vector((dx, 0.10, 0.10 * up + 0.08)),
                  tb + Vector((dx, 0.16, 0.06 * up + 0.02)), tb + Vector((dx, 0.07, -0.03))], 0.01)
    elif p["tailk"] == "hen":
        cone("tail", p["tail"], "tail", tb, tb + Vector((0, bl * 0.25, bh * 0.45)), bw * 0.28, bw * 0.08, sides=5, flat=0.5)
    elif p["tailk"] == "fan":
        plate("tail", p["tail"], "tail", [tb + Vector((-bw * 0.12, 0, 0)), tb + Vector((-bw * 0.22, bl * 0.45, -bh * 0.08)),
              tb + Vector((bw * 0.22, bl * 0.45, -bh * 0.08)), tb + Vector((bw * 0.12, 0, 0))], 0.008)
    else:
        cone("tail", p["tail"], "tail", tb, tb + Vector((0, bl * 0.2, bh * 0.18)), bw * 0.25, bw * 0.05, sides=5, flat=0.45)
    # legs + feet
    lz = p["legz"]
    for s, side in ((-1, "R"), (1, "L")):
        hip = Vector((s * bw * 0.2, bl * 0.02, lz + 0.01))
        foot = Vector((s * bw * 0.22, bl * 0.0, 0.004))
        cone("leg" + side, p["leg"], "leg." + side, foot, hip + Vector((0, 0, bh * 0.25)), max(0.006, bw * 0.045), max(0.005, bw * 0.04), sides=4)
        fl = max(0.03, bl * 0.18) if p["beak"] in ("flat", "goose") else max(0.025, bl * 0.14)
        if p["beak"] in ("flat", "goose"):
            plate("foot" + side, p["leg"], "leg." + side, [foot + Vector((-fl * 0.5, -fl, 0)), foot + Vector((fl * 0.5, -fl, 0)), foot + Vector((0, fl * 0.2, 0))], 0.006)
        else:
            for a in (-25, 0, 25):
                d = Vector((math.sin(math.radians(a)), -math.cos(math.radians(a)), 0)) * fl
                cone("toe", p["leg"], "leg." + side, foot, foot + d, 0.005, 0.002, sides=3)
    # rig
    neck_mid = nb
    arm = build_rig([
        ("root", (0, 0, 0), (0, 0, bz * 0.5), None),
        ("body", (0, bl * 0.1, bz), (0, -bl * 0.3, bz + bh * 0.1), "root"),
        ("neck", tuple(nb), tuple(nt), "body"),
        ("head", tuple(nt), tuple(hc + Vector((0, -p["hr"], 0))), "neck"),
        ("tail", tuple(tb), tuple(tb + Vector((0, bl * 0.25, bh * 0.2))), "body"),
        ("wing.L", (bw * 0.4, -bl * 0.2, bz + bh * 0.3), (bw * 0.45, bl * 0.35, bz + bh * 0.2), "body"),
        ("wing.R", (-bw * 0.4, -bl * 0.2, bz + bh * 0.3), (-bw * 0.45, bl * 0.35, bz + bh * 0.2), "body"),
        ("leg.L", (bw * 0.2, bl * 0.02, lz + bh * 0.2), (bw * 0.22, 0, 0.004), "body"),
        ("leg.R", (-bw * 0.2, bl * 0.02, lz + bh * 0.2), (-bw * 0.22, 0, 0.004), "body"),
    ])
    obj = assemble(arm)
    return arm, obj, dict(bz=bz, bh=bh, bl=bl, lz=lz)

def bird_anims(arm, d, fly, waddle):
    bz = d["bz"]
    # Idle: breathe + look around
    L.proc_action(arm, "Idle", [
        (1, {}, {}),
        (12, {"head": [(Z, 25)], "tail": [(X, -5)]}, {"body": (0, 0, 0.004)}),
        (24, {"head": [(Z, 25)]}, {}),
        (36, {"head": [(Z, -20)], "tail": [(X, 4)]}, {"body": (0, 0, 0.004)}),
        (48, {}, {})])
    # Walk / Run
    def gait(name, n, swing, bob, lean, head_bob, wings=0):
        ks = []
        for i in range(5):
            f = 1 + i * n / 4; ph = i / 4 * 2 * math.pi
            s = math.sin(ph)
            r = {"leg.L": [(X, swing * s)], "leg.R": [(X, -swing * s)],
                 "body": [(X, -lean)] + ([(Y, waddle * s)] if waddle else []),
                 "neck": [(X, head_bob * math.cos(ph * 2))], "head": [(X, -head_bob * 0.6 * math.cos(ph * 2))]}
            if wings: r["wing.L"] = [(Y, -wings)]; r["wing.R"] = [(Y, wings)]
            ks.append((f, r, {"body": (0, 0, bob * abs(math.cos(ph)))}))
        return L.proc_action(arm, name, ks)
    gait("Walk", 24, 28, bz * 0.03, 0, 10)
    gait("Run", 12, 45, bz * 0.06, 14, 6, wings=20)
    # Eat: peck twice
    down = {"neck": [(X, 55)], "head": [(X, 30)], "body": [(X, 12)], "tail": [(X, -10)]}
    L.proc_action(arm, "Eat", [(1, {}, {}), (8, down, {}), (12, {"neck": [(X, 25)], "head": [(X, 10)], "body": [(X, 8)]}, {}),
                               (16, down, {}), (24, {}, {}), (40, {"head": [(Z, 15)]}, {}), (48, {}, {})])
    # Death
    dead = {"root": [(Y, 90)], "neck": [(X, -40), (Z, 20)], "leg.L": [(X, -30)], "leg.R": [(X, 30)], "wing.L": [(Y, -40)]}
    L.proc_action(arm, "Death", [(1, {}, {}), (6, {"wing.L": [(Y, -60)], "wing.R": [(Y, 60)], "body": [(X, -15)]}, {"root": (0, 0, bz * 0.2)}),
                                 (16, dead, {"root": (0, 0, -bz * 0.35)}), (30, dead, {"root": (0, 0, -bz * 0.35)})])
    # Fly (flap) for flying birds; flightless chickens get a short flutter
    if fly:
        tuck = {"leg.L": [(X, -70)], "leg.R": [(X, -70)], "body": [(X, 0)]}
        up = dict(tuck); up.update({"wing.L": [(Y, -80)], "wing.R": [(Y, 80)], "tail": [(X, -5)]})
        dn = dict(tuck); dn.update({"wing.L": [(Y, 25)], "wing.R": [(Y, -25)], "tail": [(X, 5)]})
        L.proc_action(arm, "Fly", [(1, up, {"root": (0, 0, bz)}), (7, dn, {"root": (0, 0, bz * 0.9)}), (13, up, {"root": (0, 0, bz)})])
        L.proc_action(arm, "Glide", [(1, {"leg.L": [(X, -70)], "leg.R": [(X, -70)], "wing.L": [(Y, -75)], "wing.R": [(Y, 75)]}, {"root": (0, 0, bz)}),
                                     (24, {"leg.L": [(X, -70)], "leg.R": [(X, -70)], "wing.L": [(Y, -70)], "wing.R": [(Y, 70)]}, {"root": (0, 0, bz * 1.05)}),
                                     (48, {"leg.L": [(X, -70)], "leg.R": [(X, -70)], "wing.L": [(Y, -75)], "wing.R": [(Y, 75)]}, {"root": (0, 0, bz)})])
    else:
        up = {"wing.L": [(Y, -75)], "wing.R": [(Y, 75)], "neck": [(X, -15)]}
        L.proc_action(arm, "Flutter", [(1, {}, {}), (4, up, {"root": (0, 0, 0.05)}), (7, {"wing.L": [(Y, -10)], "wing.R": [(Y, 10)]}, {"root": (0, 0, 0.1)}),
                                       (10, up, {"root": (0, 0, 0.08)}), (16, {}, {})])

# ------------------------------------------------------------------ rabbit
def make_rabbit(body="rabbit", light="rabbit_lt"):
    bl, bw, bh, bz = 0.26, 0.15, 0.15, 0.095
    blob("body", body, "body", (0, 0.03, bz), (bw, bl, bh), rot=(-8, 0, 0), seg=8, rings=6, taper=-0.25, seed=5)
    blob("belly", light, "body", (0, -0.03, bz - 0.035), (bw * 0.7, bl * 0.6, bh * 0.45), seg=6, rings=4)
    hc = Vector((0, -bl * 0.45, bz + bh * 0.45))
    blob("head", body, "head", hc, (0.075, 0.095, 0.075), rot=(15, 0, 0), seg=7, rings=5, seed=2)
    blob("muzzle", light, "head", hc + Vector((0, -0.04, -0.015)), (0.04, 0.03, 0.03), seg=5, rings=3)
    blob("nose", "pink_ear", "head", hc + Vector((0, -0.055, -0.004)), (0.012, 0.01, 0.01), seg=4, rings=3)
    for s in (-1, 1):
        blob("eye", "black", "head", hc + Vector((s * 0.033, -0.022, 0.012)), (0.014, 0.014, 0.016), seg=4, rings=3)
        side = "L" if s > 0 else "R"
        eb = hc + Vector((s * 0.018, 0.012, 0.03))
        blob("ear" + side, body, "ear." + side, eb + Vector((s * 0.008, 0.012, 0.055)), (0.028, 0.012, 0.11), rot=(-15, s * 12, 0), seg=5, rings=4)
        blob("earin" + side, "pink_ear", "ear." + side, eb + Vector((s * 0.008, 0.006, 0.058)), (0.016, 0.006, 0.08), rot=(-15, s * 12, 0), seg=4, rings=3)
        # front legs
        blob("fleg" + side, body, "fleg." + side, (s * 0.038, -bl * 0.33, 0.04), (0.03, 0.034, 0.085), seg=5, rings=4)
        # hind legs: haunch + long foot
        blob("haunch" + side, body, "hleg." + side, (s * 0.058, bl * 0.24, 0.07), (0.055, 0.12, 0.105), rot=(-15, 0, 0), seg=6, rings=4)
        blob("hfoot" + side, body, "hleg." + side, (s * 0.058, bl * 0.14, 0.014), (0.032, 0.11, 0.028), seg=5, rings=3)
    blob("tail", "white", "tail", (0, bl * 0.55, bz + 0.03), (0.045, 0.04, 0.045), seg=5, rings=4)
    arm = build_rig([
        ("root", (0, 0, 0), (0, 0, 0.06), None),
        ("body", (0, bl * 0.3, bz), (0, -bl * 0.3, bz + 0.02), "root"),
        ("head", tuple(hc + Vector((0, 0.03, -0.03))), tuple(hc + Vector((0, -0.07, 0))), "body"),
        ("ear.L", (0.02, hc.y + 0.012, hc.z + 0.03), (0.03, hc.y + 0.03, hc.z + 0.15), "head"),
        ("ear.R", (-0.02, hc.y + 0.012, hc.z + 0.03), (-0.03, hc.y + 0.03, hc.z + 0.15), "head"),
        ("fleg.L", (0.04, -bl * 0.3, bz - 0.02), (0.04, -bl * 0.32, 0.0), "body"),
        ("fleg.R", (-0.04, -bl * 0.3, bz - 0.02), (-0.04, -bl * 0.32, 0.0), "body"),
        ("hleg.L", (0.058, bl * 0.28, 0.08), (0.058, bl * 0.1, 0.01), "body"),
        ("hleg.R", (-0.058, bl * 0.28, 0.08), (-0.058, bl * 0.1, 0.01), "body"),
        ("tail", (0, bl * 0.5, bz + 0.02), (0, bl * 0.62, bz + 0.05), "body"),
    ])
    obj = assemble(arm)
    return arm, obj, dict(bz=bz)

def rabbit_anims(arm, d):
    bz = d["bz"]
    L.proc_action(arm, "Idle", [(1, {}, {}), (8, {"head": [(X, 4)], "ear.L": [(X, -8)]}, {}), (12, {"head": [(X, -3)]}, {}),
                                (24, {"ear.R": [(Y, 10)], "head": [(Z, 12)]}, {}), (36, {"head": [(Z, 12)]}, {}), (48, {}, {})])
    def hop(name, n, h, stretch):
        crouch = {"hleg.L": [(X, 10)], "hleg.R": [(X, 10)], "fleg.L": [(X, -10)], "fleg.R": [(X, -10)], "body": [(X, 6)]}
        air = {"hleg.L": [(X, -stretch)], "hleg.R": [(X, -stretch)], "fleg.L": [(X, stretch * 0.8)], "fleg.R": [(X, stretch * 0.8)],
               "body": [(X, -10)], "ear.L": [(X, -15)], "ear.R": [(X, -15)]}
        land = {"hleg.L": [(X, 25)], "hleg.R": [(X, 25)], "fleg.L": [(X, -20)], "fleg.R": [(X, -20)], "body": [(X, 10)]}
        return L.proc_action(arm, name, [(1, crouch, {}), (1 + n * 0.3, air, {"root": (0, 0, h)}), (1 + n * 0.65, land, {"root": (0, 0, h * 0.2)}), (1 + n, crouch, {})])
    hop("Walk", 20, bz * 0.35, 30)
    hop("Run", 12, bz * 0.9, 55)
    down = {"head": [(X, 40)], "body": [(X, 12)], "fleg.L": [(X, 10)], "fleg.R": [(X, 10)]}
    ks = [(1, {}, {}), (8, down, {})]
    for i, f in enumerate(range(12, 40, 4)):
        dd = dict(down); dd["head"] = [(X, 40 + (5 if i % 2 else 0))]; ks.append((f, dd, {}))
    ks += [(42, down, {}), (48, {}, {})]
    L.proc_action(arm, "Eat", ks)
    dead = {"root": [(Y, 90)], "hleg.L": [(X, -30)], "hleg.R": [(X, -40)], "ear.L": [(X, 40)], "ear.R": [(X, 30)], "head": [(X, -15)]}
    L.proc_action(arm, "Death", [(1, {}, {}), (10, dead, {"root": (0, 0, -bz * 0.25)}), (30, dead, {"root": (0, 0, -bz * 0.25)})])

# ------------------------------------------------------------------ main
report = {}
def finish(name, arm, obj):
    for pb in arm.pose.bones: pb.rotation_mode = "QUATERNION"
    cmap = {m.name: m.name for m in bpy.data.materials if m.name in L.PAL.NAMES}
    L.paint(obj, cmap)
    L.clear_nla(arm)
    st = L.stats(arm)
    out = os.path.join(OUT, name + ".glb")
    L.export_glb(out, arm)
    mn, mx = L.rest_bounds(arm, [obj]); st["size_m"] = [round(v, 2) for v in (mx - mn)]
    st["kb"] = round(os.path.getsize(out) / 1024)
    report[name] = st; print("BUILT", name, json.dumps(st))

for name, p in BIRDS.items():
    if ONLY and name not in ONLY: continue
    L.reset(); PARTS.clear()
    arm, obj, d = make_bird(name, p)
    bird_anims(arm, d, p["fly"], waddle=6 if p["beak"] in ("flat", "goose") else 0)
    finish(name, arm, obj)
for name, cols in (("rabbit", ("rabbit", "rabbit_lt")),):
    if ONLY and name not in ONLY: continue
    L.reset(); PARTS.clear()
    arm, obj, d = make_rabbit(*cols)
    rabbit_anims(arm, d)
    finish(name, arm, obj)
p = os.path.join(OUT, "_build_small.json")
old = json.load(open(p)) if os.path.exists(p) else {}
old.update(report); json.dump(old, open(p, "w"), indent=1)
