extends RefCounted
## Per-settlement VISUAL IDENTITY profile (docs/design/VERTICAL_SLICE.md: "you should recognise a settlement without
## reading its name": architecture, clothing, industries, food, guards, street activity). Preload; no class_name.
##
## data/world/town_identity.json (generated by tools/town_identity/gen_town_identity.py) holds visual archetypes (which map to
## the realm identities of scripts/realm/settlements.gd), named dressing kits, palettes and one entry per town. profile(s)
## merges archetype defaults, the town's own overrides, its culture (data/world/cultures.json clothing palette), the
## terrain sensed from WorldGen (relief, forest) and its size class. Everything is deterministic and cached per town.
##
## Who reads it (each a few lines):
##   CityPlanner.plan / _zone_districts   layout shape (rings, lanes, plaza, density, corridors) and house roof-mix restyle
##   SettlementBuilder._build             per-lot instance colour (palette tint, shabbiness: NO new draw calls), wall style,
##                                        banner / bunting / awning colours, outskirts yards (town_identity_view.gd)
##   DistrictProps                        kit dressing specs added to the district prop sets, prop multipliers
##   micro_events.gd                      street-activity bias (activity_bias), busy factor
##   villager.gd                          clothing palette bias per culture/town, guard uniform tint
##   world_sim.gd                         guard density per town (adjust_job)
## The signature report (tools_qa/town_identity/signature_report.gd) lists every town's profile and a pairwise distinctness.
##
## Limits (honest): roof TYPE is expressed by which shared house meshes a town uses (the roof colour is baked into each house
## atlas: thatch house_1/5/9, shingle 2/6/10/13/4, slate 3/7/11/12/16, red tile 8/14/15) and the palette tints the whole
## instance, not just the plaster. No settlement of the 30 has a river or coast within ~330 m (the generator keeps towns
## off the water), so "river" and "port" towns get a dry boatyard; a real quay and pier are built only where water is near.

const HouseDetails := preload("res://scripts/world/house_details.gd")
const GEN := "res://assets/generated/"
const DATA_PATH := "res://data/world/town_identity.json"
const CULTURES_PATH := "res://data/world/cultures.json"

const ROOF_GROUPS := {
	"thatch": ["house_1", "house_5", "house_9", "mhouse_peasant_a"],
	"shingle": ["house_2", "house_6", "house_10", "house_13", "house_4"],
	"slate": ["house_3", "house_7", "house_11", "house_12", "house_16", "mhouse_peasant_b", "mhouse_trader"],
	"red": ["house_8", "house_14", "house_15", "mhouse_family"],
	"tall": ["house_town_a", "house_town_b", "house_town_c", "house_town_d"],
}
const ROOF_KINDS := ["thatch", "shingle", "slate", "red", "tall"]
const WALL_STYLES := ["stone", "low", "palisade", "hedge", "runestones", "none"]
const LAYOUT_KINDS := ["royal", "radial", "terraced", "strung", "loose", "green", "close", "bank", "lanes", "campus", "hold", "v_green", "v_linear", "v_cluster", "v_cross"]
## Village / hamlet signature vocabulary: three (hamlets: two) of these features and one street pattern per place, never the same set twice.
const VILLAGE_FEATURES := ["green", "chapel", "mill", "smithy", "jetty", "orchard", "fieldring", "pond", "maypole"]
const VILLAGE_STREETS := ["green", "linear", "cluster", "crossroads"]
const STREET_LAYOUTS := {"green": "v_green", "linear": "v_linear", "cluster": "v_cluster", "crossroads": "v_cross"}
const VF_ARCH := {
	"green": {"farming": 2, "pastoral": 3, "religious": 2, "scholarly": 1, "merchant": 1},
	"chapel": {"religious": 4, "scholarly": 2, "farming": 1, "pastoral": 1, "fishing": 1, "hunting": 1},
	"mill": {"farming": 3, "craft": 2, "pastoral": 1, "merchant": 1},
	"smithy": {"mining": 3, "fortress": 3, "craft": 3, "criminal": 1, "merchant": 1, "hunting": 1},
	"jetty": {"fishing": 4, "merchant": 1},
	"orchard": {"farming": 2, "religious": 3, "pastoral": 1, "scholarly": 1},
	"fieldring": {"farming": 3, "pastoral": 2},
	"pond": {"pastoral": 2, "farming": 1, "religious": 1, "scholarly": 1},
	"maypole": {"farming": 2, "pastoral": 2, "religious": 1, "merchant": 1}}
const VF_TERRAIN := {"jetty": {"mere": 3, "river": 3, "coast": 3, "marsh": 2}, "pond": {"mere": 2, "marsh": 2, "stream": 2, "river": 1},
	"mill": {"stream": 2, "river": 1, "hill": 1}, "orchard": {"hill": 1}, "chapel": {"hill": 1}, "fieldring": {"hill": -2, "forest": -2}, "green": {"hill": -1}, "maypole": {"forest": 1}}
const ARCH_KINDS := ["royal", "merchant", "craft", "farming", "pastoral", "mining", "fortress", "hunting", "religious", "scholarly", "criminal", "fishing"]
const SIZE_CLASSES := ["hamlet", "village", "frontier", "town", "castle"]

## Layout shapes (CityPlanner.plan reads these). rings: ring street radii as fractions of the town radius ([] = none),
## lanes / lanes_mul: radial lane count, plaza: plaza radius multiplier, density: share of lots kept, compact: lots stay
## inside this fraction of the radius, narrow: street width multiplier (back alleys), corridor/ellipse: lot windows
## (strung and bank towns follow their gate roads), temple_centre / academy: a landmark at the heart.
const LAYOUTS := {
	"royal": {},
	"radial": {"rings": [0.40, 0.70], "lanes_mul": 1.5, "plaza": 1.3},
	"terraced": {"rings": [0.30, 0.52, 0.74], "lanes_mul": 1.0, "plaza": 0.9, "compact": 0.93},
	"strung": {"rings": [0.5], "lanes": 5, "plaza": 1.0, "ellipse": 0.40, "corridor": 0.22},
	"loose": {"rings": [0.55], "lanes_mul": 0.6, "plaza": 1.1, "density": 0.62},
	"green": {"rings": [0.5], "lanes_mul": 0.9, "plaza": 1.45, "density": 0.88},
	"close": {"rings": [0.5], "lanes_mul": 1.0, "plaza": 1.55, "density": 0.95, "temple_centre": true},
	"bank": {"rings": [0.5], "lanes": 5, "plaza": 1.0, "ellipse": 0.5, "corridor": 0.2, "one_sided": true},
	"lanes": {"rings": [0.40, 0.68], "lanes_mul": 2.1, "plaza": 0.8, "narrow": 0.7},
	"campus": {"rings": [0.5], "lanes_mul": 1.0, "plaza": 1.35, "density": 0.95, "academy": true},
	"hold": {"rings": [0.5], "lanes_mul": 0.8, "plaza": 0.9, "density": 0.92, "compact": 0.9},
	# Village street patterns (the generic "loose" villages are re-cut into one of these; see village_sig).
	"v_green": {"rings": [0.5], "lanes_mul": 0.6, "plaza": 1.7, "density": 0.62},
	"v_linear": {"rings": [], "lanes": 2, "plaza": 0.85, "ellipse": 0.3, "corridor": 0.2, "density": 0.8},
	"v_cluster": {"rings": [0.4], "lanes_mul": 0.6, "plaza": 0.8, "density": 0.7, "compact": 0.7},
	"v_cross": {"rings": [], "lanes": 2, "plaza": 0.85, "ellipse": 0.12, "corridor": 0.26, "density": 0.8},
}

## QA switch (signature report --legacy): every town gets the unchanged original layout and look, for before / after numbers.
const VILLAGE_THRESHOLD := 0.25
static var legacy_all := false
static var _data: Dictionary = {}
static var _cultures: Dictionary = {}
static var _cache: Dictionary = {}
static var _mesh_cache: Dictionary = {}
static var _mat_cache: Dictionary = {}
static var _bias_cache: Dictionary = {}
static var _roof_of: Dictionary = {}
static var _fit_cache: Dictionary = {}
static var _vsig_cache: Dictionary = {}
static var _vsig_key := ""


# ================================================================ data
static func data() -> Dictionary:
	if _data.is_empty():
		var f := FileAccess.open(DATA_PATH, FileAccess.READ)
		if f != null:
			var j: Variant = JSON.parse_string(f.get_as_text())
			if j is Dictionary:
				_data = j
	return _data


static func culture_data(id: String) -> Dictionary:
	if _cultures.is_empty():
		var f := FileAccess.open(CULTURES_PATH, FileAccess.READ)
		if f != null:
			var j: Variant = JSON.parse_string(f.get_as_text())
			if j is Dictionary:
				for c: Dictionary in j.get("cultures", []):
					_cultures[String(c["id"])] = c
	return _cultures.get(id, {})


## Forget cached profiles (a new world seed moves the towns).
static func reset() -> void:
	_vsig_cache.clear()
	_vsig_key = ""
	_cache.clear()
	_bias_cache.clear()


static func roof_of(asset: String) -> String:
	if _roof_of.is_empty():
		for g: String in ROOF_GROUPS:
			for a: String in ROOF_GROUPS[g]:
				_roof_of[a] = g
	return String(_roof_of.get(asset, ""))


static func _color(v: Variant, fallback := Color.WHITE) -> Color:
	return Color.html(String(v)) if v is String and String(v) != "" else fallback


static func size_class(s: Dictionary) -> String:
	var pop := int(s.get("population", 200))
	match String(s.get("kind", "village")):
		"castle":
			return "castle"
		"frontier_town":
			return "frontier"
		"town":
			return "town"
	return "hamlet" if pop <= 120 else "village"


## Terrain read from WorldGen (relief and forest around the town). Safe before WorldGen.setup (returns plain).
static func sense(s: Dictionary) -> Dictionary:
	var out := {"relief": 0.0, "forest": 0.0}
	if WorldGen.settlements.is_empty() or not s.has("pos"):
		return out
	var c: Vector2 = s["pos"]
	var lo := 1.0e9
	var hi := -1.0e9
	var f := 0.0
	for k in 16:
		var a := TAU * k / 16.0
		var q := c + Vector2(cos(a), sin(a)) * 260.0
		var h := WorldGen.height(q.x, q.y)
		lo = minf(lo, h)
		hi = maxf(hi, h)
		f += WorldGen.forest_density(q.x, q.y, false)
	out["relief"] = hi - lo
	out["forest"] = f / 16.0
	return out


## Nearest river / lake to a town (rivers and the lake exist only after WorldGen.setup built the water, so this is a LIVE query for
## the builder, never part of the cached profile): {dist, dir, point}. dist = INF when nothing is known.
static func water_info(s: Dictionary) -> Dictionary:
	var out := {"dist": INF, "dir": Vector2.ZERO, "point": Vector2.ZERO}
	if not s.has("pos"):
		return out
	var c: Vector2 = s["pos"]
	var best := INF
	var bp := c
	for r: Dictionary in WorldGen.rivers:
		for p: Vector2 in (r["points"] as PackedVector2Array):
			var d := c.distance_to(p)
			if d < best:
				best = d
				bp = p
	if WorldGen.lake_center.x < 1.0e5:
		var ld := c.distance_to(WorldGen.lake_center) - WorldGen.lake_radius
		if ld < best:
			best = ld
			bp = WorldGen.lake_center
	out["dist"] = best
	if best < INF:
		out["dir"] = (bp - c).normalized()
		out["point"] = bp
	return out


# ================================================================ profile
static func profile(s: Dictionary) -> Dictionary:
	var pos: Vector2 = s.get("pos", Vector2.ZERO)
	var key := "%s|%d|%d,%d" % [String(s.get("name", "")), int(s.get("id", 0)), roundi(pos.x), roundi(pos.y)]
	if _cache.has(key):
		return _cache[key]
	var p := _make(s)
	_cache[key] = p
	return p


static func of_id(sid: int) -> Dictionary:
	if sid < 0 or sid >= WorldGen.settlements.size():
		return {}
	return profile(WorldGen.settlements[sid])


static func _auto_entry(s: Dictionary) -> Dictionary:
	# A settlement the data does not know (other seeds' extras, hidden places): archetype by kind, picked by a stable hash.
	var h := absi(hash([int(s.get("id", 0)), String(s.get("name", ""))]))
	var pools := {"village": ["farming", "pastoral", "hunting", "fishing", "craft", "mining"], "hamlet": ["farming", "pastoral", "fishing", "hunting"],
		"town": ["merchant", "craft", "fortress", "scholarly", "religious"], "frontier": ["fortress", "hunting", "criminal"], "castle": ["royal"]}
	var pool: Array = pools.get(size_class(s), pools["village"])
	return {"arch": pool[h % pool.size()], "culture": "caldric", "auto": true}


static func _make(s: Dictionary) -> Dictionary:
	var d := data()
	var towns: Dictionary = d.get("towns", {})
	var e: Dictionary = towns.get(String(s.get("name", "")), {})
	if legacy_all:
		e = {"arch": "royal", "culture": "caldric"}
	elif e.is_empty():
		e = _auto_entry(s)
	var arch_id := String(e.get("arch", "farming"))
	var arch: Dictionary = (d.get("archetypes", {}) as Dictionary).get(arch_id, {})
	var sz := size_class(s)
	var sn := sense(s)
	var p := {"id": int(s.get("id", 0)), "name": String(s.get("name", "")), "arch": arch_id, "realm": String(e.get("realm", arch.get("realm", "farming"))),
		"flavour": String(e.get("flavour", "")), "size": sz, "kind": String(s.get("kind", "village")), "legacy": arch_id == "royal"}
	# --- culture: clothing palette from cultures.json (plus a minority influence)
	var culture := String(e.get("culture", "caldric"))
	var influence := String(e.get("influence", ""))
	p["culture"] = culture
	p["influence"] = influence
	var cloth: Array[Color] = []
	for h: String in arch.get("cloth", []):
		cloth.append(_color(h))
	for cid: String in [culture, influence]:
		if cid == "":
			continue
		var cd := culture_data(cid)
		var pal: Array = cd.get("clothing_palette", [])
		for i in mini(pal.size(), 3 if cid == culture else 2):
			cloth.append(_color((pal[i] as Dictionary).get("hex", "")))
	p["cloth"] = cloth
	# --- architecture
	var pal_id := String(e.get("palette", arch.get("palette", "neutral")))
	var pals: Dictionary = d.get("palettes", {})
	p["palette"] = pal_id
	p["tint"] = _color((pals.get(pal_id, {}) as Dictionary).get("tint", "#FFFFFF"))
	p["shabby"] = float(e.get("shabby", arch.get("shabby", 0.0)))
	var roof: Dictionary = e.get("roof", arch.get("roof", {"shingle": 1.0}))
	p["roof"] = roof
	var rbest := ""
	var rw := -1.0
	for k: String in ROOF_KINDS:
		if float(roof.get(k, 0.0)) > rw:
			rw = float(roof.get(k, 0.0))
			rbest = k
	p["roof_main"] = rbest
	p["wall"] = String(e.get("wall", arch.get("wall", "none")))
	p["tower"] = float(e.get("tower", arch.get("tower", 1.0)))
	p["stone"] = float(e.get("stone", arch.get("stone", 0.4)))
	var layout := String(e.get("layout", arch.get("layout", "loose")))
	var vsig := village_sig(s) if (sz == "village" or sz == "hamlet") and arch_id != "royal" and not legacy_all else {}
	if not vsig.is_empty() and layout == "loose":
		layout = String(STREET_LAYOUTS[vsig["street"]])
	p["vsig"] = vsig
	p["layout"] = layout
	var lay: Dictionary = (LAYOUTS.get(layout, {}) as Dictionary).duplicate(true)
	# Very small places keep a plain spacing: no ring street fits a 42 m hamlet's lots anyway.
	if sz == "hamlet" and lay.has("rings") and (lay["rings"] as Array).size() > 1:
		lay["rings"] = [lay["rings"][0]]
	p["lay"] = lay
	p["stalls"] = float(e.get("stalls", arch.get("stalls", 1.0)))
	p["lamps"] = float(e.get("lamps", arch.get("lamps", 1.0)))
	p["guards"] = float(e.get("guards", arch.get("guards", 1.0)))
	p["busy"] = float(e.get("busy", {"merchant": 1.25, "craft": 1.1, "royal": 1.0, "religious": 0.9, "farming": 0.85, "pastoral": 0.85, "criminal": 0.85, "fortress": 1.0}.get(arch_id, 1.0)))
	# --- colour language
	var bn: Array = e.get("banner", arch.get("banner", ["#B3202A", "#E6B93A"]))
	p["banner"] = [_color(bn[0]), _color(bn[1])]
	var aw: Array = e.get("awning", arch.get("awning", ["#C2301F", "#F2E8CC"]))
	p["awning"] = [_color(aw[0]), _color(aw[1])]
	p["guard"] = _color(e.get("guard", arch.get("guard", "#B3202A")))
	# --- kits, dressing, activity
	var kits: Array = []
	for k: String in arch.get("kits", []):
		kits.append(k)
	for k: String in e.get("kits", []):
		if not kits.has(k):
			kits.append(k)
	p["kits"] = kits
	var dress: Array = []
	var yards: Array = []
	var kd: Dictionary = d.get("kits", {})
	for k: String in kits:
		var kit: Dictionary = kd.get(k, {})
		for sp: Dictionary in kit.get("dress", []):
			dress.append(sp)
		for y: Dictionary in kit.get("yards", []):
			yards.append(y)
	p["dress"] = dress
	p["yards"] = yards
	p["prop_mult"] = arch.get("prop_mult", {})
	var act: Dictionary = (arch.get("activity", {}) as Dictionary).duplicate()
	for g: String in (e.get("activity", {}) as Dictionary):
		act[g] = e["activity"][g]
	p["activity"] = act
	# --- terrain tags: sensed + hand hints (coast, mere, marsh ...)
	var tags: Array = []
	if float(sn["relief"]) >= 105.0:
		tags.append("hill")
	if float(sn["forest"]) >= 0.37:
		tags.append("forest")
	for t: String in e.get("terrain", []):
		if not tags.has(t):
			tags.append(t)
	for t: String in e.get("hint", []):
		if not tags.has(t):
			tags.append(t)
	p["terrain"] = tags
	p["relief"] = sn["relief"]
	p["forest"] = sn["forest"]
	return p


# ================================================================ layout (CityPlanner)
## The road axis of a town: the line between the two gates that are furthest apart (a lone gate: its own direction).
static func main_axis(gates: Array) -> Vector2:
	var best := -1.0
	var out := Vector2.RIGHT
	for i in gates.size():
		var a := Vector2(cos(float(gates[i])), sin(float(gates[i])))
		if i == 0:
			out = a
		for j in range(i + 1, gates.size()):
			var b := Vector2(cos(float(gates[j])), sin(float(gates[j])))
			var sep := (a - b).length()
			if sep > best:
				best = sep
				out = (a - b) / maxf(sep, 0.001)
	return out


## Context for keep_lot: the road axis, the gate roads and (for one-sided "bank" towns) the open water side.
static func layout_context(prof: Dictionary, c: Vector2, r: float, gates: Array) -> Dictionary:
	var axis := main_axis(gates)
	var ctx := {"c": c, "r": r, "axis": axis, "gates": gates, "lay": prof["lay"], "id": int(prof["id"]), "side": 1.0}
	if bool((prof["lay"] as Dictionary).get("one_sided", false)):
		var n := Vector2(-axis.y, axis.x)
		# Water is not known when towns are planned: the open (quay / boatyard) side is the downhill one, lots take the high side.
		var h1 := WorldGen.height((c + n * r * 0.9).x, (c + n * r * 0.9).y)
		var h2 := WorldGen.height((c - n * r * 0.9).x, (c - n * r * 0.9).y)
		ctx["side"] = 1.0 if h1 > h2 else -1.0
	return ctx


## How many homes a town of this size must keep after its layout shape thinned it (see CityPlanner.plan: the shape is relaxed until met).
static func min_lots(prof: Dictionary) -> int:
	match String(prof.get("size", "village")):
		"hamlet":
			return 9
		"village":
			return 20
		"frontier":
			return 34
		"town":
			return 66
	return 0


## The layout context with its shape loosened by `step` (1..4): wider windows, denser lots.
static func relaxed(ctx: Dictionary, step: int) -> Dictionary:
	var out := ctx.duplicate()
	var lay: Dictionary = (ctx["lay"] as Dictionary).duplicate()
	var f := 1.0 + 0.25 * step
	for k: String in ["ellipse", "corridor"]:
		if lay.has(k):
			lay[k] = float(lay[k]) * f
	if lay.has("density"):
		lay["density"] = minf(1.0, float(lay["density"]) + 0.12 * step)
	if lay.has("compact"):
		lay["compact"] = minf(1.0, float(lay["compact"]) + 0.03 * step)
	out["lay"] = lay
	return out


static func keep_lot(ctx: Dictionary, p: Vector2) -> bool:
	var lay: Dictionary = ctx["lay"]
	if lay.is_empty():
		return true
	var c: Vector2 = ctx["c"]
	var r: float = ctx["r"]
	if lay.has("compact") and p.distance_to(c) > r * float(lay["compact"]):
		return false
	if lay.has("ellipse"):
		var axis: Vector2 = ctx["axis"]
		var v := p - c
		var along := v.dot(axis)
		var lat := v.dot(Vector2(-axis.y, axis.x))
		var in_ellipse := absf(lat) <= r * float(lay["ellipse"]) * sqrt(maxf(0.0, 1.0 - pow(minf(absf(along) / (r * 1.02), 1.0), 4.0)))
		if bool(lay.get("one_sided", false)):
			var side: float = ctx["side"]
			in_ellipse = in_ellipse and lat * side >= -r * 0.14
		var in_corridor := false
		var cw := r * float(lay.get("corridor", 0.2))
		for g in ctx["gates"]:
			var dg := Vector2(cos(float(g)), sin(float(g)))
			var q := Geometry2D.get_closest_point_to_segment(p, c, c + dg * r * 1.05)
			if p.distance_to(q) <= cw:
				in_corridor = true
				break
		if not (in_ellipse or in_corridor):
			return false
	var dens := float(lay.get("density", 1.0))
	if dens < 1.0:
		var h := absi(hash([int(ctx["id"]), roundi(p.x * 3.0), roundi(p.y * 3.0)]))
		if float(h % 1000) / 1000.0 >= dens:
			return false
	return true


# ================================================================ architecture (CityPlanner._zone_districts, builder)
static func _is_plain_house(asset: String) -> bool:
	return (asset.begins_with("house_") or asset in ["mhouse_peasant_a", "mhouse_peasant_b", "mhouse_family", "mhouse_trader"])


## Re-draw every plain house of a planned town from the profile's roof mix (the building-variant weights): a thatch hamlet,
## a slate-and-tall-townhouse guild town, a shingle-and-palisade hunters' hold. Own RNG stream; special lots keep their asset.
## `fits_cb(asset, pos, yaw) -> bool` is CityPlanner's footprint test.
static func restyle_lots(plan: Dictionary, prof: Dictionary, seed_value: int, fits_cb: Callable) -> int:
	if bool(prof.get("legacy", false)):
		return 0
	var rng := RandomNumberGenerator.new()
	rng.seed = hash([seed_value, int(prof["id"]), "restyle"])
	var mix: Dictionary = prof["roof"]
	var changed := 0
	for lot: Dictionary in plan["lots"]:
		var asset := String(lot["asset"])
		if not _is_plain_house(asset) or String(lot.get("role", "")) != "":
			continue
		var dk := String(lot.get("district", ""))
		var roll := rng.randf()
		var keep_old := roll < 0.08
		var weights := {}
		var total := 0.0
		for g: String in ROOF_KINDS:
			var w := float(mix.get(g, 0.0))
			if w <= 0.0:
				continue
			match dk:
				"poor":
					w *= 1.5 if g == "thatch" else (0.12 if g == "tall" else 1.0)
				"market", "admin":
					w *= 1.7 if g == "tall" else (0.6 if g == "thatch" else 1.0)
				"military":
					w *= 0.4 if g == "thatch" else 1.0
				"craft":
					w *= 0.7 if g == "tall" else 1.0
			weights[g] = w
			total += w
		var pick := rng.randf() * total
		var chosen := ""
		for g: String in weights:
			pick -= float(weights[g])
			if pick <= 0.0:
				chosen = g
				break
		if chosen == "" or keep_old:
			continue
		var group: Array = ROOF_GROUPS[chosen]
		var cand := String(group[rng.randi() % group.size()])
		if cand == asset or roof_of(asset) == chosen and rng.randf() < 0.7:
			continue
		if not fits_cb.call(cand, lot["pos"], lot["yaw"]):
			continue
		lot["asset"] = cand
		changed += 1
	return changed


## Instance colour of a lot: palette tint x per-house variation x shabbiness (darker, greyer, poorer lots most).
static func lot_tint(prof: Dictionary, lot: Dictionary) -> Color:
	var base: Color = prof["tint"]
	var seed_i := int(lot.get("seed", 0))
	var j := float(absi(hash([seed_i, 17])) % 1000) / 1000.0
	var j2 := float(absi(hash([seed_i, 29])) % 1000) / 1000.0
	var v := 0.93 + 0.07 * j                              # brightness 0.93..1.0
	var warm := (j2 - 0.5) * 0.06
	var col := Color(clampf(base.r * v + warm, 0.0, 1.0), clampf(base.g * v, 0.0, 1.0), clampf(base.b * v - warm, 0.0, 1.0), 1.0)
	var shabby := float(prof.get("shabby", 0.0))
	if shabby > 0.0:
		var poor := 1.0 - float(lot.get("wealth", 0.5))
		var k := clampf(shabby * (0.45 + 0.9 * poor), 0.0, 0.9)
		var grey := (col.r + col.g + col.b) / 3.0
		col = col.lerp(Color(grey, grey * 0.97, grey * 0.92), k * 0.7) * (1.0 - 0.28 * k)
		col.a = 1.0
	return col


## A copy of a Meshy material that reads vertex colour (so a MultiMesh instance colour tints it). Cached per material.
static func vc_material(mat: Material) -> Material:
	var sm := mat as BaseMaterial3D
	if sm == null or sm.vertex_color_use_as_albedo:
		return mat
	var key := sm.get_instance_id()
	if _mat_cache.has(key):
		return _mat_cache[key]
	var m := sm.duplicate() as BaseMaterial3D
	m.vertex_color_use_as_albedo = true
	m.vertex_color_is_srgb = true
	_mat_cache[key] = m
	return m


# ================================================================ colour language: banners, bunting, awnings
static func _vc_material() -> StandardMaterial3D:
	var k := "vcmat"
	if _mat_cache.has(k):
		return _mat_cache[k]
	var m := StandardMaterial3D.new()
	m.vertex_color_use_as_albedo = true
	m.vertex_color_is_srgb = true
	m.roughness = 0.9
	m.specular_mode = BaseMaterial3D.SPECULAR_DISABLED
	_mat_cache[k] = m
	return m


static func _box(st: SurfaceTool, c: Vector3, sz: Vector3, col: Color) -> void:
	var h := sz * 0.5
	var v := [Vector3(-h.x, -h.y, -h.z), Vector3(h.x, -h.y, -h.z), Vector3(h.x, h.y, -h.z), Vector3(-h.x, h.y, -h.z),
		Vector3(-h.x, -h.y, h.z), Vector3(h.x, -h.y, h.z), Vector3(h.x, h.y, h.z), Vector3(-h.x, h.y, h.z)]
	var faces := [[0, 3, 2, 1], [4, 5, 6, 7], [0, 4, 7, 3], [1, 2, 6, 5], [0, 1, 5, 4], [3, 7, 6, 2]]
	for f: Array in faces:
		var shade := 1.0
		if f[0] == 0 and f[1] == 4:
			shade = 0.86
		elif f[0] == 1:
			shade = 0.92
		elif f[0] == 0 and f[1] == 1:
			shade = 0.7
		var cc := Color(col.r * shade, col.g * shade, col.b * shade, 1.0)
		for idx in [0, 1, 2, 0, 2, 3]:
			st.set_color(cc)
			st.add_vertex(c + v[f[idx]])


static func _finish(st: SurfaceTool) -> ArrayMesh:
	st.generate_normals()
	var m := st.commit()
	m.surface_set_material(0, _vc_material())
	return m


## Town-coloured variant of a shared dressing mesh (banner pole, wall banner, bunting, shop awning); null = use the stock mesh.
## Cached per key + colour pair, so every town with the same colours shares one mesh and one draw per cell.
static func mesh_variant(prof: Dictionary, key: String) -> Mesh:
	if prof.is_empty() or bool(prof.get("legacy", false)):
		return null
	var c1: Color = (prof["banner"] as Array)[0]
	var c2: Color = (prof["banner"] as Array)[1]
	if key == "d:striped_awning" or key == "striped_awning":
		c1 = (prof["awning"] as Array)[0]
		c2 = (prof["awning"] as Array)[1]
	var ck := "%s|%s|%s" % [key, c1.to_html(false), c2.to_html(false)]
	if _mesh_cache.has(ck):
		return _mesh_cache[ck]
	var m: Mesh = null
	match key:
		"banner_pole":
			m = _banner_pole(c1, c2)
		"wall_banner", "d:wall_banner":
			m = _recolour(Assets.building_mesh("wall_banner"), {"RA_Cloth": c1, "RA_Crown": c2})
		"bunting":
			m = _recolour(Assets.building_mesh("bunting"), {"RA_Cloth": c1})
		"d:striped_awning", "striped_awning":
			m = _awning(c1, c2)
	if m != null:
		m.resource_name = "%s_town" % key.replace("d:", "")      # the world lint recognises hanging banners / bunting by name
	_mesh_cache[ck] = m
	return m


static func _recolour(src: ArrayMesh, by_name: Dictionary) -> Mesh:
	if src == null:
		return null
	var out := ArrayMesh.new()
	for i in src.get_surface_count():
		out.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, src.surface_get_arrays(i))
		var mat := src.surface_get_material(i)
		var nm := mat.resource_name if mat != null else ""
		out.surface_set_material(i, Assets.flat_material(by_name[nm]) if by_name.has(nm) else mat)
	return out


static func _banner_pole(c1: Color, c2: Color) -> Mesh:
	var st := SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_TRIANGLES)
	var wood := Color(0.30, 0.20, 0.12)
	var gold := Color(0.85, 0.68, 0.22)
	_box(st, Vector3(-0.5, 1.9, 0.0), Vector3(0.14, 3.8, 0.14), wood)
	_box(st, Vector3(-0.5, 3.85, 0.0), Vector3(0.24, 0.16, 0.24), gold)
	_box(st, Vector3(0.0, 3.5, 0.0), Vector3(1.1, 0.08, 0.08), wood)
	_box(st, Vector3(0.0, 2.55, 0.0), Vector3(0.92, 1.9, 0.05), c1)
	_box(st, Vector3(0.0, 2.95, 0.03), Vector3(0.92, 0.36, 0.04), c2)
	_box(st, Vector3(0.0, 2.2, 0.03), Vector3(0.28, 0.5, 0.04), c2)
	_box(st, Vector3(-0.3, 1.45, 0.0), Vector3(0.3, 0.4, 0.05), c1)
	_box(st, Vector3(0.3, 1.45, 0.0), Vector3(0.3, 0.4, 0.05), c1)
	return _finish(st)


static func _awning(c1: Color, c2: Color) -> Mesh:
	var st := SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_TRIANGLES)
	for i in 7:
		_box(st, Vector3(-1.05 + i * 0.35, 0.0, 0.5), Vector3(0.35, 0.05, 1.0), c1 if i % 2 == 0 else c2)
	_box(st, Vector3(0, -0.12, 1.0), Vector3(2.45, 0.22, 0.05), c1)
	return _finish(st)


## Share of red (vs green) market stalls: warm banner towns lean red, green / blue / teal towns lean green.
static func stall_red_share(prof: Dictionary) -> float:
	if prof.is_empty() or bool(prof.get("legacy", false)):
		return 0.55
	var c: Color = (prof["awning"] as Array)[0]
	var hue := c.h
	var warm := hue < 0.12 or hue > 0.78
	return 0.8 if warm else (0.45 if hue < 0.2 else 0.18)


## How many crop fields ring the town (1.0 = the old count): farming and pastoral towns sprawl into fields, mines and holds do not.
static func field_mult(prof: Dictionary) -> float:
	if prof.is_empty() or bool(prof.get("legacy", false)):
		return 1.0
	var m := 1.0
	for y: Dictionary in prof.get("yards", []):
		if String(y.get("kind", "")) == "fields":
			m += 0.5 * float(y.get("n", 1)) / 3.0
	match String(prof.get("arch", "")):
		"farming":
			m += 0.45
		"pastoral":
			m += 0.2
		"mining", "criminal", "scholarly", "fortress":
			m -= 0.45
		"religious", "hunting", "fishing":
			m -= 0.25
	return clampf(m, 0.4, 2.2)


## A generated GLB as one merged mesh centred on x/z with its base on y = 0, optionally scaled to `target` metres on its longest
## horizontal side. Cached for the session; null when the file is missing.
static func fitted(path: String, target := 0.0) -> ArrayMesh:
	var key := "%s@%s" % [path, target]
	if _fit_cache.has(key):
		return _fit_cache[key]
	var out: ArrayMesh = null
	if ResourceLoader.exists(path):
		var raw := Assets.merged_mesh(path)
		if raw != null:
			var box := raw.get_aabb()
			var sc := 1.0 if target <= 0.0 else target / maxf(maxf(box.size.x, box.size.z), 0.001)
			var fit := Transform3D(Basis.IDENTITY.scaled(Vector3.ONE * sc),
				Vector3(-(box.position.x + box.size.x * 0.5) * sc, -box.position.y * sc, -(box.position.z + box.size.z * 0.5) * sc))
			out = Assets._transformed(raw, fit, false)
	_fit_cache[key] = out
	return out


## Mesh of a dressing id: a SettlementBuilder building key, "g:<path under assets/generated>" (fitted) or "d:<house detail>".
static func mesh_by_id(id: String) -> Mesh:
	if id.begins_with("g:"):
		return fitted(GEN + id.substr(2) + ".glb")
	if id.begins_with("d:"):
		return HouseDetails.mesh_for(id.substr(2))
	return Assets.building_mesh(id)


# ================================================================ dressing (DistrictProps)
static func prop_mult(prof: Dictionary, id: String) -> float:
	if prof.is_empty():
		return 1.0
	var pm: Dictionary = prof.get("prop_mult", {})
	var m := float(pm.get(id, 1.0))
	if id == "street_lamp" or id == "lamp_post":
		m *= float(prof.get("lamps", 1.0))
	elif id.begins_with("market_stall"):
		m *= float(prof.get("stalls", 1.0))
	return m


## The kit specs of a profile for one district kind, as DistrictProps spec dictionaries (no "in" key).
static func kit_specs(prof: Dictionary, dk: String) -> Array:
	var out: Array = []
	for sp: Dictionary in prof.get("dress", []):
		if (sp["in"] as Array).has(dk):
			var e := sp.duplicate()
			e.erase("in")
			out.append(e)
	return out


# ================================================================ people and street life
## Multiplier per micro-event id for this town (micro_events.gd weight_of reads ctx["town_bias"]).
static func activity_bias(sid: int) -> Dictionary:
	if _bias_cache.has(sid):
		return _bias_cache[sid]
	var out := {}
	var prof := of_id(sid)
	if not prof.is_empty():
		var groups: Dictionary = data().get("activity_groups", {})
		var act: Dictionary = prof.get("activity", {})
		for g: String in act:
			var m := float(act[g])
			for id: String in groups.get(g, []):
				out[id] = clampf(float(out.get(id, 1.0)) * m, 0.15, 3.5)
	_bias_cache[sid] = out
	return out


## Busy-ness of the streets (merchant towns teem, hamlets are quiet): multiplies Schedule.street_activity.
static func busy(sid: int) -> float:
	var prof := of_id(sid)
	return float(prof.get("busy", 1.0)) if not prof.is_empty() else 1.0


## WorldSim job index of person `i` of a town: fortress towns draw more guards, criminal towns fewer (job 3 = guard,
## 4 = labourer). Deterministic on (town, person); the caller keeps its own RNG stream untouched.
static func adjust_job(job: int, s: Dictionary, i: int) -> int:
	var g := float(profile(s).get("guards", 1.0))
	if g == 1.0:
		return job
	var roll := float(absi(hash([int(s.get("id", 0)), i, 313])) % 1000) / 1000.0
	if job == 3 and g < 1.0 and roll > g:
		return 4
	if job != 3 and job != 2 and g > 1.0 and roll < (g - 1.0) * 0.12:
		return 3
	return job


## Clothing / uniform tint for a villager of town `sid`: guards wear the town's uniform colour, everyone else a colour of its
## palette (archetype + culture). Returns [Color, strength].
static func person_tint(sid: int, person: int, is_guard: bool) -> Array:
	var prof := of_id(sid)
	if prof.is_empty() or bool(prof.get("legacy", false)):
		return [Color.WHITE, 0.0]
	if is_guard:
		return [prof["guard"], 0.62]
	var cloth: Array = prof["cloth"]
	if cloth.is_empty():
		return [Color.WHITE, 0.0]
	return [cloth[absi(hash([person, 91])) % cloth.size()], 0.34]


## Tint a character model's materials (duplicated and cached per source material + colour, so a town's villagers share a
## handful of materials; the shared character materials are never touched).
static func tint_model(model: Node, color: Color, strength: float) -> void:
	if strength <= 0.0:
		return
	var mul := Color.WHITE.lerp(color, strength)
	for n in model.find_children("*", "MeshInstance3D", true, false):
		var mi := n as MeshInstance3D
		if mi.mesh == null:
			continue
		for si in mi.mesh.get_surface_count():
			var mat := mi.get_active_material(si) as BaseMaterial3D
			if mat == null:
				continue
			var key := "%d|%s" % [mat.get_instance_id(), mul.to_html(false)]
			var ov: Material = _mat_cache.get(key)
			if ov == null:
				var m2 := mat.duplicate() as BaseMaterial3D
				m2.albedo_color = mat.albedo_color * mul
				_mat_cache[key] = m2
				ov = m2
			mi.set_surface_override_material(si, ov)


# ================================================================ village signatures
static func _street_of_layout(layout: String) -> String:
	match layout:
		"strung", "bank":
			return "linear"
		"hold", "close", "lanes":
			return "cluster"
		"radial":
			return "crossroads"
		"campus", "green":
			return "green"
	return ""


static func _vsig_distance(a: Dictionary, b: Dictionary) -> float:
	return 0.7 * _jaccard(a["features"], b["features"]) + 0.3 * (0.0 if a["street"] == b["street"] else 1.0)


## Signature of one village / hamlet: {street, features}. Assigned for ALL villages of the world at once (cached) so that no two
## share a feature set: greedy in id order, each picks its best-scoring set (archetype + terrain affinity + a seeded jitter) that
## stays >= 0.55 (relaxing to 0.45 / 0.35 / 0.2) away from every set already given out. {} for towns.
static func village_sig(s: Dictionary) -> Dictionary:
	var list: Array = WorldGen.settlements
	if list.is_empty():
		return {}
	var key := "%d|%s|%d,%d" % [list.size(), String((list[0] as Dictionary).get("name", "")), roundi(((list[-1] as Dictionary)["pos"] as Vector2).x), roundi(((list[-1] as Dictionary)["pos"] as Vector2).y)]
	if key != _vsig_key:
		_vsig_cache = _assign_villages(list)
		_vsig_key = key
	return _vsig_cache.get(int(s.get("id", -1)), {})


static func _assign_villages(list: Array) -> Dictionary:
	var towns: Dictionary = data().get("towns", {})
	var out := {}
	var chosen: Array = []
	var street_use := {}
	var feat_use := {}
	for st: Dictionary in list:
		var sz := size_class(st)
		if sz != "village" and sz != "hamlet":
			continue
		var e: Dictionary = towns.get(String(st.get("name", "")), {})
		if e.is_empty():
			e = _auto_entry(st)
		var arch_id := String(e.get("arch", "farming"))
		if arch_id == "royal":
			continue
		var arch: Dictionary = (data().get("archetypes", {}) as Dictionary).get(arch_id, {})
		var sn := sense(st)
		var tags: Array = []
		if float(sn["relief"]) >= 105.0:
			tags.append("hill")
		if float(sn["forest"]) >= 0.37:
			tags.append("forest")
		tags.append_array(e.get("terrain", []))
		tags.append_array(e.get("hint", []))
		var rng := RandomNumberGenerator.new()
		rng.seed = absi(hash([int(st.get("id", 0)), String(st.get("name", "")), roundi((st["pos"] as Vector2).x), roundi((st["pos"] as Vector2).y)]))
		var layout := String(e.get("layout", arch.get("layout", "loose")))
		var street := _street_of_layout(layout)
		if street == "":
			var best_n := 999
			var order := VILLAGE_STREETS.duplicate()
			for i in order.size():       # seeded shuffle, then the least used pattern wins
				var j := rng.randi() % order.size()
				var tmp = order[i]
				order[i] = order[j]
				order[j] = tmp
			for cand: String in order:
				if int(street_use.get(cand, 0)) < best_n:
					best_n = int(street_use.get(cand, 0))
					street = cand
		street_use[street] = int(street_use.get(street, 0)) + 1
		var k := 2 if sz == "hamlet" else 3
		var aff := {}
		for f: String in VILLAGE_FEATURES:
			var v := float((VF_ARCH.get(f, {}) as Dictionary).get(arch_id, 0))
			for t: String in tags:
				v += float((VF_TERRAIN.get(f, {}) as Dictionary).get(t, 0))
			aff[f] = v
		var cands: Array = []
		var n := VILLAGE_FEATURES.size()
		for i in n:
			for j in range(i + 1, n):
				for l in range(j + 1, n) if k == 3 else range(j, j + 1):
					var set: Array = [VILLAGE_FEATURES[i], VILLAGE_FEATURES[j]] if k == 2 else [VILLAGE_FEATURES[i], VILLAGE_FEATURES[j], VILLAGE_FEATURES[l]]
					if k == 2 and l != j:
						continue
					if set.has("pond") and set.has("jetty"):
						continue
					if set.has("jetty") and float(aff["jetty"]) < 3.0:
						continue          # a jetty needs water or a fishing trade
					var sc := 0.0
					for f: String in set:
						sc += float(aff[f]) - 0.9 * float(feat_use.get(f, 0))      # spread the vocabulary: popular features get dearer
					cands.append([sc + rng.randf_range(0.0, 2.2), set])
		cands.sort_custom(func(x: Array, y: Array) -> bool: return float(x[0]) > float(y[0]))
		var pick: Array = []
		for thr: float in [0.55, 0.45, 0.35, 0.2]:
			for c: Array in cands:
				var sig := {"street": street, "features": c[1]}
				var ok := true
				for o: Dictionary in chosen:
					if _vsig_distance(sig, o) < thr:
						ok = false
						break
				if ok:
					pick = c[1]
					break
			if not pick.is_empty():
				break
		if pick.is_empty():
			pick = (cands[0] as Array)[1]
		var sigd := {"street": street, "features": pick}
		chosen.append(sigd)
		for f: String in pick:
			feat_use[f] = int(feat_use.get(f, 0)) + 1
		out[int(st.get("id", 0))] = sigd
	return out


## Village-only distance: half the full profile distance, half the signature (feature-set Jaccard + street pattern).
static func village_distance(a: Dictionary, b: Dictionary) -> float:
	return 0.5 * distance(a, b) + 0.5 * _vsig_distance(a["vsig"], b["vsig"])


# ================================================================ signature and distinctness
## Named features of a profile (the "town signature" the report lists).
static func signature(prof: Dictionary) -> Dictionary:
	return {"name": prof["name"], "arch": prof["arch"], "realm": prof["realm"], "flavour": prof["flavour"], "size": prof["size"],
		"culture": prof["culture"] + ("+" + String(prof["influence"]) if String(prof["influence"]) != "" else ""),
		"roof": prof["roof_main"], "palette": prof["palette"], "wall": prof["wall"], "layout": prof["layout"],
		"banner": "%s/%s" % [(prof["banner"][0] as Color).to_html(false), (prof["banner"][1] as Color).to_html(false)],
		"guard": (prof["guard"] as Color).to_html(false), "guards": prof["guards"], "kits": prof["kits"], "terrain": prof["terrain"],
		"street": String((prof["vsig"] as Dictionary).get("street", "")), "features": (prof["vsig"] as Dictionary).get("features", [])}


static func _jaccard(a: Array, b: Array) -> float:
	if a.is_empty() and b.is_empty():
		return 0.0
	var inter := 0
	for x in a:
		if b.has(x):
			inter += 1
	var uni := a.size() + b.size() - inter
	return 1.0 - float(inter) / float(maxi(uni, 1))


static func _cdist(a: Color, b: Color) -> float:
	return sqrt((a.r - b.r) * (a.r - b.r) + (a.g - b.g) * (a.g - b.g) + (a.b - b.b) * (a.b - b.b)) / 1.732


## Pairwise visual distance 0..1 (weighted Gower: categorical mismatches, roof-mix L1, colour distances, kit Jaccard).
static func distance(a: Dictionary, b: Dictionary) -> float:
	var acc := [0.0, 0.0]
	var add := func(w: float, v: float) -> void:
		acc[0] += w * clampf(v, 0.0, 1.0)
		acc[1] += w
	add.call(2.0, 0.0 if a["arch"] == b["arch"] else 1.0)
	var l1 := 0.0
	for k: String in ROOF_KINDS:
		l1 += absf(float((a["roof"] as Dictionary).get(k, 0.0)) - float((b["roof"] as Dictionary).get(k, 0.0)))
	add.call(2.0, l1 * 0.5)
	add.call(1.0, 0.0 if a["wall"] == b["wall"] else 1.0)
	add.call(1.5, 0.0 if a["layout"] == b["layout"] else 1.0)
	add.call(1.0, _cdist(a["tint"], b["tint"]) * 4.0)
	add.call(0.5, absf(float(a["shabby"]) - float(b["shabby"])))
	add.call(1.5, (_cdist((a["banner"] as Array)[0], (b["banner"] as Array)[0]) + _cdist((a["banner"] as Array)[1], (b["banner"] as Array)[1])) * 0.9)
	add.call(0.7, _cdist(a["guard"], b["guard"]) * 1.6)
	add.call(0.5, absf(float(a["guards"]) - float(b["guards"])) * 0.5)
	add.call(2.5, _jaccard(a["kits"], b["kits"]))
	add.call(0.5, absf(SIZE_CLASSES.find(a["size"]) - SIZE_CLASSES.find(b["size"])) / 4.0)
	add.call(0.5, _jaccard(a["terrain"], b["terrain"]))
	add.call(0.5, 0.0 if (a["culture"] == b["culture"] and a["influence"] == b["influence"]) else 1.0)
	return float(acc[0]) / float(acc[1])


## {rows: [signature + nearest {name, distance}], min_distance, min_pair, mean_distance, pairs, threshold, violations}.
static func report(settlements: Array, threshold := 0.2) -> Dictionary:
	var profs: Array = []
	for s: Dictionary in settlements:
		profs.append(profile(s))
	var rows: Array = []
	var min_d := 9.0
	var min_pair := ["", ""]
	var sum := 0.0
	var pairs := 0
	var bad: Array = []
	for i in profs.size():
		var near_d := 9.0
		var near_n := ""
		for j in profs.size():
			if i == j:
				continue
			var dd := distance(profs[i], profs[j])
			if dd < near_d:
				near_d = dd
				near_n = String(profs[j]["name"])
			if j > i:
				sum += dd
				pairs += 1
				if dd < min_d:
					min_d = dd
					min_pair = [profs[i]["name"], profs[j]["name"]]
				if dd < threshold:
					bad.append([profs[i]["name"], profs[j]["name"], dd])
		var row := signature(profs[i])
		row["nearest"] = near_n
		row["nearest_distance"] = near_d
		rows.append(row)
	var vil: Array = []
	for pr: Dictionary in profs:
		if not (pr["vsig"] as Dictionary).is_empty():
			vil.append(pr)
	var vmin := 9.0
	var vpair := ["", ""]
	var vsum := 0.0
	var vpairs := 0
	var vbad: Array = []
	for i in vil.size():
		for j in range(i + 1, vil.size()):
			var vd := village_distance(vil[i], vil[j])
			vsum += vd
			vpairs += 1
			if vd < vmin:
				vmin = vd
				vpair = [vil[i]["name"], vil[j]["name"]]
			if vd < VILLAGE_THRESHOLD:
				vbad.append([vil[i]["name"], vil[j]["name"], vd])
	return {"villages": vil.size(), "village_min_distance": vmin, "village_min_pair": vpair, "village_mean_distance": vsum / maxf(vpairs, 1),
		"village_pairs": vpairs, "village_threshold": VILLAGE_THRESHOLD, "village_violations": vbad,
		"rows": rows, "min_distance": min_d, "min_pair": min_pair, "mean_distance": sum / maxf(pairs, 1), "pairs": pairs, "threshold": threshold, "violations": bad}
