class_name ElementFX
extends RefCounted
## Elemental VFX set: 8 elements x (charge, aura, projectile, beam, impact, aoe, status) plus
## generic melee / dash / level-up effects. Scenes live in scenes/vfx/elements/<element>/<type>.tscn
## (generated by tools_qa/vfx_gallery/build_element_scenes.gd, shaders in shaders/vfx_elements/).
## Every effect is pooled: play() reuses a hidden instance, finished one-shots return themselves.
## Looping effects (charge, aura, beam, projectile, status) return the node: pass it to stop().
##
## Elements: fire water earth wind lightning ice light dark
##   aliases: frost -> ice, holy/heal -> light, shadow/void -> dark, qi -> light (see canon()).
##
##   ElementFX.play(&"fire", &"impact", pos, dir, scale)            one-shot or looping, world position
##   ElementFX.attach(&"water", &"charge", hand_node, scale)        looping, follows `node`
##   ElementFX.stop(fx)                                             fade a looping effect out
##   ElementFX.projectile(&"fire", from, to, speed, scale) -> fx    flies, then plays the impact itself
##   ElementFX.beam(&"lightning", from, to, width, seconds) -> fx   update with ElementFX.aim_beam()
##   ElementFX.aoe(&"earth", ground_pos, radius)                    ground area effect
##   ElementFX.chain(&"lightning", [p0, p1, p2...])                 arcs hopping along the points
##   ElementFX.slash(&"fire", pos, yaw, tilt, radius, fist)         sword / fist slash arc, element tinted
##   ElementFX.hit_sparks(&"ice", pos, dir)   ElementFX.dash(&"wind", character)   ElementFX.level_up(pos, &"light")
##   ElementFX.warmup(parent)                                       instantiate everything once (shader compile)
## Directions are world vectors; effects point along -Z (Godot forward), so a projectile
## `dir` of (to - from) works directly. Gameplay code owns timing/damage: see docs/art/vfx_elements/README.md.

const ELEMENTS: Array[StringName] = [&"fire", &"water", &"earth", &"wind", &"lightning", &"ice", &"light", &"dark"]
const TYPES: Array[StringName] = [&"charge", &"aura", &"projectile", &"beam", &"impact", &"aoe", &"status"]
const GENERIC: Array[StringName] = [&"slash_sword", &"slash_fist", &"hit_sparks", &"dash", &"level_up"]
const ROOT := "res://scenes/vfx/elements/"
const AOE_RADIUS := 3.0          ## radius in metres of an aoe scene at scale 1
const BEAM_LENGTH := 1.0         ## beam scenes are 1 m long along -Z, scaled to the requested length

const ALIASES := {
	&"frost": &"ice", &"snow": &"ice", &"holy": &"light", &"heal": &"light", &"qi": &"light", &"metal": &"light",
	&"shadow": &"dark", &"void": &"dark", &"air": &"wind", &"storm": &"lightning", &"thunder": &"lightning",
	&"wood": &"earth", &"stone": &"earth", &"ember": &"fire", &"flame": &"fire", &"ocean": &"water",
}

## Palette per element: core (hot centre), mid (body), edge (rim). Warm storybook tones, never neon.
const PAL := {
	&"fire": {"core": Color(1.0, 0.92, 0.6), "mid": Color(1.0, 0.5, 0.12), "edge": Color(0.72, 0.16, 0.05)},
	&"water": {"core": Color(0.86, 0.97, 1.0), "mid": Color(0.28, 0.66, 0.95), "edge": Color(0.08, 0.28, 0.62)},
	&"earth": {"core": Color(0.98, 0.86, 0.5), "mid": Color(0.72, 0.5, 0.26), "edge": Color(0.36, 0.22, 0.12)},
	&"wind": {"core": Color(0.96, 1.0, 0.96), "mid": Color(0.6, 0.95, 0.78), "edge": Color(0.26, 0.66, 0.6)},
	&"lightning": {"core": Color(1.0, 0.98, 0.82), "mid": Color(0.62, 0.72, 1.0), "edge": Color(0.36, 0.26, 0.9)},
	&"ice": {"core": Color(0.96, 1.0, 1.0), "mid": Color(0.58, 0.86, 1.0), "edge": Color(0.22, 0.48, 0.86)},
	&"light": {"core": Color(1.0, 0.99, 0.9), "mid": Color(1.0, 0.86, 0.46), "edge": Color(0.92, 0.6, 0.2)},
	&"dark": {"core": Color(0.86, 0.62, 1.0), "mid": Color(0.42, 0.16, 0.62), "edge": Color(0.09, 0.03, 0.17)},
}

static var _scenes := {}         # path -> PackedScene
static var _pool := {}           # "element/type" -> Array[ElementEffect]
static var _live := 0


static func canon(element: Variant) -> StringName:
	var e := StringName(String(element).to_lower())
	if ALIASES.has(e):
		return ALIASES[e]
	return e if PAL.has(e) else &"light"


static func palette(element: Variant) -> Dictionary:
	return PAL[canon(element)]


static func scene_path(element: StringName, type: StringName) -> String:
	if type in GENERIC:
		return ROOT + "generic/" + String(type) + ".tscn"
	return ROOT + String(element) + "/" + String(type) + ".tscn"


static func _tier() -> int:
	var ml := Engine.get_main_loop()
	if ml is SceneTree:
		var q := (ml as SceneTree).root.get_node_or_null("Quality")
		if q:
			return int(q.get("tier"))
	return 2


static func _default_parent() -> Node:
	var ml := Engine.get_main_loop()
	if ml is SceneTree:
		var t := ml as SceneTree
		return t.current_scene if t.current_scene else t.root
	return null


static func _take(element: StringName, type: StringName, parent: Node) -> ElementEffect:
	var key := String(element) + "/" + String(type)
	var arr: Array = _pool.get(key, [])
	while not arr.is_empty():
		var fx: ElementEffect = arr.pop_back()
		if is_instance_valid(fx) and not fx.is_queued_for_deletion():
			if fx.get_parent() != parent:
				if fx.get_parent():
					fx.reparent(parent, false)
				else:
					parent.add_child(fx)
			return fx
	var path := scene_path(element, type)
	var ps: PackedScene = _scenes.get(path)
	if ps == null:
		ps = load(path) as PackedScene
		if ps == null:
			push_warning("ElementFX: missing scene " + path)
			return null
		_scenes[path] = ps
	var inst := ps.instantiate() as ElementEffect
	inst.pooled_key = key
	inst.visible = false
	parent.add_child(inst)
	inst.finished.connect(_on_finished)
	return inst


static func _on_finished(fx: ElementEffect) -> void:
	if not is_instance_valid(fx):
		return
	if not _pool.has(fx.pooled_key):
		_pool[fx.pooled_key] = []
	var arr: Array = _pool[fx.pooled_key]
	if arr.size() < 6:
		arr.append(fx)
	else:
		fx.queue_free()


## Play `element`'s `type` at world `pos` facing `dir` (world, -Z forward; ZERO keeps identity).
## Returns the effect (a looping one until you stop() it) or null if the scene is missing.
static func play(element: Variant, type: StringName, pos: Vector3, dir := Vector3.ZERO, scale := 1.0, parent: Node = null) -> ElementEffect:
	var el := canon(element)
	if parent == null:
		parent = _default_parent()
	if parent == null:
		return null
	var fx := _take(el, type, parent)
	if fx == null:
		return null
	_place(fx, pos, dir, scale)
	fx.play_fx(_tier())
	if type in GENERIC and element != null and String(element) != "":
		fx.tint(PAL[el])
	return fx


static func _place(fx: ElementEffect, pos: Vector3, dir: Vector3, scale: float) -> void:
	var b := Basis.IDENTITY
	if dir.length_squared() > 0.0001:
		var f := dir.normalized()
		var up := Vector3.UP if absf(f.y) < 0.98 else Vector3.RIGHT
		b = Basis.looking_at(f, up)
	fx.global_transform = Transform3D(b.scaled(Vector3.ONE * scale), pos)


## Looping effect glued to `node` (hand bone attachment, character root...). Local origin.
static func attach(element: Variant, type: StringName, node: Node3D, scale := 1.0, offset := Vector3.ZERO) -> ElementEffect:
	var fx := _take(canon(element), type, node)
	if fx == null:
		return null
	fx.transform = Transform3D(Basis.IDENTITY.scaled(Vector3.ONE * scale), offset)
	fx.play_fx(_tier())
	return fx


static func stop(fx: Variant, fade := 0.25) -> void:
	if is_instance_valid(fx) and fx is ElementEffect:
		(fx as ElementEffect).stop_fx(fade)


## Missile that flies from `from` to `to` at `speed` m/s (with its trail), then stops and plays the
## element's impact where it lands. `on_hit` (Callable, optional) is called on arrival.
static func projectile(element: Variant, from: Vector3, to: Vector3, speed := 18.0, scale := 1.0, on_hit := Callable(), parent: Node = null) -> ElementEffect:
	var el := canon(element)
	var dir := to - from
	var fx := play(el, &"projectile", from, dir, scale, parent)
	if fx == null:
		return null
	var dur := maxf(dir.length() / maxf(speed, 0.1), 0.02)
	var tw := fx.create_tween()
	tw.tween_property(fx, "global_position", to, dur)
	tw.tween_callback(func() -> void:
		if is_instance_valid(fx):
			stop(fx, 0.12)
		play(el, &"impact", to, -dir, scale, parent)
		if on_hit.is_valid():
			on_hit.call())
	return fx


## Channelled beam between two points. `seconds` > 0 stops it by itself; else stop() it. Re-aim with aim_beam().
static func beam(element: Variant, from: Vector3, to: Vector3, width := 1.0, seconds := 0.0, parent: Node = null) -> ElementEffect:
	var fx := play(element, &"beam", from, to - from, 1.0, parent)
	if fx == null:
		return null
	aim_beam(fx, from, to, width)
	if seconds > 0.0:
		fx.get_tree().create_timer(seconds).timeout.connect(stop.bind(fx, 0.2))
	return fx


static func aim_beam(fx: ElementEffect, from: Vector3, to: Vector3, width := 1.0) -> void:
	if not is_instance_valid(fx):
		return
	var d := to - from
	var len := maxf(d.length(), 0.1)
	var f := d / len
	var up := Vector3.UP if absf(f.y) < 0.98 else Vector3.RIGHT
	var b := Basis.looking_at(f, up)
	if fx.has_meta("beam_len"):
		# fixed-shape beams (earth spike line): uniform scale so the meshes keep their proportions
		var s := len / float(fx.get_meta("beam_len"))
		b = b.scaled(Vector3.ONE * s * width)
	else:
		b = b.scaled(Vector3(width, width, len / BEAM_LENGTH))
	fx.global_transform = Transform3D(b, from)


## Ground area effect of `radius` metres centred on `pos`.
static func aoe(element: Variant, pos: Vector3, radius := AOE_RADIUS, parent: Node = null) -> ElementEffect:
	return play(element, &"aoe", pos, Vector3.ZERO, radius / AOE_RADIUS, parent)


## Short lightning arcs hopping along `points` (the gameplay chain: 0.07 s per hop).
static func chain(element: Variant, points: Array, width := 1.0, hop_time := 0.07, parent: Node = null) -> void:
	var tree := Engine.get_main_loop() as SceneTree
	for i in points.size() - 1:
		var a: Vector3 = points[i]
		var b: Vector3 = points[i + 1]
		if i == 0:
			beam(element, a, b, width, 0.3, parent)
		else:
			tree.create_timer(hop_time * i).timeout.connect(beam.bind(element, a, b, width, 0.25, parent))
		if i + 1 < points.size():
			tree.create_timer(hop_time * (i + 1)).timeout.connect(play.bind(element, &"impact", b, Vector3.ZERO, 0.45, parent))


## Sword (or fist) slash arc in front of `pos`. `yaw` faces -Z rotated about Y, `tilt` rolls the arc.
static func slash(element: Variant, pos: Vector3, yaw := 0.0, tilt := 0.0, radius := 1.6, fist := false, parent: Node = null) -> ElementEffect:
	var fx := play(element, &"slash_fist" if fist else &"slash_sword", pos, Vector3.ZERO, radius / 1.6, parent)
	if fx:
		fx.global_basis = Basis.from_euler(Vector3(0, yaw, tilt)).scaled(Vector3.ONE * radius / 1.6)
	return fx


static func hit_sparks(element: Variant, pos: Vector3, dir := Vector3.ZERO, scale := 1.0, parent: Node = null) -> ElementEffect:
	return play(element, &"hit_sparks", pos, dir, scale, parent)


## Dash streaks + dust at the character's feet, plus the game's ghost afterimages (VFX.afterimage) in the element colour.
static func dash(element: Variant, character: Node3D, dir := Vector3.ZERO, afterimages := 4, parent: Node = null) -> ElementEffect:
	var pal := palette(element)
	var p := parent if parent else character.get_parent()
	var d := dir if dir.length_squared() > 0.001 else -character.global_basis.z
	var fx := play(element, &"dash", character.global_position, d, 1.0, p)
	if afterimages > 0:
		VFX.afterimage(p, character, (pal["mid"] as Color).lerp(Color.WHITE, 0.2), afterimages, 0.05, 0.35)
	return fx


static func level_up(pos: Vector3, element: Variant = &"light", scale := 1.0, parent: Node = null) -> ElementEffect:
	return play(element, &"level_up", pos, Vector3.ZERO, scale, parent)


## Instantiate + play every effect once far below the world so shaders/pipelines compile before the first cast.
static func warmup(parent: Node) -> void:
	for el in ELEMENTS:
		for t in TYPES:
			var fx := play(el, t, Vector3(0, -500, 0), Vector3.ZERO, 0.01, parent)
			if fx:
				stop(fx, 0.0)
	for g in GENERIC:
		play(&"light", g, Vector3(0, -500, 0), Vector3.ZERO, 0.01, parent)
